kubernetes-sigs/azuredisk-csi-driver

deploy/azuredisk-csi-driver.yaml
pkg/azuredisk/identityserver.go

This commit adds csi liveness check to azure csi driver
/kind feature
Fixes #https://github.com/csi-driver/azuredisk-csi-driver/issues/31
```
enhance: adds csi liveness check for azure csi driver
```

[WIP] enhance: adds csi liveness check for azure csi driver

---

deploy/azuredisk-csi-driver.yaml
deploy/crd-csi-driver-registry.yaml
deploy/crd-csi-node-info.yaml
deploy/csi-azuredisk-provisioner.yaml
docs/install-azuredisk-csi-driver.md

fix deploy yaml files

---

OWNERS
OWNERS_ALIASES

/kind design
cc @feiskyer @khenidak @brendandburns
Fixes #
```
none
```

add OWNERS

---

pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go

/kind feature
This commit adds MaxVolumesPerNode info in NodeGetInfoResponse so the CO will decide how many volumes can be published on a node.
Fixes https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/30
```
Adds MaxVolumesPerNode info in NodeGetInfoResponse
```

Adds MaxVolumesPerNode info in NodeGetInfoResponse

---

pkg/azurediskplugin/main.go

/kind bug
This commit fixes info values not getting printed with klog.
Fixes https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/68
```
fix(klog): fix info values not getting printed with klog
```

fix(klog): fix info values not getting printed with klog

---

hack/boilerplate/boilerplate.Dockerfile.txt
hack/boilerplate/boilerplate.Makefile.txt
hack/boilerplate/boilerplate.bzl.txt
hack/boilerplate/boilerplate.go.txt
hack/boilerplate/boilerplate.py
hack/boilerplate/boilerplate.py.txt
hack/boilerplate/boilerplate.sh.txt
hack/verify-all.sh
hack/verify-boilerplate.sh

Add boilerplate check.
Fixes #59 
```
None
```

add boilerplate check

---

pkg/csi-common/utils.go
pkg/csi-common/utils_test.go

/kind bug
Mask secrets in logs.
```
fix secret value exposed in logs issue
```

Fix secret values exposed in logs issue

---

Gopkg.lock
docs/csi-dev.md
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
test/integration/run-test.sh

/kind feature
This PR implements the standard CSI snapshot functionalities, including:
- CreateSnapshot
- ListSnapshots
- DeleteSnapshot
This PR does not contain restore snapshot feature. It would be addressed next.
Fixes #25
```
add create/delete/list snapshot feature
```

add create/delete/list snapshot feature

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go

/kind feature
add snapshot restore functionality.
This PR copies CreateManagedDisk code from azure cloud provider, need to do the upstream change to azure cloud provider later.
Fixes #38
```
feat: add snapshot restore functionality
```

feat: add snapshot restore functionality

---

deploy/azuredisk-csi-driver.yaml
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go

/kind feature
This PR enables  mountOptions support
Fixes #33
```
fix: support mountOptions
```

fix: support mountOptions

---

.travis.yml

/kind design
Fixes #
The reason why we upgrade CI env os is that on Ubuntu 18.04, there are fewer sanity test failures compared to Ubuntu 16.04
```
```

chore: set CI to use ubuntu-18.04

---

.travis.yml
Makefile
test/sanity/README.md
test/sanity/run-tests-all-clouds.sh

/kind design
Fixes #
```
chore: enable sanity test in CI
```
cc @ZeroMagic

chore: enable sanity test in CI

---

deploy/example/azure.json
test/integration/azure.json
test/sanity/run-tests-all-clouds.sh

>
> /kind bug
> /kind design
> /kind flake
Fixes #
```
none
```

chore: don't run sanity test on Azure China Cloud

---

test/sanity/run-tests-all-clouds.sh

/kind design
Fixes #
```
none
```

chore: run sanity test in user mode

---

test/integration/run-test.sh

test: randomize volume name

---

.travis.yml
test/sanity/run-tests-all-clouds.sh

test: Change test config

---

Gopkg.lock
Gopkg.toml
pkg/azurediskplugin/main.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go

With this feature, we can get the prometheus metrics of azure_api.
- update the vendor "github.com/prometheus/client_golang"
- set the default metrics port to 10252
>
Fixes #84 
```
collect Prometheus metrics from this driver
```

feat: export prometheus metrics

---

deploy/v0.2.0/crd-csi-driver-registry.yaml
deploy/v0.2.0/crd-csi-node-info.yaml
deploy/v0.2.0/csi-azuredisk-controller.yaml
deploy/v0.2.0/csi-azuredisk-node.yaml
deploy/v0.2.0/rbac-csi-azuredisk-controller.yaml
docs/install-azuredisk-csi-driver.md
docs/install-csi-driver-master.md
docs/install-csi-driver-v0.2.0.md

docs: change deployment script
Fixes #
```
none
```

docs: change deployment script

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/version.go

Driver name should be a certain value. 
With the fix, "Identity Service GetPluginInfo [It] should return appropriate information" will be fixed.
Signed-off-by: ZeroMagic <anthonyliu@zju.edu.cn>
>
> /kind bug
Fixes #46
```
fix: set driver name
```

fix: set driver name

---

deploy/example/logs/0.2.0/csi-azuredisk-controller.log
deploy/example/logs/0.2.0/csi-azuredisk-node.log
deploy/example/logs/0.3.0/csi-azuredisk-controller.log
deploy/example/logs/0.3.0/csi-azuredisk-node.log

docs: add driver log example

---

pkg/azuredisk/controllerserver.go

/kind bug
check DiskSizeGB if it is nil or not
Fixes #
```
fix: check DiskSizeGB if it is nil or not
```

fix: check DiskSizeGB if it is nil or not

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go

/kind bug
Check the diskName before creating azure disk.
Fixes #46 
```
fix: set disk name as volume name
```

fix: check the diskName

---

test/sanity/sanity_test.go

/kind flake
- init klog flags
Because the version of klog is v0.3.3, we should init flags. So that we can get the logs from terminal.
Fixes #
```
none
```

test: init klog flags

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go

/kind bug
- set the default disk capacity
- compare the disk capacity when creating the disk
Fixes #46 
```
fix: compare the disk capacity
```

fix: check the disk capacity

---

test/sanity/sanity_test.go

/kind flake
In sanity test, we should get node id from ENV.
Fixes #46 
```
none
```

chore: get nodeid from env

---

pkg/azuredisk/controllerserver.go

/kind bug
- check snapshot id if it is empty
Fixes #46 
```
fix: check snapshot id if it is empty
```

fix: check snapshot id if it is empty

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go

/kind bug
- fix: validate snapshot name
With this PR, "should not fail when creating snapshot with maximum-length name" in sanity test will pass.
Fixes #46 
```
fix: validate snapshot name
```

fix: validate snapshot name

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go

/kind bug
When listing the snapshot, we should return empty when the specify snapshot id does not exist.
Fixes #46 
```
fix: return empty when the specify snapshot id does not exist
```

fix: return empty when the specify snapshot id does not exist

---

pkg/azuredisk/controllerserver.go

/kind bug
When creating the snapshot, we should return appropriate error code "AlreadyExists" if snapshot exists.
Fixes #46 
```
fix: return appropriate error code when snapshot exists
```

fix: return appropriate error code when snapshot exists

---

pkg/azuredisk/controllerserver.go

/kind bug
If the SourceVolumeId in request is not empty and does not match the listed snapshot's SourceVolumeId, we should return empty.
With this PR, we can fix `ListSnapshots [Controller Server] [It] should return empty when the specify source volume id is not exist`
Fixes #46
```
fix: return empty when the specify source volume id does not exist
```

fix: return empty when the specify source volume id does not exist

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go

/kind bug
With this PR, we can fix `ListSnapshots [Controller Server] [It] should return next token when a limited number of entries are requested `.
Fixes #46 
```
fix: return appropriate values according to StartingToken and MaxEntries
```

fix: return appropriate values according to StartingToken and MaxEntries

---

.travis.yml
test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh

/kind flake
skip one test sanity test failure in CI test.
Now sanity tests are totally credible.
Fixes #126 
```
none
```

chore: skip one test sanity test failure in CI test

---

test/e2e/dynamic_provisioning.go
test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go

/kind test
add e2e test "dynamically_provisioned_collocated_pod_test"
Fixes #
```
add e2e test "dynamically_provisioned_collocated_pod_test"
```

test: add e2e test "dynamically_provisioned_collocated_pod_test"

---

test/e2e/pre_provisioning.go
test/e2e/suite_test.go
test/e2e/testsuites/pre_provisioned_reclaim_policy_tester.go

/kind test
add e2e test "pre_provisioned_reclaim_policy_test"
Fixes #
```
add e2e test "pre_provisioned_reclaim_policy_test"
```

test: add e2e test "pre_provisioned_reclaim_policy_test"

---

test/e2e/dynamic_provisioning.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go

/kind test
add e2e test "dynamically_provisioned_read_only_volume_test"
Fixes #
```
add e2e test "dynamically_provisioned_read_only_volume_test"
```

test: add e2e test "dynamically_provisioned_read_only_volume_test"

---

test/e2e/pre_provisioning.go
test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
test/e2e/testsuites/testsuites.go

/kind test
add e2e test "pre_provisioned_read_only_volume_test"
Fixes #
```
add e2e test "pre_provisioned_read_only_volume_test"
```

test: add e2e test "pre_provisioned_read_only_volume_test"

---

test/e2e/dynamic_provisioning.go
test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go

/kind test
add e2e test "dynamically_provisioned_reclaim_policy_test"
Fixes #
```
add e2e test "dynamically_provisioned_reclaim_policy_test"
```

test: add e2e test "dynamically_provisioned_reclaim_policy_test"

---

README.md
deploy/v0.3.0/crd-csi-driver-registry.yaml
deploy/v0.3.0/crd-csi-node-info.yaml
deploy/v0.3.0/csi-azuredisk-controller.yaml
deploy/v0.3.0/csi-azuredisk-node.yaml
deploy/v0.3.0/rbac-csi-azuredisk-controller.yaml
docs/install-azuredisk-csi-driver.md
docs/install-csi-driver-v0.3.0.md

doc: cut off v0.3.0 beta release
Fixes #
```
doc: cut off v0.3.0 beta release
```

doc: cut off v0.3.0 beta release

---

deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml

doc: upgrade master deployment to use v0.4.0
Fixes #
```
none
```

doc: upgrade master deployment to use v0.4.0

---

deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml
deploy/v0.2.0/csi-azuredisk-controller.yaml
deploy/v0.2.0/csi-azuredisk-node.yaml
deploy/v0.3.0/csi-azuredisk-controller.yaml
deploy/v0.3.0/csi-azuredisk-node.yaml

/kind feature
Set priority class to system critical.
Fixes #148 
```
set priority class to system critical
```

feat: set priority class to system critical

---

charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml

chore: use latest version tag for master branch
Fixes #
```
none
```

chore: use latest version tag for master branch

---

deploy/example/rawblock/README.md
deploy/example/rawblock/nginx-pod-azuredisk.yaml
deploy/example/rawblock/pvc-azuredisk-csi.yaml
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
test/e2e/dynamic_provisioning.go
test/e2e/testsuites/testsuites.go

/kind feature
add raw block volume support
Fixes #27 
We can use the yaml files in `deploy/example/rawblock` to test the feature manully, and verify it according to the README.md.
```
feat: add raw block volume support
```

feat: add raw block volume support

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/nodeserver.go

/kind feature
support azure disk with partitions in disk mount
Fixes #144 
```
support azure disk with partitions in disk mount
```

feat: support azure disk with partitions in disk mount

---

charts/README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/v0.2.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/v0.2.0/azuredisk-csi-driver/values.yaml
charts/v0.3.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml

/kind flake
Because pods with system-node-critical priorityClass is not permitted in csi-demo namespace.
So we need to use kube-system instead of csi-demo.
Fixes #
```
```

chore: use kube-system instead of csi-demo

---

deploy/example/snapshot/README.md
deploy/example/snapshot/nginx-pod-restored-snapshot.yaml

add snapshot feature doc
Fixes #152 
```
add snapshot feature doc
```

docs: add snapshot feature doc

---

Makefile
pkg/azurediskplugin/Windows.Dockerfile

>
> /kind bug
> /kind design
> /kind test
> /kind flake
/kind feature
- Adds ability in the Makefile to accept custom registries from environment variables set. 
- Add the initial windows build targets and Dockerfile
Fixes #
```
```

Add custom image and windows build

---

pkg/azuredisk/controllerserver.go

/kind bug
controller should not depend on `cloud.InstanceID`, remove this dependency.
You may get following error without this PR:
```
I0930 20:58:23.803208       1 controllerserver.go:294] ControllerPublishVolume: called with args {VolumeId:/subscriptions/xxx/resourceGroups/chuwon/providers/Microsoft.Compute/disks/pvc-4f21dcfc-fe49-4100-89e8-68a205a01c97 NodeId:k8s-agentpool1-95854893-1 VolumeCapability:mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER >  Readonly:false Secrets:map[] VolumeContext:map[skuName:Standard_LRS storage.kubernetes.io/csiProvisionerIdentity:1569876755795-8081-disk.csi.azure.com] XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0}
E0930 20:58:23.825534       1 utils.go:117] …
```

fix getting instance id failure

---

README.md
charts/v0.4.0/azuredisk-csi-driver/Chart.yaml
charts/v0.4.0/azuredisk-csi-driver/templates/NOTES.txt
charts/v0.4.0/azuredisk-csi-driver/templates/_helpers.tpl
charts/v0.4.0/azuredisk-csi-driver/templates/crd-csi-driver-registry.yaml
charts/v0.4.0/azuredisk-csi-driver/templates/crd-csi-node-info.yaml
charts/v0.4.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/v0.4.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/v0.4.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
charts/v0.4.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
charts/v0.4.0/azuredisk-csi-driver/values.yaml
deploy/v0.4.0/crd-csi-driver-registry.yaml
deploy/v0.4.0/crd-csi-node-info.yaml
deploy/v0.4.0/csi-azuredisk-controller.yaml
deploy/v0.4.0/csi-azuredisk-node.yaml
deploy/v0.4.0/rbac-csi-azuredisk-controller.yaml
docs/install-azuredisk-csi-driver.md
docs/install-csi-driver-v0.4.0.md

doc: cut off v0.4.0 beta release
Fixes #
cc @chewong 
```
doc: cut off v0.4.0 beta release
```

doc: cut off v0.4.0 beta release

---

Makefile
README.md

add build-push make command and remove v0.1.0 version doc since it's not necessary
Fixes #
```
none
```

doc: add build-push make command

---

pkg/azurediskplugin/Dockerfile

/kind feature
fix: use secure ubuntu image
Fixes #
```
fix: use secure ubuntu image
```

fix: use secure ubuntu image

---

Makefile

>
> /kind bug
> /kind design
> /kind test
> /kind flake
```
I1028 07:39:58.347] DRIVER INFORMATION:
I1028 07:39:58.347] -------------------
I1028 07:39:58.347] Build Date: N/A
I1028 07:39:58.347] Compiler: gc
I1028 07:39:58.347] Driver Name: disk.csi.azure.com
I1028 07:39:58.348] Driver Version: N/A
I1028 07:39:58.348] Git Commit: N/A
I1028 07:39:58.348] Go Version: go1.12.12
I1028 07:39:58.348] Platform: linux/amd64
I1028 07:39:58.348] Topology Key: N/A
```
Various fields in the driver information are N/A …

Change package name in Makefile

---

pkg/azuredisk/nodeserver.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind test
> /kind flake
Add logging for Node{Publish/Unpublish}Volume. We need it to debug the azure disk driver.
Fixes #
```
```

Add logging for Node{Publish/Unpublish}Volume

---

pkg/azuredisk/azure_common_darwin.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind test
> /kind flake
Add mock functions to support running UTs on Mac
Fixes #
```
```

Add mock functions to support running UTs on mac

---

test/utils/credentials/credentials.go
test/utils/credentials/credentials_test.go

Signed-off-by: sph <shepenghui1@huawei.com>

fix golint errors

---

hack/verify-golint.sh
test/e2e/suite_test.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Noticed verify and e2e-single-az CI tests have failed in a lot of pending PRs. This PR should fix the issue and pending PRs should be rebased once this is merged.
Fixes #
```
None.
```

Fix verify and e2e CI error

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/nodeserver.go
pkg/mounter/safe_mounter_linux.go
pkg/mounter/safe_mounter_windows.go

>
> /kind bug
> /kind design
> /kind test
/kind feature
> /kind flake
This PR prepares the code for the windows support. 
Following are the changes:
- Separate out Linux and Windows mounter.
- Add default filesystem for windows as "ntfs"
- Add unimplemented CSIProxyMounter for windows which will be used to contact csi-proxy (https://github.com/kubernetes-csi/csi-proxy).
Fixes #
```
```

Windows support - set 1 - preparation

---

pkg/mounter/safe_mounter_unix.go
test/e2e/README.md
test/e2e/driver/azuredisk_csi_driver.go
test/e2e/driver/azuredisk_driver.go
test/e2e/driver/driver.go
test/e2e/dynamic_provisioning.go
test/e2e/pre_provisioning.go
test/e2e/suite_test.go

>
> /kind bug
> /kind design
/kind test
> /kind flake
Add support to run the tests with in-tree drivers
Fixes #161 
```
NONE
```

Add support to run the tests with in-tree drivers

---

test/e2e/manifest/in-tree-vmss.json
test/e2e/manifest/in-tree.json
test/e2e/manifest/multi-az.json
test/e2e/manifest/single-az.json

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fixes #
```
```

Update VM size to Standard_DS2_v2

---

test/e2e/suite_test.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
It's okay to have an empty nodeid string during E2E test.
Fixes #
```
```

Remove nodeid empty string check

---

test/e2e/dynamic_provisioning.go

/kind test
test: add xfs e2e test case
Fixes #
```
none
```

test: add xfs fsType e2e test case

---

Makefile
test/utils/azure/azure_helpers.go

>
> /kind bug
> /kind design
> /kind flake
/kind test
`creationTimestamp` tag will be used to determine whether we should delete stale resource groups in upstream test subscription (https://github.com/chewong/rg-cleanup/blob/master/main.go#L112-L134).
Fixes #
```
None.
```

Add job info tags to Azure resource groups

---

hack/verify-golint.sh

/kind test
This PR fixed below error:
```
Verifying gofmt
No issue found
Verifying govet
Done
/root/go/src/sigs.k8s.io/azuredisk-csi-driver/hack/verify-golint.sh: line 21: GOBIN: unbound variable
```
Fixes #
```
none
```

fix: golangci-lint error

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-controller.yaml
deploy/example/storageclass-azuredisk-csi-topology.yaml
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/identityserver.go
pkg/azuredisk/nodeserver.go

/kind feature
add topology(zone) support, refer to 
- https://kubernetes-csi.github.io/docs/topology.html
- https://kubernetes.io/docs/concepts/storage/storage-classes/#allowed-topologies
Fixes #89
cc @chewong 
```
add topology(zone) support
```

add topology(zone) support

---

deploy/example/snapshot/README.md
test/e2e/manifest/in-tree-vmss.json
test/e2e/manifest/in-tree.json
test/e2e/manifest/multi-az.json
test/e2e/manifest/single-az.json

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fixes #210 's failing e2e tests.
```
```

Enable VolumeSnapshotDataSource feature gate in API models

---

Gopkg.lock
charts/README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/example/resizing/README.md
deploy/example/resizing/storageclass-azuredisk-csi-resize.yaml
deploy/rbac-csi-azuredisk-controller.yaml
hack/verify-helm-chart.sh
pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/nodeserver.go

/kind test
/kind feature
/kind flake
Fixes #201 
```
complete resize feature
```

feat: complete resize feature

---

Gopkg.lock
test/e2e/suite_test.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
This PR should enable testgrid to list all test cases we ran in https://testgrid.k8s.io/provider-azure-master#pr-azuredisk-csi-driver-e2e-single-az.
/assign @andyzhangx  
Fixes #
```
None.
```

test: Run e2e test suite with JUnit reporter

---

docs/csi-dev.md

Since clone only works for one level, we will manually create the
`rexray` parent directory first.
>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fixes #
```
```

Fix clone process in dev setup doc

---

.gitignore
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/rbac-csi-azuredisk-controller.yaml
test/utils/azuredisk_log.sh

The following csi components provides builtin leader election support:
- csi-provisioner
- csi-attacher
- csi-snapshotter
- csi-resizer
To improve availability of controller service, we can enable leader
election in these components and allow the deployment to replica to 3.
for #177
>
/kind feature
Fixes #
```
```

Enable leader election in csi components

---

test/utils/azuredisk_log.sh

/kind test
chore: print out more driver logs
Fixes #
```
none
```

chore: print out more driver logs

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go

/kind feature
feat: BYOK(SSE+CMK) support
Actually BYOK is already supported in in-tree azure disk driver, this PR just switch to use `CreateManagedDisk` in azure cloud provider, and then BYOK would be also supported in CSI driver.
Fixes #
```
feat: BYOK(SSE+CMK) support
```

feat: BYOK(SSE+CMK) support

---

hack/verify-all.sh

/kind test
test: disable golint check since it does not work
Fixes #
looks like this an issue in `hack/verify-golint.sh`, it suddenly does not work today, it is always working before today, I will disable it first.
```
WARN [runner] Can't run linter unused: buildssa: analysis skipped: errors in package: [/root/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:59:14: undeclared name: azurediskDriver /root/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:74:16: undeclared name: azurediskDriver /root/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/pre_provisioning.go:113:16: undeclared name: azurediskDriver …
```

test: disable golint check since it does not work

---

docs/install-csi-driver-master.md
docs/install-csi-driver-v0.2.0.md
docs/install-csi-driver-v0.3.0.md
docs/install-csi-driver-v0.4.0.md

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fix a tiny doc issue: `watch` does not work in pipe
Fixes #
```
```

docs: watch does not work in pipe

---

pkg/azurediskplugin/Dockerfile

>
> /kind bug
> /kind design
> /kind test
/kind flake
mcr is the official register in msft
Fixes #
```
```

chore: use base-ubuntu image from mcr

---

charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml

/kind bug
fix: CVE-2019-11255 & mcr image migration
Fixes #202 
Fixes #208
cc @tilnl
```
fix: CVE-2019-11255 & mcr image migration
```

fix: CVE-2019-11255 & mcr image migration

---

charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml

/kind cleanup
chore: switch to mcr repo
Fixes #208
```
none
```

chore: switch to mcr repo

---

README.md
deploy/example/topology/README.md
test/utils/azuredisk_log.sh

Doc for version v0.5.0
Fixes #
```
none
```

Doc for version v0.5.0

---

README.md
charts/v0.5.0/azuredisk-csi-driver/Chart.yaml
charts/v0.5.0/azuredisk-csi-driver/templates/NOTES.txt
charts/v0.5.0/azuredisk-csi-driver/templates/_helpers.tpl
charts/v0.5.0/azuredisk-csi-driver/templates/crd-csi-driver-registry.yaml
charts/v0.5.0/azuredisk-csi-driver/templates/crd-csi-node-info.yaml
charts/v0.5.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/v0.5.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/v0.5.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
charts/v0.5.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
charts/v0.5.0/azuredisk-csi-driver/values.yaml
deploy/v0.5.0/crd-csi-driver-registry.yaml
deploy/v0.5.0/crd-csi-node-info.yaml
deploy/v0.5.0/csi-azuredisk-controller.yaml
deploy/v0.5.0/csi-azuredisk-node.yaml
deploy/v0.5.0/rbac-csi-azuredisk-controller.yaml
docs/install-azuredisk-csi-driver.md
docs/install-csi-driver-v0.5.0.md

doc: cut off v0.5.0 beta release
Fixes #
```
doc: cut off v0.5.0 beta release
```

doc: cut off v0.5.0 beta release

---

docs/csi-dev.md
pkg/azurediskplugin/main.go

/kind cleanup
remove nodeid restriction
Fixes #
```
none
```

chore: remove nodeid restriction

---

pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go

/kind cleanup
clean up the redundant code. 
Directly use bind mount in `NodePublishVolume`.
Fixes #
```
```

chore: clean up the redundant code

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/utils/check_driver_pods_restart.sh

/kind flake
before each e2e tests starts, check the driver pods if restarts
Fixes #246 
```
```

chore: add driver pods check

---

.travis.yml

/kind flake
fix broken Coverage
Fixes #259 
```
```

chore: fix broken coverage

---

test/e2e/manifest/single-az.json

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Adding a userAssignedID field in single-az.json API model. If not specified, the cluster will use system-assigned ID, which does not have permission to create Azure disks. 
Merging this manually since it only consists of API model change.
/cc @andyzhangx 
Fixes #
```
```

Add userAssignedID field in API model

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml
test/utils/check_driver_pods_restart.sh

/kind feature
This PR enable hostNetwork to support MSI on driver controller, and also change port 9602 to 9603 on node driver to avoid conflict.
Fixes #274
```
feat: eanble hostNetwork to support MSI
```

feat: enable hostNetwork to support MSI

---

charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
deploy/crd-csi-node-info.yaml
deploy/crd-csi-snapshot.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-driver.yaml
deploy/csi-azuredisk-node.yaml
deploy/csi-snapshot-controller.yaml
deploy/rbac-csi-snapshot-controller.yaml
docs/install-csi-driver-master.md
hack/verify-all.sh
hack/verify-yamllint.sh

/kind bug
fix: yaml file format
```
```
could leverage following site to check yaml format:
https://onlineyamltools.com/prettify-yaml
Fixes #275
```
none
```

fix: yaml file format

---

deploy/remove-driver.sh
hack/verify-yamllint.sh
pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/nodeserver.go

/kind cleanup
chore: scripts modification, refactor
Fixes #
```
none
```

chore: scripts modification

---

Gopkg.lock
vendor/github.com/prometheus/procfs/crypto.go
vendor/github.com/prometheus/procfs/loadavg.go
vendor/github.com/prometheus/procfs/net_conntrackstat.go
vendor/github.com/prometheus/procfs/net_softnet.go
vendor/github.com/prometheus/procfs/net_udp.go
vendor/github.com/prometheus/procfs/net_unix.go
vendor/github.com/prometheus/procfs/proc_status.go
vendor/github.com/prometheus/procfs/swaps.go
vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
vendor/k8s.io/cloud-provider/cloud.go
vendor/k8s.io/legacy-cloud-providers/azure/auth/azure_auth.go
vendor/k8s.io/legacy-cloud-providers/azure/azure.go
vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_common.go
vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_standard.go
vendor/k8s.io/legacy-cloud-providers/azure/azure_controller_vmss.go
vendor/k8s.io/legacy-cloud-providers/azure/azure_fakes.go
vendor/k8s.io/legacy-cloud-providers/azure/azure_vmsets.go
vendor/k8s.io/legacy-cloud-providers/azure/retry/azure_error.go
vendor/k8s.io/legacy-cloud-providers/azure/retry/azure_retry.go

/kind feature
chore: upgrade to latest azure cloud provider
Fixes #286
```
```
/hold
This PR should fail now.

chore: upgrade to latest azure cloud provider

---

test/e2e/manifest/in-tree-migration.json
test/e2e/manifest/migration.json

/kind test
This PR add in-tree-migration.json for migration from in-tree driver to CSI driver. Later, we also need to add following config, while following config depends on https://github.com/kubernetes/kubernetes/pull/88014 which is merged in `v1.18.0-beta.0`, `v1.17.4`, so I would make following config change when we switched to use `v1.18.0`. In current stage, let's use this config.
```
"kubernetesConfig": {
"kubeletConfig": {
"--feature-gates": "CSIMigration=true,CSIMigrationAzureDisk=true"
}
```
Fixes #
/assign @chewong 
```
none
```

test: add in-tree-migration.json

---

Gopkg.lock
vendor/golang.org/x/crypto/chacha20/chacha_arm64.go
vendor/golang.org/x/crypto/chacha20/chacha_arm64.s
vendor/golang.org/x/crypto/chacha20/chacha_generic.go
vendor/golang.org/x/crypto/chacha20/chacha_noasm.go
vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.go
vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.s
vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
vendor/golang.org/x/crypto/chacha20/chacha_s390x.s
vendor/golang.org/x/crypto/poly1305/mac_noasm.go
vendor/golang.org/x/crypto/poly1305/sum_amd64.go
vendor/golang.org/x/crypto/poly1305/sum_amd64.s
vendor/golang.org/x/crypto/poly1305/sum_noasm.go
vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
vendor/golang.org/x/crypto/poly1305/sum_ppc64le.s
vendor/golang.org/x/crypto/poly1305/sum_s390x.go
vendor/golang.org/x/crypto/poly1305/sum_s390x.s
vendor/golang.org/x/crypto/poly1305/sum_vmsl_s390x.s
vendor/k8s.io/legacy-cloud-providers/azure/azure_fakes.go
vendor/k8s.io/legacy-cloud-providers/azure/azure_utils.go
vendor/k8s.io/legacy-cloud-providers/azure/azure_vmss.go

/kind test
chore: update azure cloud to use fake clients
cc @ZeroMagic
Fixes #
```
none
```

chore: update azure cloud to use fake clients

---

docs/install-csi-driver-v0.6.0.md

use the correct file to install
Fixes #302 
```
```

doc: update v0.6.0 installation

---

pkg/mounter/safe_mounter_windows.go

>
/kind bug
> /kind design
> /kind test
> /kind flake
Normalize paths used in calls to CSI proxy.
Fixes #
```
NONE
```

Normalize paths used in calls to CSI proxy

---

test/e2e/suite_test.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Depends on https://github.com/kubernetes/test-infra/pull/16590.
/hold
Fixes #
```
```

test: install driver during migration job

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-node.yaml
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/azure_common_test.go

/kind bug
fix: use /dev instead of /devhost in volume mapping
Fixes #
```
```

fix: use /dev instead of /devhost in volume mapping

---

docs/driver-parameters.md
pkg/azuredisk/azure_common.go
pkg/azuredisk/azure_common_test.go
test/e2e/suite_test.go
test/utils/azuredisk_log.sh

/kind feature
chore: change default type from Standard to StandardSSD
and also add print controller-manager logs for in-tree e2e tests
Fixes #
```
none
```

chore: change default type from Standard to StandardSSD

---

test/e2e/suite_test.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
https://testgrid.k8s.io/provider-azure-upstream#k8s-e2e-azure-disk-1-15 was trying to uninstall CSI driver but it was testing in-tree volume plugin.
Fixes #
```
```

test: do not run make e2e-teardown when testing in-tree volume plugin

---

pkg/azuredisk/azure_common_darwin.go
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/azure_common_windows.go
pkg/azuredisk/nodeserver.go

>
/kind bug
> /kind design
> /kind test
> /kind flake
Fix cleanupmountpoint to make os specific calls
Fixes #
```
NONE
```

Fix cleanupmountpoint to make os specific calls

---

deploy/csi-azuredisk-node-windows.yaml
docs/install-csi-driver-master.md

>
> /kind bug
> /kind design
> /kind test
/kind feature
> /kind flake
Windows CSI deployment instructions and yaml
Fixes #
```
NONE
```

Windows CSI deployment instructions and yaml

---

deploy/example/windows/README.md
deploy/example/windows/aspnetapp.yaml

Currently, the driver has supported windows. Add the document to guide users.
Ref: #45 
Fixes #
```
```

doc: add windows feature doc

---

Makefile
pkg/azuredisk/controllerserver.go

/kind feature
feat: enable RWX for shared disk
Fixes #
```
feat: disable vol cap check to support share disk
```
/hold
hold for test pass

feat: enable RWX for shared disk

---

README.md
deploy/example/rawblock/README.md
deploy/example/rawblock/nginx-pod-azuredisk.yaml
deploy/example/sharedisk/README.md
deploy/example/sharedisk/deployment.yaml
hack/verify-yamllint.sh

shared disk doc
Fixes #
cc @VybavaRamadoss
```
none
```

doc: shared disk doc

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
charts/v0.6.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/v0.6.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node.yaml
deploy/csi-snapshot-controller.yaml
deploy/example/cloning/nginx-pod-restored-cloning.yaml
deploy/example/nginx-pod-azuredisk.yaml
deploy/example/rawblock/README.md
deploy/example/rawblock/nginx-pod-azuredisk.yaml
deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
deploy/v0.6.0/csi-azuredisk-controller.yaml
deploy/v0.6.0/csi-azuredisk-node.yaml
deploy/v0.6.0/csi-snapshot-controller.yaml
test/e2e/testsuites/testsuites.go

/kind cleanup
Fixes https://github.com/kubernetes/kubernetes/issues/89477
I'm not sure if it's ok to just modify the latest version of the charts template
```
```
/assign @feiskyer

beta.kubernetes.io/arch is already deprecated since v1.14, are targeted for removal in v1.18 or v1.19

---

README.md
deploy/csi-azuredisk-node-windows.yaml
deploy/example/snapshot/README.md
deploy/example/windows/README.md
deploy/install-driver-standalone.sh
deploy/uninstall-driver-standalone.sh
docs/install-csi-driver-master.md
pkg/azurediskplugin/README.md

doc: change windows related doc, script
Fixes #
```
none
```

doc: change windows related doc, script

---

deploy/example/windows/README.md
deploy/install-driver.sh
deploy/uninstall-driver.sh
docs/install-csi-driver-master.md
test/e2e/suite_test.go

/kind test
test: add install/uninstall deployment script test
This PR is mainly for testing scripts:
- deploy/install-driver.sh
- deploy/uninstall-driver.sh
Fixes #
```
none
```

test: add install/uninstall deployment script test

---

Makefile
charts/README.md
charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
charts/latest/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
charts/latest/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
charts/latest/azuredisk-csi-driver/values.yaml
hack/verify-helm-chart.sh
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/utils/check_driver_pods_restart.sh

/kind flake
- add snapshot/windows driver selection in helm chart installation
- add the latest helm chart configuration
- update verify-helm-chart.sh 
Fixes #
```
NONE
```

doc: add snapshot/windows driver selection in helm chart installation

---

Makefile
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node-windows.yaml
test/e2e/pre_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
This PR allows future PRs to build and push Azure Disk CSI Driver Windows containers to ACR using Travis CI. This will be the first step in enabling e2e tests on Windows clusters. The Windows PR jobs should be triggered assuming that the Windows image has been pushed to ACR.
/cc @ZeroMagic 
Ref: https://github.com/ZeroMagic/azuredisk-csi-driver/commit/b3848134fd90bcbdf50284eb0ff5a2c79b81420f …

test: run CSI driver e2e tests on Windows clusters

---

vendor/k8s.io/legacy-cloud-providers/azure/azure.go
vendor/k8s.io/legacy-cloud-providers/azure/azure_config.go

/kind cleanup
expose azure.KubeClient per https://github.com/kubernetes/kubernetes/pull/89645, will update azure cloud provider later since it's not an easy job
Fixes #
```
none
```

chore: expose azure.KubeClient

---

Makefile

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fixed a typo in introduced in #334
Fixes #
```
```

fix: typo in Makefile

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node.yaml

/kind bug
fix: set cpu,memory limit to a higher value to prevent restart when load is high
Fixes #
```
fix: set cpu,memory limit to a higher value
```

fix: set cpu,memory limit to a higher value

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
deploy/example/windows/README.md
docs/install-csi-driver-master.md
docs/install-csi-driver-v0.6.0.md

doc: fix doc error

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-secret.yaml
charts/latest/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
deploy/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node.yaml
deploy/install-driver.sh
deploy/rbac-csi-azuredisk-controller.yaml
deploy/rbac-csi-azuredisk-node.yaml
deploy/uninstall-driver.sh
docs/read-from-secret.md
pkg/azuredisk/azure.go
pkg/azuredisk/azure_test.go
pkg/azuredisk/azuredisk.go
pkg/azurediskplugin/main.go
test/e2e/suite_test.go

/kind feature
/kind flake
- read cloud config from secret 
- update the related deployment
- add the related doc
Fixes #333 
```
read cloud config from secret 
```

feat: read cloud config from secret 

---

Makefile
charts/README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/values.yaml

>
> /kind bug
> /kind design
> /kind test
> /kind flake
We should be able to deploy both Linux and Windows version of csi-azuredisk-node via helm chart to clusters containing both Windows and Linux nodes
Fixes #
```
```

chore: add linux.enabled parameter to helm chart

---

pkg/azuredisk/nodeserver.go

/kind bug
Remove the unnecessary check in NodeGetVolumeStats.
Fixes #
```
```

fix: remove the unnecessary check in NodeGetVolumeStats

---

README.md
charts/v0.7.0/azuredisk-csi-driver/Chart.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/NOTES.txt
charts/v0.7.0/azuredisk-csi-driver/templates/_helpers.tpl
charts/v0.7.0/azuredisk-csi-driver/templates/crd-csi-node-info.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/rbac-csi-azuredisk-secret.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/rbac-csi-snapshot-controller.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-controller.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/serviceaccount-csi-azuredisk-node.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/serviceaccount-csi-snapshot-controller.yaml
charts/v0.7.0/azuredisk-csi-driver/values.yaml
deploy/v0.7.0/crd-csi-node-info.yaml
deploy/v0.7.0/crd-csi-snapshot.yaml
deploy/v0.7.0/csi-azuredisk-controller.yaml
deploy/v0.7.0/csi-azuredisk-driver.yaml
deploy/v0.7.0/csi-azuredisk-node-windows.yaml
deploy/v0.7.0/csi-azuredisk-node.yaml
deploy/v0.7.0/csi-snapshot-controller.yaml
deploy/v0.7.0/rbac-csi-azuredisk-controller.yaml
deploy/v0.7.0/rbac-csi-azuredisk-node.yaml
deploy/v0.7.0/rbac-csi-snapshot-controller.yaml
docs/install-azuredisk-csi-driver.md
docs/install-csi-driver-v0.7.0.md

doc: cut v0.7.0 release
Fixes #
```
git checkout -b cut-v0.7.0
vi README.md
cd deploy/
mkdir v0.7.0
cp *.yaml v0.7.0/
cd v0.7.0/
grep latest ./* -R
sed -i 's/latest/v0.7.0/g' ./csi-azuredisk-node-windows.yaml ./csi-azuredisk-node.yaml
cd ..
cd ../docs/
cp install-csi-driver-master.md install-csi-driver-v0.7.0.md
vi install-csi-driver-v0.7.0.md
vi install-azuredisk-csi-driver.md
cd ../charts/
cp latest/ v0.7.0 -r
cd v0.7.0/
cd azuredisk-csi-driver/
grep latest ./* -R
sed -i 's/latest/v0.7.0/g' ./Chart.yaml ./values.yaml
grep latest ./* -R
git add charts/ deploy/ docs/
```
```
doc: cut v0.7.0 release
```

doc: cut v0.7.0 release

---

deploy/example/snapshot/storageclass-azuredisk-snapshot.yaml
pkg/azuredisk/controllerserver.go

/kind feature
support tags in snapshot
Fixes #358
```
```

feat: support tags in snapshot

---

deploy/install-driver.sh
deploy/rbac-csi-azuredisk-secret.yaml
deploy/uninstall-driver.sh

/kind flake
add secret rbac file in deploy directory.
Fixes #
```
```

chore: add secret rbac file

---

hack/verify-yamllint.sh
test/e2e/driver/azuredisk_driver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_cmd_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_invalid_mount_options.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
add more disk type tests
Fixes #
```
none
```

test: add disk type tests

---

hack/verify-golint.sh

/kind test
test: improve golint check script
Fixes #
```
none
```

test: improve golint check script

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/testsuites.go

/kind test
test: switch to use busybox
Fixes #373
```
none
```

test: switch to use busybox

---

charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-node.yaml
deploy/rbac-csi-azuredisk-controller.yaml
deploy/rbac-csi-azuredisk-node.yaml

/kind test
/kind flake
separate secret rbac
Fixes #
```
```

chore: separate secret RBAC

---

.golangci.yml
hack/verify-golint.sh
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/nodeserver.go
test/utils/azure/azure_helpers.go
test/utils/credentials/credentials.go

/kind cleanup
Fixes #372
```
NONE
```

Fix golangci-lint findings

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-controller.yaml
pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go

/kind bug
fix: disable IMDS in controller to support MSI
Fixes #
```
fix: disable IMDS in controller to support MSI
```

fix: disable IMDS in controller to support MSI

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: enable topology for azure disk in-tree e2e tests
Fixes #
```
none
```

test: enable topology for azure disk in-tree e2e tests

---

Makefile
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml

/kind feature
chore: lower the cpu/memory limits
Fixes #
```
none
```

chore: lower the cpu/memory limits

---

test/e2e/manifest/in-tree-vmss.json
test/e2e/manifest/in-tree.json
test/e2e/manifest/migration.json

/kind test
test: remove "storageProfile" field in test config
Fixes #
```
none
```

test: remove "storageProfile" field in test config

---

hack/verify-helm-chart.sh

/kind test
Fixes #387 
```
```

test: add snapshot controller image version check

---

Makefile
pkg/azurediskplugin/Dockerfile
pkg/azurediskplugin/Windows.Dockerfile

>
> /kind bug
> /kind design
> /kind test
/kind feature
> /kind flake
- Updates dockerfile with a builder image to build `azurediskplugin` (for building inside the container)
- Updates base image with `us.gcr.io/k8s-artifacts-prod/build-image/debian-base-amd64:v2.1.0` as minimal base (https://github.com/kubernetes/kubernetes/tree/master/build/debian-base)
- Uses `docker buildx` to build cross-platform images
Fixes #
```
feat: replace …
```

feat: update base image with debian-base

---

pkg/azuredisk/azure.go

/kind bug
fix: empty azure cred file issue
Fixes #
```
fix: empty azure cred file issue
```

fix: empty azure cred file issue

---

pkg/azuredisk/controllerserver.go

/kind bug
fix: support snapshot on disk in external resource group
Fixes #408
```
fix: support snapshot on disk in external resource group
```

fix: support snapshot on disk from external resource group

---

pkg/azuredisk/controllerserver.go

/kind feature
feat: enable incremental snapshot feature
This PR added a new parameter(`incremental`, `true` by default) in `VolumeSnapshotClass`
```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
name: csi-azuredisk-vsc
driver: disk.csi.azure.com
deletionPolicy: Delete
parameters:
incremental: "true"  # available values: "true"(by default), "false"
```
Fixes #199
```
feat: enable incremental snapshot feature
```

feat: enable incremental snapshot feature

---

deploy/example/storageclass-azuredisk-csi-allowed-topologies.yaml
deploy/example/topology/README.md
pkg/azuredisk/controllerserver.go

doc: fix topology doc
Fixes #
```
none
```

doc: fix topology doc

---

pkg/azuredisk/nodeserver_test.go
pkg/csi-common/controllerserver-default.go
pkg/csi-common/controllerserver-default_test.go
pkg/csi-common/driver_test.go
pkg/csi-common/identityserver-default_test.go
pkg/csi-common/utils_test.go

/kind test
Unit tests
Work towards #382 
```
```

Add Unit tests

---

test/e2e/suite_test.go

/kind test
test: change Unicode encoding to String
fix flacky windows e2e test
Fixes #
```
none
```

test: change Unicode encoding to String

---

deploy/csi-azuredisk-node-windows.yaml
deploy/example/windows/README.md
deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
test/e2e/testsuites/testsuites.go

fix windows docs
Fixes #
```
none
```

fix windows docs

---

pkg/azuredisk/controllerserver.go

Add resource group parameter to volumesnapshot
More info in #417 
Fixes #417 
```
```

Add resource group parameter to volumesnapshot

---

pkg/azuredisk/controllerserver_test.go

>
/kind test
Fixes #382 
I'll add more unit tests after I learn more about gomock and StorageAccountClient .
```
```

Add Unit tests in pkg/azuredisk/controllerserver_test.

---

.github/PULL_REQUEST_TEMPLATE.md
deploy/example/cloning/pvc-azuredisk-cloning.yaml
deploy/example/deployment.yaml
deploy/example/pvc-azuredisk-csi.yaml
deploy/example/rawblock/README.md
deploy/example/rawblock/pvc-azuredisk-csi.yaml
deploy/example/resize/README.md
deploy/example/sharedisk/README.md
deploy/example/sharedisk/deployment.yaml
deploy/example/snapshot/pvc-azuredisk-snapshot-restored.yaml
deploy/example/storageclass-azuredisk-csi-allowed-topologies.yaml
deploy/example/storageclass-azuredisk-csi-topology.yaml
deploy/example/storageclass-azuredisk-csi.yaml
deploy/example/topology/README.md
deploy/example/windows/deployment.yaml

doc: rename storage class to managed-csi
Fixes #
```
none
```

doc: rename storage class to managed-csi

---

docs/driver-parameters.md

doc: fix partition doc
Fixes #
```
none
```

doc: fix partition doc

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_pod_with_multiple_pv.go
test/e2e/testsuites/specs.go

/kind test
test: add multiple PVs e2e tests
Fixes #
```
none
```

test: add multiple PVs e2e tests

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: fix failure in running multiple volume e2e test
Fixes #
```
none
```

test: fix failure in running multiple volume e2e test

---

.travis.yml
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go

/kind test
Fixes #
```
none
```

Test: add nodeserver unit test

---

deploy/install-driver.sh

/kind bug
fix: driver installation issue
Fixes #
```
none
```

fix: driver installation issue

---

go.mod
go.sum
pkg/azuredisk/azure.go
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/azure_common_windows.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/identityserver.go
pkg/azuredisk/nodeserver.go
pkg/azurediskplugin/main.go
pkg/csi-common/controllerserver-default.go
pkg/csi-common/driver.go
pkg/csi-common/identityserver-default.go
pkg/csi-common/nodeserver-default.go
pkg/csi-common/server.go
pkg/csi-common/utils.go
pkg/csi-common/utils_test.go
pkg/mounter/safe_mounter_windows.go
vendor/github.com/go-logr/logr/README.md
vendor/github.com/go-logr/logr/go.mod
vendor/github.com/go-logr/logr/logr.go
vendor/k8s.io/klog/v2/go.mod
vendor/k8s.io/klog/v2/go.sum
vendor/k8s.io/klog/v2/klog.go
vendor/modules.txt

/kind bug
fix: logging missing due to klog/v2 change
Now the azure cloud provider lib logs are missing
Fixes #
```
none
```

fix: logging missing due to klog/v2 change

---

go.mod
go.sum
pkg/azuredisk/controllerserver.go
vendor/github.com/container-storage-interface/spec/lib/go/csi/csi.pb.go
vendor/modules.txt

/kind feature
chore: upgrade to csi v1.3.0
Fixes #
```
chore: upgrade to csi v1.3.0
```

chore: upgrade to csi v1.3.0

---

hack/release-image.sh
pkg/azuredisk/controllerserver_test.go

/kind test
chore: add hack/release-image.sh
Fixes #
```
none
```

chore: add hack/release-image.sh

---

.travis.yml
Makefile
deploy/uninstall-driver.sh
pkg/azurediskplugin/dev.Dockerfile

/kind test
test: add dev.Dockerfile
Fixes #
```
none
```

test: add dev.Dockerfile

---

.travis.yml
pkg/azuredisk/fake_azuredisk_test.go
pkg/azuredisk/fake_mounter.go
pkg/azuredisk/fake_mounter_test.go
pkg/azuredisk/nodeserver_test.go

/kind test
Fixes #
```
none
```

test: Remove root privileges to run unit test

---

pkg/azuredisk/nodeserver.go

/kind bug
fix: initial delay(1s) when mount azure disk
This PR uses `wait.PollImmediate` instead of `wait.Poll` function to fix initial delay(1s) when mount azure disk
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/a3fd2161f1302ff2fb363f66a22e2dfeb976d6e6/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go#L397-L429
Fixes #
```
fix: initial delay(1s) when mount azure disk
```

fix: initial delay(1s) when mount azure disk

---

hack/verify-gomod.sh
pkg/azuredisk/azure_common_test.go

/kind test
Fixes #
```
none
```

test: add unit-test and hack-verify-gomod

---

pkg/azuredisk/controllerserver_test.go

/kind test
Fixes #
```
none
```

test: add unit-test

---

hack/release-image.sh
test/e2e/driver/driver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go

/kind test
test: add resize disk e2e test
Fixes #453 
```
none
```

test: add resize disk e2e test

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
test/utils/azure/azure_helpers.go

/kind test
Fixes #433 
```
none
```

test: add e2e-test-azuredisk-tag.

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go

/kind test
Fixes #
```
none
```

test: add new judgment in resize e2e-test.

---

pkg/azuredisk/nodeserver_test.go

/kind test
Fixes #
```
none
```

test: add unit-test in azuredisk/nodeserver_test.go

---

pkg/azuredisk/controllerserver_test.go

/kind test
Fixes #
```
none
```

test: add unit-test in pkg/azuredisk/controllerserver_test.go

---

go.mod
pkg/azuredisk/controllerserver_test.go
vendor/k8s.io/legacy-cloud-providers/azure/clients/snapshotclient/mocksnapshotclient/doc.go
vendor/k8s.io/legacy-cloud-providers/azure/clients/snapshotclient/mocksnapshotclient/interface.go
vendor/modules.txt

/kind test
Fixes #
```
none
```

test: add snapshot-unit-test in azuredisk/controllerserver_test

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: skip one flaky windows test
Fixes #
```
none
```

test: skip one flaky windows test

---

deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node.yaml

/kind cleanup
chore: set default imagePullPolicy
Actually default value of `imagePullPolicy` is `IfNotPresent`, this PR does not change anything, only make user easier to change that value to `Always` if user wants update latest version
Fixes #
```console
wget https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/deploy/csi-azuredisk-controller.yaml
sed -i 's/IfNotPresent/Always/g' csi-azuredisk-controller.yaml
kubectl apply -f csi-azuredisk-controller.yaml
```
```
none
```

chore: set default imagePullPolicy

---

pkg/azuredisk/controllerserver_test.go
pkg/csi-common/controllerserver-default_test.go
pkg/csi-common/fake_driver_test.go

/kind test
Fixes #
```
none
```

test: add unit-test for unimplemented method

---

pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/nodeserver_test.go

/kind test
Fixes #
```
none
```

test: add unit-test for azuredisk nodeserver and createvolume.

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver_test.go
pkg/azurediskplugin/main.go
pkg/csi-common/server.go
pkg/csi-common/server_test.go
pkg/csi-common/utils.go
test/e2e/suite_test.go

/kind test
Fixes #
```
none
```

test: add unit-test in controllerserver and serve

---

pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/nodeserver_test.go
pkg/util/util_test.go

/kind test
Fixes #
```
none
```

test: add unit-test in controllerserver and nodeserver

---

Makefile
test/e2e/suite_test.go

>
> /kind bug
/kind cleanup
> /kind design
> /kind test
> /kind flake
Currently working on incorporating e2e tests in an internal pipeline and it'd be nice to have an option to run e2e tests on a cluster that already has azuredisk-csi-driver install.
/assign @andyzhangx  
Fixes #
```
none
```

ci: add options to skip installing / uninstalling azuredisk-csi-driver during e2e test

---

Makefile
test/e2e/suite_test.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
- Revert #476
- Add E2E_HELM_OPTIONS to Makefile, which can be overridden by users.
Fixes #
```
none
```

ci: add E2E_HELM_OPTIONS to Makefile

---

deploy/example/deployment.yaml
deploy/example/sharedisk/deployment.yaml
deploy/example/statefulset.yaml
deploy/example/windows/deployment.yaml
test/e2e/suite_test.go
test/utils/azuredisk_log.sh
test/utils/controller-manager-log.sh

/kind test
test: add more logs in e2e tests
Fixes #
```
none
```

test: add more logs in e2e tests

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go

/kind test
Fixes #221 
```
none
```

test: add disk detach e2e-test

---

test/utils/azuredisk_log.sh
test/utils/controller-manager-log.sh

>
> /kind bug
> /kind design
> /kind test
> /kind flake
kubectl logs --prefix is only available for kubectl v1.17+. This PR ensures no error will occur when using an older version of kubectl.
/assign @andyzhangx
Fixes #
```
none
```

ci: remove --prefix when using kubectl to ensure backward compatibility

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go

/kind test
Addressing[https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/485](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/485)
Fixes #
```
none
```

test: add disk detach e2e-test in in-tree situation.

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go

/kind cleanup
- `extractSnapshotInfo` func is not in good coding style. Remove the condition that checking whether the id contains `/subscriptions/`.
- Delete the unnecessary unit test case.
Fixes #409
```
none
```

chore: refactor the snapshot code

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
Fixes #238 
```
none
```

test: add disk statefulset e2e-test

---

docs/node-shutdown-recovery/README.md
docs/node-shutdown-recovery/statefulset-azuredisk.yaml
hack/verify-yamllint.sh

doc: add node-shutdown-recovery-doc

---

Makefile
pkg/azurediskplugin/Dockerfile
pkg/azurediskplugin/Windows.Dockerfile

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fixes #
```
none
```

build: build binary outside of builder container to allow binary signing

---

pkg/azuredisk/controllerserver.go

/kind feature
feat: add dangling error support
When one disk volume is already attached to another node, and got `DanglingAttachError`, detach that disk directly and then attach disk again.
This PR uses Azure API to detach disk directly(not through k8s volume controller), it's actually  not a graceful way to solve the dangling error issue on CSI driver(mentioned [here](https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/288)) , while it's still a good workaround. 
I Will put some efforts to solve the dangling error issue on CSI driver **gracefully** later.
Fixes #436
Fixes #288
Below are the steps how to validate dangling …

feat: add dangling error support

---

charts/README.md
charts/latest/azuredisk-csi-driver/templates/_helpers.tpl
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml

/kind feature
Addressing [372](https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/372)
Fixes #
```
none
```

fix: Add imagePullSecrets in Helm chart for secret used to pull Docker images

---

deploy/example/windows/statefulset.yaml
test/e2e/manifest/multi-az.json
test/utils/azuredisk_log.sh

test: add containerd e2e test config
/kind cleanup
Fixes #
```
none
```

test: add containerd e2e test config

---

pkg/csi-common/driver_test.go

/kind test
Fixes #
```
none
```

test: add unit-test in csi-common.

---

.github/PULL_REQUEST_TEMPLATE.md
charts/README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/example/windows/README.md
deploy/install-driver.sh

/kind feature
feat: enable windows feature installation by default
Fixes #
```
feat: enable windows feature installation by default
```

feat: enable windows feature installation by default

---

test/e2e/pre_provisioning_test.go

/kind test
test: add shared disk e2e test
Fixes #
```
none
```

test: add shared disk e2e test

---

deploy/example/e2e_usage.md
deploy/example/metrics/README.md
deploy/example/metrics/csi-azuredisk-controller-svc.yaml
test/e2e/pre_provisioning_test.go

doc: fix metrics doc
Fixes #505
```
none
```

doc: fix metrics doc

---

Makefile
charts/README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node-windows.yaml
test/e2e/suite_test.go
test/utils/azuredisk_log.sh

/kind test
test: add metrics logs in e2e test
Fixes #
```
none
```

test: add metrics logs in e2e test

---

deploy/example/metrics/README.md
test/utils/azuredisk_log.sh

/kind test
test: make metrics test mandatory
Fixes #
```
none
```

test: make metrics test mandatory

---

README.md
deploy/example/volumelimits/README.md

add volume limits doc
Fixes #402
cc @ezYakaEagle442
```
none
```

doc: add volume limits doc

---

pkg/azurediskplugin/Dockerfile

/kind cleanup
Update debian base image to v2.1.3 to address CVEs.
```
none
```

Update debian base image to v2.1.3

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-controller.yaml

/kind cleanup
chore: set provisioner timeout as 15s, 15s is the default value of csi-provisioner.
- Before v0.8.0, disk creation time is 10s; 
- Since v0.8.0, disk creation time is around 2s after fix(https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/473) in v0.8.0
So 15s is quite a safe timeout value now.
Fixes #366
```
chore: set provisioner timeout as 15s
```

chore: set provisioner timeout as 15s

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go

/kind bug
fix: create snapshot on external resource group failure
Fixes #530
```
fix: create snapshot on external resource group failure
```

fix: create snapshot on external resource group failure

---

README.md
charts/README.md
deploy/example/snapshot/README.md

chore: change image repo address
Fixes #
```
chore: change image repo address
```
cc @chewong
/hold

chore: change image repo address

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

/kind test
test: migration test on Windows
Fixes #
```
none
```

test: migration test on Windows

---

Makefile
test/e2e/suite_test.go

/kind test
test: add example test
Fixes #
```
none
```

test: add example test

---

deploy/example/cloning/nginx-pod-restored-cloning.yaml
deploy/example/deployment.yaml
deploy/example/nginx-pod-azuredisk.yaml
deploy/example/rawblock/README.md
deploy/example/rawblock/nginx-pod-azuredisk.yaml
deploy/example/sharedisk/README.md
deploy/example/sharedisk/deployment.yaml
deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
docs/known-issues/node-shutdown-recovery/statefulset-azuredisk.yaml

/kind test
test: switch to use mcr nginx image
Fixes #
```
nginx                                                             latest               7e4d58f0e5f3        12 days ago         133MB
mcr.microsoft.com/oss/nginx/nginx                                 1.17.3-alpine        d87c83ec7a66        13 months ago       21.2MB
```
```
test: switch to use mcr nginx image
```

test: switch to use mcr nginx image

---

test/e2e/manifest/migration-windows.json
test/utils/azuredisk_log.sh

/kind test
test: increase windows test vm size
Fixes #
```
none
```

test: increase windows test vm size

---

.github/workflows/static.yaml

Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>
/kind test
Add `golangci-linter` to github actions
Fixes #
```
none
```

CI: Add `golangci-linter` to github actions

---

Makefile
deploy/example/deployment.yaml
deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
test/utils/check_driver_pods_restart.sh

/kind cleanup
chore: field name refactor
Fixes #
```
none
```

chore: field name refactor

---

test/e2e/suite_test.go
test/utils/check_driver_pods_restart.sh

/kind test
test: print restart pod logs once
Fixes #
```
none
```

test: print restart pod logs once

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml
pkg/azurediskplugin/Dockerfile
pkg/azurediskplugin/dev.Dockerfile

/kind bug
fix: create nonroot user in Dockerfile
Fixes #
```
fix: create nonroot user in Dockerfile
```

fix: create nonroot user in Dockerfile

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: add xfs test
Fixes #
```
none
```

test: add xfs test

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-node.yaml

/kind bug
"ClusterFirstWithHostNet": For Pods running with hostNetwork, you should explicitly set its DNS policy "ClusterFirstWithHostNet".
https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#pod-s-dns-policy
Fixes #
```
fix: use dnsPolicy ClusterFirstWithHostNet for hostNetwork
```

fix: use dnsPolicy ClusterFirstWithHostNet for hostNetwork

---

deploy/example/statefulset.yaml
test/e2e/dynamic_provisioning_test.go

/kind test
test: enable one windows e2e test for in-tree driver
Fixes #
```
none
```

test: enable one windows e2e test for in-tree driver

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: enable one windows test for CSI driver
Fixes #
```
none
```

test: enable one windows test for CSI driver

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
test: fix windows deployment e2e test failure
Fixes #
```
none
```

test: fix windows deployment e2e test failure

---

test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
test/e2e/testsuites/specs.go

test: add e2e test for create snapshot on external resource group

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node.yaml

/kind bug
fix: not schedule driver pod on virtual node
Fixes #
```
fix: not schedule driver pod on virtual node
```

fix: not schedule driver pod on virtual node

---

test/e2e/manifest/migration-windows.json
test/e2e/manifest/migration.json

/kind test
test: set CSIMigrationAzureDiskComplete as true
pkg/controller/volume/attachdetach/util/util.go:
```
if csiMigratedPluginManager.IsMigrationCompleteForPlugin(pluginName) {
// All nodes are expected to have migrated CSI plugin installed and
// configured when CSI Migration Complete flag is enabled for a plugin.
// CSI migration is supported even if there is version skew between
// managers and node.
return true, nil
}
```
Fixes #
```
test: set CSIMigrationAzureDiskComplete as true
```

test: set CSIMigrationAzureDiskComplete as true

---

test/sanity/README.md
test/utils/credentials/credentials.go

/kind cleanup
Fixes https://github.com/kubernetes-sigs/azurefile-csi-driver/issues/459
/hold
I need to go through all the repos that rely on these values.
```
Add AZURE prefix to e2e environment variables
```

Add AZURE prefix to e2e environment variables

---

Makefile
docs/csi-dev.md
hack/release-image.sh
pkg/azurediskplugin/Windows.Dockerfile

image: support multi OS versions for Windows images

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml

/kind bug
Replace livenessprobe flag --connection-timeout with --probe-timeout.
Update the livenessprobe version from v1.1.0 to v2.0.0.
Update helm charts.
Fixes #
```
none
```

fix: update livenessprobe version from v1.1.0 to v2.0.0

---

pkg/mounter/safe_mounter_windows.go

/kind bug
fix: panic on Windows
driver crash issue on Windows, details: https://github.com/kubernetes-csi/csi-driver-smb/issues/150
Fixes #
```
fix: panic on Windows
```

fix: panic on Windows

---

charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-node.yaml
deploy/example/topology/README.md

/kind feature
chore: ugprade csi-node-driver-registrar to v2.0.1
Fixes #
```
chore: ugprade csi-node-driver-registrar to v2.0.1
```

chore: ugprade csi-node-driver-registrar to v2.0.1

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go

/kind bug
fix: set minimum disk size as 1GiB
Fixes #592
```
fix: set minimum disk size as 1GiB
```
/assign @Jiawei0227

fix: set minimum disk size as 1GiB

---

Makefile

/kind feature
chore: build from vendor
Fixes #
```
chore: build from vendor
```

chore: build from vendor

---

charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-node-windows.yaml

/kind feature
chore: upgrade node-driver-registrar version to v2.0.1 on windows
Fixes #
```
chore: upgrade node-driver-registrar version to v2.0.1 on windows
```

chore: upgrade node-driver-registrar version to v2.0.1 on windows

---

pkg/azurediskplugin/Windows.Dockerfile

Copy netapi32.dll from windows-servercore-cache (https://github.com/kubernetes/kubernetes/tree/master/test/images/windows-servercore-cache) instead of servercore, which would speed up the image building process by a lot. 
Fixes #
```
none
```

fix: copy netapi32.dll from windows-servercore-cache instead of servercore

---

Makefile
charts/README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml

/kind feature
chore: support run controller on master node
add `controller.runOnMasterNode` in helm install to support run controller on master node
Fixes #598
```
feat: support run controller on master node
```

feat: support run controller on master node

---

Makefile
charts/README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/values.yaml

chore: rename runOnMasterNode to runOnMaster
Fixes #
```
none
```

chore: rename runOnMasterNode to runOnMaster

---

hack/verify-yamllint.sh
pkg/azuredisk/azure.go
pkg/azuredisk/controllerserver.go
test/e2e/driver/azuredisk_driver.go
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go

/kind bug
/kind test
Add function `IsAzureStackCloud` to decide if the driver is running on Azure Stack Cloud.
If it is on Azure Stack Cloud, then the shared disk is not supported, only Standard_LRS and Premium_LRS are supported, the incremental snapshot is not supported. Corresponding documentation will be in the next PR.
Apply the same logic on the e2e tests.
Fixes #
```
none
```

fix: add Azure Stack specific logic

---

pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go

/kind bug
This PR tries to skip node expansion when volume type is block. However, this does not guarantee to work well because volumeCapability is not yet being passed from kubelet until v1.19.
https://github.com/kubernetes/kubernetes/commit/7d6959ce2ce49fa5b37b3aa28d20fdeb01c02223
The root cause for this is the way it get devicePath. I am not familiar with this domain so I dont know how to get the devicepath given volumepath when we cant use the mount information.
[Update] I am using  `isBlock, err := hostutil.NewHostUtil().PathIsDevice(volumePath)` to check if this is a block device and it seems to work.
Testing:
Running e2e testsuite offline volume expansion and it worked for block volume.
**Which issue(s) this PR …

fix: skip raw block node volume expansion

---

Makefile

/kind bug
fix: windows image build error
This is a workaround fix, wait for buildkit fix on v0.8.0: https://github.com/moby/buildkit/pull/1879
Fixes #
```
fix: windows image build error
```

fix: windows image build error

---

Makefile

/kind test
test: optimize buildkit setting
Fixes #
```
none
```

test: optimize buildkit setting

---

pkg/csi-common/utils.go

/kind cleanup
chore: remove useless code
Fixes #
```
none
```

chore: remove useless code

---

test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh

/kind test
test: use original way for setting up sanity tests
Fixes #
```
none
```

test: use original way for setting up sanity tests

---

go.mod
vendor/modules.txt

/kind test
chore: use go 1.15
Fixes #
```
none
```

chore: use go 1.15

---

Makefile

/kind bug
Fixes #630 
```
none
```

fix:   Fix default Docker Hub prefix generation.

---

Makefile
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node-windows.yaml
test/e2e/testsuites/testsuites.go
test/integration/run-tests-all-clouds.sh

/kind bug
Add AZURE_ENVIRONMENT_FILEPATH variable for windows on Azure Stack.
If the test runs for Azure Stack, we spin up a buildx builder container with certs path mounted.
By default, in tests, we run pods/deployments/statefulsets on Linux nodes.
Add GO111MODULE=off for csc install.
Fixes #
```
none
```

fix: windows support for Azure Stack

---

pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go

/kind bug
Fixes #639 
```
none
```

fix: Set right errorCode for NodeExpandVolume failure

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go

/kind bug
ListSnapshot implementation currently returns all the snapshots in an rg even when a specific volumeId is given. This fix will only return snapshots related to a particular volume when the volumeId is given.
Fixes #641 
```
none
```

fix: List only snapshots that match the volumeId

---

pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go

/kind bug
fix: make node stage and publish idempotent
fixed following sanity test failure:
```
[91m[1m[Fail] [0m[90mNode Service [0m[91m[1m[It] should be idempotent [0m
[37m/home/prow/go/src/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go:140[0m
```
Fixes #
```
fix: make node stage and publish idempotent
```

fix: make node stage and publish idempotent

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go

/kind feature
feat: add pv name tag on disk
Fixes #579
```
I1229 02:57:27.275307       1 controllerserver.go:315] create azure disk(pvc-a3539b9b-b81b-411d-85d7-9465b8164d53) account type(StandardSSD_LRS) rg(kubetest-9d42deeb-497c-11eb-9b3d-fa6cb9fbae8e) location() size(10) tags(map[kubernetes.io-created-for-pv-name:pvc-a3539b9b-b81b-411d-85d7-9465b8164d53]) successfully
```
```
feat: add pv name tag on disk creation
```

feat: add pv name tag on disk creation

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: add UltraSSD e2e test
Fixes #
```
none
```

test: add UltraSSD e2e test

---

pkg/mounter/safe_mounter_windows.go
test/e2e/dynamic_provisioning_test.go

/kind bug
fix: cache data loss issue on Windows when unmount disk
Fixes #
```
fix: cache data loss issue on Windows when unmount disk
```

fix: cache data loss issue on Windows when unmount disk

---

.github/workflows/darwin.yaml
.github/workflows/linux.yml
.github/workflows/windows.yml

/kind test
test: enable GH actions on all branches
Fixes #
```
none
```

test: enable GH actions on all branches

---

charts/README.md

doc: update charts doc
Fixes #
```
none
```

doc: update charts doc

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml

/kind bug
fix: ssl cert issue on non-debian agent node
This issue is introduced by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/600, which is only for Azure stack, remove following mount should work:
```yaml
name: ssl
mountPath: /etc/ssl/certs
readOnly: true
```
Fixes #662, #658
cc @songjiaxun 
```
fix: ssl cert issue on non-debian agent node
```

fix: ssl cert issue on non-debian agent node

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/rbac-csi-azuredisk-controller.yaml

/kind feature
chore: upgrade resizer to v1.1.0
with `handle-volume-inuse-error=true`, it could prevent detach disk which is already in use
Fixes #
```
chore: upgrade resizer to v1.1.0
```

chore: upgrade resizer to v1.1.0

---

charts/README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/values.yaml

/kind feature
add kubeletPath support in Helm chart
**Which issue(s) this PR fixes**: 
Fixes #610 
None
```
feat: add kubeletPath support in Helm chart
```

feat: add kubeletPath support in Helm chart

---

Makefile
README.md
charts/README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node.yaml

/kind bug
Azure Stack needs certs to be mounted on the CSI containers.
Fixes #
```
none
```

fix: mount certs for Azure Stack

---

test/external-e2e/manifest/testdriver.yaml

/kind test
Adding the test driver config yaml file which is required to run the external e2e k8s tests
Fixes #577
```
none
```

test: Test driver config for external e2e k8s tests

---

pkg/azuredisk/controllerserver.go

/kind bug
Fixes #678 
```
none
```

fix: Exclude os disks from the ListVolumes response

---

test/utils/azure/azure_helpers.go

If `nil` is passed to the `managedBy` parameter of `azure.Client.EnsureResourceGroup()` method, use resource group's current value when calling `resources.groupsClient.CreateOrUpdate()`.
/kind bug
This is convenient for those who use AKS to create and manage test clusters.
Fixes #675
```
none
```

test: Use the resource group's managedBy property if none provided

---

charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-snapshot-controller.yaml

/kind feature
feat: upgrade to snapshotter v3.0.3
Fixes #
```
feat: upgrade to snapshotter v3.0.3
```
/hold

feat: upgrade to snapshotter v3.0.3

---

pkg/azuredisk/azure_common.go
pkg/azuredisk/azure_common_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go

/kind cleanup
cleanup: remove unmanaged disk support
Fixes #440
/hold
```
cleanup: remove unmanaged disk support
```

cleanup: remove unmanaged disk support

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
test/e2e/testsuites/testsuites.go

/kind test
Adds a e2e test case to check if snapshot restore functionality behaves correctly.
Fixes #434 
```
none
```

test: Add e2e test for snapshot restore

---

pkg/azuredisk/nodeserver_test.go

/kind test
Fixes #625 
```
none
```

test: Improve unit test coverage of nodeserver.go

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/nodeserver.go
pkg/util/util.go

/kind feature
Fixes #656 
```
none
```

feat: Handle concurrency for node stage/unstage publish/unpublish

---

Makefile

/kind bug
Fix CLOUD environment variable in Makefile.
Fixes #
```
none
```

fix: passing CLOUD correctly in Makefile for Azure Stack

---

Makefile
deploy/example/statefulset-nonroot.yaml
deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
hack/verify-examples.sh
test/e2e/suite_test.go

/kind test
test: refactor example verification test
Fixes #
```
none
```

test: refactor example verification test

---

charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node.yaml
deploy/example/sharedisk/README.md
docs/driver-parameters.md
hack/verify-examples.sh

/kind feature
chore: upgrade livenessprobe to v2.2.0
Fixes #
```
none
```

chore: upgrade livenessprobe to v2.2.0

---

pkg/azuredisk/controllerserver.go

/kind feature
feat: add more controller metrics
Fixes #
```
feat: add more controller metrics
```

feat: add more controller metrics

---

README.md
deploy/example/snapshot/storageclass-azuredisk-snapshot.yaml
deploy/example/storageclass-azuredisk-csi-azurestack.yaml
docs/limitations.md
hack/verify-examples.sh
pkg/azuredisk/azure.go
pkg/azuredisk/azure_common.go
pkg/azuredisk/azure_common_test.go
pkg/azuredisk/controllerserver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/specs.go

/kind bug
Throw error when unsupported resources are requested on Azure Stack.
Change the test logic accordingly.
Add limitations for Azure Stack.
Fixes #
```
none
```

fix: throw error when unsupported resources are requested on Azure Stack

---

deploy/example/windows/README.md
pkg/azuredisk/controllerserver.go

/kind feature
feat: add controller lock
Fixes #
```
feat: add controller lock
```

feat: add controller lock

---

charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
pkg/azuredisk/controllerserver.go
pkg/azuredisk/identityserver.go
pkg/azuredisk/nodeserver.go

/kind feature
feat: upgrade csi-provisioner to v1.6.1
Fixes #
```
feat: upgrade csi-provisioner to v1.6.1
```

feat: upgrade csi-provisioner to v1.6.1

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node-windows.yaml

/kind bug
DaemonSet in Windows node is not allowed to perform privileged actions so privileged field in security context shouldn't be true
Fixes #
```
feat: remove securityContext on Windows deployment
```

feat: remove securityContext on Windows deployment

---

docs/known-issues/sizegrow.md
hack/verify-helm-chart.sh

/kind test
test: add chart tgz file verification
Fixes #
```
none
```

test: add chart tgz file verification

---

hack/verify-helm-chart.sh

/kind test
test: add chart tgz files verification
Fixes #
```
none
```

test: add chart tgz files verification

---

test/integration/run-test.sh

/kind test
Along with the recent gocsi expand volume panic fix PR, this PR adds expand volume test to the azure-csi-driver integration test suite.
Fixes #469
```
none
```

test: add expand volume test to integration test

---

pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go

/kind bug
fix: volume expansion failure on node
fixed bug introduced by https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/607
Fixes #714
```
fix: volume expansion failure on node
```

fix: volume expansion failure on node

---

charts/index.yaml
hack/verify-all.sh
hack/verify-helm-chart-files.sh
hack/verify-helm-chart.sh

/kind test
test: add verify-helm-chart-files.sh script
Fixes #
```console
helm repo index charts --url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts
```
```
none
```

test: add verify-helm-chart-files.sh script

---

pkg/azuredisk/nodeserver_test.go

/kind test
Adds a unit test for getDevicePathWithMountPath
Fixes #688
```
none
```

test: write unit test for getDevicePathWithMountPath function

---

charts/index.yaml

/kind bug
fix: broken chart index
Fixes #
```console
helm repo index charts --url=https://raw.githubusercontent.com/kubernetes-sigs/azuredisk-csi-driver/master/charts
```
```
fix: broken chart index
```

fix: broken chart index

---

pkg/azuredisk/nodeserver_test.go

test: fix windows ut failure
Fixes #
```
none
```

test: fix windows ut failure

---

test/utils/azure/azure_helpers.go

/kind bug
Fixes #743 
```
none
```

fix: dynamically generate key pair for vm creation in tests

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
test/e2e/testsuites/testsuites.go

Updates to resize e2e test

---

pkg/azuredisk/azure_common_unix.go
pkg/azuredisk/azure_common_windows.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/mounter/safe_mounter_windows.go
test/e2e/dynamic_provisioning_test.go

/kind feature
Adds support for NodeExpandVolume on Windows to enable resizing of the file system when a persistent volume is expanded. This change also enables the volume resizing tests on Windows.
Fixes #687
```
none
```

feat: Add support for NodeExpandVolume on Windows

---

.github/workflows/static.yaml

/kind test
test: add more golint checks
Fixes #
```
none
```

test: add more golint checks

---

Makefile
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/azuredisk_v1.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/fake_azuredisk_v1.go
pkg/azuredisk/fake_azuredisk_v2.go
pkg/azuredisk/fake_mounter_test.go
pkg/azuredisk/identityserver_test.go
pkg/azuredisk/identityserver_v2.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_reclaim_policy_tester.go
test/e2e/testsuites/pre_provisioned_dangling_attach_volume_tester.go
test/e2e/testsuites/testsuites.go
test/integration/integration_test.go
test/integration/run-test.sh
test/integration/run-tests-all-clouds.sh
test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh
test/sanity/sanity_test.go

/kind cleanup
This PR adds a side-by-side implementation of the v2 driver that is conditionally compiled (through the "azurediskv2" tag) in order to ease integration with ongoing v1 work with v2 work.
Fixes #
@andyzhangx This is the PR we discussed offline for staging v2 development. The v2 implementation is conditionally compiled through the "azurediskv2" tag. There is also a "--temp-use-driver-v2" command-line switch to enable side-by-side testing in the same binary. In this PR, the v1 and v2 implementations are the same (xxx_v2.go files are copies of their original counterparts). I would appreciate your feedback on this approach …

chore: Add side-by-side implementation of v2 driver to ease integration with ongoing v1 work

---

test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go

/kind bug
On Azure Stack, we consistently observe the e2e test failure from test "should create a volume on demand and resize it".
Add a short period of time to wait for the statefulset update to complete will solve the issue.
Fixes #
```
none
```

fix: add a wait period for statefulset update in e2e tests

---

Makefile

/kind bug
Fix helm install command for windows e2e test.
Fixes #
```
none
```

fix: windows e2e test helm install command

---

test/utils/azuredisk_log.sh
test/utils/controller-manager-log.sh

/kind test
test: print out node labels
Fixes #
```
none
```

test: print out node labels

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go

/kind bug
Fixes #769 
```
none
```

fix: listVolumes should not return error when no volume was found

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/nodeserver.go

/kind feature
fix: disable invalid storage class parameters
Fixes #
```
fix: disable invalid storage class parameters
```

fix: disable invalid storage class parameters

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go

/kind bug
fix: support create snapshot in parallel
should not add lock in source disk url
Fixes #
```
fix: support create snapshot in parallel
```

fix: support create snapshot in parallel

---

test/e2e/dynamic_provisioning_test.go

Fixes test failure in https://testgrid.k8s.io/provider-azure-master-signal#capz-azure-disk.
Explicitly Add `zoned` to storage class parameters based on whether we are testing clusters with AZs or not. We weren't able to attach disks to non-AZ worker nodes created by an AZ-enabled master node.
Fixes #
```
none
```

test: use `WaitForFirstConsumer` for in-tree storage driver

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/nodeserver_test.go

/kind test
Fixes #733 
```
none
```

test: add test cases for volume lock acquisition

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
test/e2e/testsuites/testsuites.go

/kind test
/kind flake
This PR fixes the flaky/failing clone from disk test in the multi-az scenario by ensuring that the pod with the cloned disk is schedule to the same zone as the source pod/disk.
Fixes #685 
```
none
```

test: Schedule pod to same zone as source disk in multi-az clone tests

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_v2.go

/kind feature
feat: support topology.kubernetes.io/zone key
Fixes #
```
feat: support topology.kubernetes.io/zone key
```

feat: support topology.kubernetes.io/zone key

---

test/e2e/pre_provisioning_test.go
test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
test: add inline volume test
Fixes #729
```
none
```

test: add inline volume test

---

test/e2e/pre_provisioning_test.go

/kind test
Fixes #793
```
none
```

test: disable inline volume test for in-tree driver

---

test/e2e/pre_provisioning_test.go

/kind test
test: skip inline test for in-tree Windows
Fixes https://github.com/kubernetes/kubernetes/issues/101196
```
none
```

test: skip inline test for in-tree Windows

---

deploy/example/topology/README.md
docs/driver-parameters.md
pkg/azuredisk/controllerserver.go

feat: support ZRS disk on non-zone nodes, this PR adds an empty topology label when creating ZRS disk volume
```yaml
csi:
driver: disk.csi.azure.com
volumeAttributes:
skuname: StandardSSD_ZRS
storage.kubernetes.io/csiProvisionerIdentity: 1618890129812-8081-disk.csi.azure.com
volumeHandle: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Compute/disks/pvc-7a15f149-be47-4ea4-9692-d7679c752b99
nodeAffinity:
required:
nodeSelectorTerms:
- matchExpressions:
- key: topology.disk.csi.azure.com/zone
operator: In
values:
- eastus2euap-1
- matchExpressions:
- key: topology.disk.csi.azure.com/zone
operator: In
values:
- eastus2euap-2
- matchExpressions:
- key: topology.disk.csi.azure.com/zone
operator: In
values:
- …
```

feat: support ZRS disk on non-zone nodes

---

Makefile
pkg/azurediskplugin/Dockerfile

/kind feature
feat: add ARM64 support
Fixes #580
```yaml
{
"schemaVersion": 2,
"mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
"manifests": [
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 953,
"digest": "sha256:23458f97facc67e6b82e5dd8f67c1580d1de144ed71dddf35cc8c992f744909c",
"platform": {
"architecture": "amd64",
"os": "linux"
}
},
{
"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
"size": 953,
"digest": "sha256:6333fd2c6893a79fcdca5f0b2b90d59f3a774c7516c56a134f061b1e77d212fd",
"platform": {
"architecture": "arm64",
"os": "linux"
}
},
{
"mediaType": …
```

feat: add ARM64 support

---

deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
test/e2e/testsuites/testsuites.go

/kind test
test: switch to use MCR windows images
Fixes #
```
none
```

test: switch to use MCR windows images

---

Makefile

/kind bug
fix: random arm64 build failure
related to https://github.com/moby/buildkit/issues/1929
Fixes #
```
fix: random arm64 build failure
```

fix: random arm64 build failure

---

test/external-e2e/manifest/testdriver.yaml
test/external-e2e/run.sh

/kind test
test: print out driver logs for external e2e tests
Fixes #
```
none
```

test: print out driver logs

---

test/external-e2e/manifest/testdriver.yaml
test/external-e2e/run.sh

/kind test
test: run external e2e test using 1.21 branch
Fixes #
```
none
```

test: run external e2e test using 1.21 branch

---

test/e2e/manifest/in-tree-vmss.json
test/e2e/manifest/in-tree.json
test/e2e/manifest/migration-windows.json
test/e2e/manifest/migration.json
test/e2e/manifest/multi-az.json
test/e2e/manifest/single-az.json

Follow-up PR for https://github.com/kubernetes/kubernetes/pull/101531.
Fixes failure in https://testgrid.k8s.io/provider-azure-master-signal#aks-engine-azure-disk-vmss
Fixes #
```
none
```

fix: remove VolumeSnapshotDataSource feature gate

---

pkg/util/util_test.go

/kind test
Fixes #719 
```
none
```

test: add test cases to increase coverage for util

---

README.md
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go

test: fix containerd Windows e2e test failure

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

/kind test
test: add ZRS e2e test
Fixes #795 
```
none
```

test: add ZRS e2e test

---

hack/verify-examples.sh
test/e2e/suite_test.go

/kind test
test: run test on install_driver.sh script
Fixes #
```
none
```

test: run test on install_driver.sh script

---

pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go

/kind bug
fix: remove unnecessary lock in NodePublish
Fixes #
```
fix: remove unnecessary lock in NodePublish
```

fix: remove unnecessary lock in NodePublish

---

test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go

/kind test
test: wait for detach complete in e2e test
Fixes #829
```
none
```

test: wait for detach complete in e2e test

---

test/external-e2e/run.sh

test: disable one external failing test
related to https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/880
Fixes #
```
none
```

test: disable one external failing test

---

hack/verify-examples.sh
test/external-e2e/run.sh

/kind test
test: add example test in external e2e test
Fixes #
```
none
```

test: add example test in external e2e test

---

pkg/azuredisk/azure.go

/kind bug
fix: read cloud config from secret regression
Fixes #884
```
none
```

fix: read cloud config from secret regression

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_tester.go
test/e2e/testsuites/testsuites.go

/kind test
Tests a pod failover by cordoning a node and then deleting the pod, contains a test for standard storage and ZRS 
Fixes #
```
none
```

test: test pod failover using ZRS

---

deploy/example/daemonset-azuredisk-ephemeral.yaml
deploy/example/nginx-pod-ephemeral.yaml
hack/verify-examples.sh
test/external-e2e/run.sh

/kind test
test: add ephemeral volume test
Fixes #
```
none
```

test: add ephemeral volume test

---

Makefile
pkg/azuredisk/azure.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/device_perf_optimization_helper.go
pkg/azuredisk/device_perf_optimization_helper_test.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/fake_azuredisk_v2.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go
pkg/optimization/azure_skus_map.go
pkg/optimization/device_perf.go
pkg/optimization/device_perf_helper.go
pkg/optimization/device_perf_helper_test.go
pkg/optimization/device_perf_linux.go
pkg/optimization/device_perf_linux_test.go
pkg/optimization/device_perf_test.go
pkg/optimization/device_perf_unsupported.go
pkg/optimization/skus.go
pkg/optimization/skus_test.go
pkg/tool/gen-disk-skus-map.go
pkg/util/util.go
vendor/k8s.io/cloud-provider/fake/doc.go
vendor/k8s.io/cloud-provider/fake/fake.go
vendor/modules.txt

/kind cleanup
This PR refactors the bulk of the device perf optimization code into its own package to enable cleaner merging with the V2 driver implementation on the `main_v2` branch.
In the V2 driver, mount point and device set up is performed by a separate Provisioner library that can have no upward dependencies on the main `azuredisk` package. This PR refactors the device perf optimization code into its own package so that it can be consumed by both the V1 driver and V2 Provisioner library implementations without introducing circular dependencies.
I am submitting these changes to master to make it cleaner and easier to merge the …

chore: Refactor device perf optimization code for cleaner merging with V2 driver

---

hack/verify-examples.sh

/kind cleanup
Modifies the `./hack/verify-examples.sh` script to wait for example rollouts to complete and exit with an error on rollout failure.
Fixes #883 #851 
```
none
```

chore: Wait for examples to complete and return error on failed rollout

---

.github/workflows/linux.yml
.travis.yml

test: fix
/kind test
test: fix broken code coverage
Fixes #
```
none
```

test: fix broken code coverage

---

pkg/azuredisk/controllerserver.go

/kind bug
fix: ZRS node affinity setting
ZRS disk should be scheduled on all nodes, ignore `accessibility_requirements.requisite` setting.
Fixes #
```
fix: ZRS node affinity setting
```

fix: ZRS node affinity setting

---

deploy/example/sharedisk/README.md

Delete 'preview' word this document because of Azure shared disks are already GA.
ref https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-azure-shared-disks-and-new-azure-disk-storage-enhancements/
ref https://github.com/MicrosoftDocs/azure-docs/commit/d9d713c890f20513f49ee5597bd9ec3e84c042e5
Fixes #
```
none
```

doc: delete 'preview' word because of Azure shared disk are already GA

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
test/e2e/dynamic_provisioning_test.go

/kind bug
fix: translation issue due to lower case managed kind
Fixes https://github.com/kubernetes/kubernetes/issues/103433
```
fix: translation issue due to lower case managed kind
```

fix: translation issue due to lower case managed kind

---

.github/workflows/windows.yml
pkg/azuredisk/nodeserver_test.go

/kind test
test: switch to csi-proxy v1.0.0-rc.1 in unit test
Fixes #
```
none
```

test: switch to csi-proxy v1.0.0-rc.1 in unit test

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_subpath_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
Fixes #741 
```
none
```

test: Add e2e test for volume subpath mount

---

deploy/example/daemonset-azuredisk-ephemeral.yaml
hack/verify-examples.sh
test/external-e2e/manifest/testdriver.yaml
test/external-e2e/run.sh
test/utils/azuredisk_log.sh

/kind test
test: alternative driver name e2e test
Fixes #
```
none
```

test: alternative driver name e2e test

---

docs/driver-parameters.md
pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: support disk io bursting
Fixes #
```
feat: support disk io bursting
```

feat: support disk io bursting

---

pkg/azuredisk/nodeserver.go

/kind bug
fix: unmount failure due to incorrect mount path check
Fixes #
```
fix: unmount failure due to incorrect mount path check
```

fix: unmount failure due to incorrect mount path check

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v1.go
pkg/azuredisk/azuredisk_v2.go
pkg/azurediskplugin/main.go
test/e2e/suite_test.go

/kind cleanup
chore: refine driver parameter setting
Fixes #
```
chore: refine driver parameter setting
```

chore: refine driver parameter setting

---

.github/workflows/windows.yml
test/e2e/manifest/migration-windows.json
test/e2e/manifest/windows.json

/kind test
test: switch to csi-proxy-v1.0.0 config
Fixes #
```
none
```

test: switch to csi-proxy-v1.0.0 config

---

pkg/mounter/safe_mounter_v1beta_windows.go

/kind cleanup
cleanup: refine csi-proxy v1beta interface
Fixes #
```
none
```

cleanup: refine csi-proxy v1beta interface

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go

/kind bug
Disable NetworkAccessPolicy on Azure Stack Cloud because it is not supported on Azure Stack.
Fixes #957
```
none
```

fix: disable networkAccessPolicy on Azure Stack Cloud

---

pkg/azuredisk/azure.go
pkg/azuredisk/azure_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/version.go

/kind feature
feat: change default userAgent
- original userAgent: `Go/go1.14.2 (amd64-linux) go-autorest/v14.2.1; kubernetes-cloudprovider/v0.0.0-master+$Format:%h$`
- current userAgent: `disk.csi.azure.com/v1.6.0 gc/go1.16.6 (amd64-linux) db5fe240b5e8eebc52b1806bd33651f20ad41caf/2021-08-09T10:18:40Z`
Fixes #536 
```
feat: change default userAgent
```

feat: change default userAgent

---

pkg/azuredisk/azure.go
pkg/azuredisk/azure_test.go
pkg/azuredisk/version.go
pkg/azuredisk/version_test.go

/kind bug
fix: disable disk related rate limit
Fixes #
```
fix: disable disk related rate limit
```

fix: disable disk related rate limit

---

pkg/azuredisk/controllerserver_test.go

/kind test
Increases the UT coverage for controllerserver.go to aid with the goal of keeping CSI drivers above 80% code coverage
Fixes #717 
```
none
```

test: improve UT coverage for controllerserver.go

---

OWNERS

/kind cleanup
Per our conversation yesterday, I am requesting to be added to the list of reviewers for this repo.
```
none
```

chore: Add edreed to reviewers

---

pkg/azurediskplugin/main.go

/kind bug
fix: enable avset setting by default
fix the test case failure on capz standalone vm type
Fixes #
```
fix: enable avset setting by default
```

fix: enable avset setting by default

---

deploy/example/sharedisk/README.md
deploy/example/sharedisk/deployment.yaml

doc: fix shared disk doc
Fixes #1003
@circy9 
```
none
```

doc: fix shared disk doc

---

test/e2e/manifest/in-tree-vmss.json
test/e2e/manifest/in-tree.json
test/e2e/manifest/migration-windows.json
test/e2e/manifest/migration.json
test/e2e/manifest/multi-az.json
test/e2e/manifest/single-az.json
test/external-e2e/manifest/single-az.json

/kind test
test: remove deprecated test configs
Fixes #
```
none
```

test: remove deprecated test configs

---

test/e2e/pre_provisioning_test.go

/kind bug
* the pre-provisioning tests currently do not clean up created volumes and the volumes are not deleted until user manually deletes them from portal or CLI.
Fixes #
```
none
```

test: pre-provisioning-test should clean up created volumes unless told not to

---

pkg/azuredisk/azure_common_windows.go
pkg/mounter/safe_mounter_v1beta_windows.go
pkg/mounter/safe_mounter_windows.go

/kind cleanup
Abstracts the CSI Proxy client implementation behind an interface to avoid the need for consumers to use explicit type assertions to detect the correct implementation.
```
none
```

chore: Abstract release and beta CSI Proxy behind interface

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go

/kind bug
fix: add AccessMode_SINGLE_NODE_READER_ONLY cap
Fixes #
```
fix: add AccessMode_SINGLE_NODE_READER_ONLY cap
```

fix: add AccessMode_SINGLE_NODE_READER_ONLY cap

---

Makefile
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
test/sanity/run-test.sh

add missing cap
/kind feature
feat: add ReadWriteOncePod cap
Fixes #
```
feat: add ReadWriteOncePod cap
```

feat: add ReadWriteOncePod cap

---

Makefile
docs/csi-dev.md

/kind feature
Enables existing functionality for new OS Windows Server 2022
Fixes #
ltsc2022 is the MCR tag for Windows Server 2022
https://hub.docker.com/_/microsoft-windows-nanoserver
There is an identical PR here: https://github.com/kubernetes-sigs/azurefile-csi-driver/pull/807
There is 
```
none
```

Added WS2022 to Makefile build process

---

Makefile
docs/csi-dev.md

/kind feature
feat: add 20H2 Windows image support
Fixes #
```
feat: add 20H2 Windows image support
```

feat: add 20H2 Windows image support

---

pkg/azureconstants/azure_constants.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azureutils/azure_disk_utils.go

/kind bug
fix: snapshot throttling issue
This PR is to workaround snapshot backoff issue: https://github.com/kubernetes-csi/external-snapshotter/issues/533
Fixes #
```
fix: snapshot throttling issue
```

fix: snapshot throttling issue

---

docs/driver-parameters.md
pkg/azurediskplugin/Dockerfile
test/e2e/dynamic_provisioning_test.go
test/integration/run-test.sh

/kind feature
feat: add btrfs file system support
Fixes #
```
feat: add btrfs file system support
```

feat: add btrfs file system support

---

test/e2e/dynamic_provisioning_test.go

test: only run btrfs in CSI driver e2e tests
Fixes #
```
none
```

test: only run btrfs in CSI driver e2e tests

---

test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go

/kind flake
test: fix Windows containerd test failures
Fixes #
```
none
```

test: fix Windows containerd test failures

---

docs/driver-parameters.md
pkg/azuredisk/controllerserver.go

/kind feature
feat: add location parameter in snapshot class
Fixes #
```
feat: add location parameter in snapshot class
```

feat: add location parameter in snapshot class

---

OWNERS

/kind cleanup
Adds @edreed to approvers for this repository.
```
none
```

chore: Add edreed to approvers

---

Makefile

/kind cleanup
cleanup: remove arm64 build workaround
Fixes #
```
none
```

cleanup: remove arm64 build workaround

---

test/e2e/pre_provisioning_test.go

/kind cleanup
Re-enables the shared disk test case on Windows e2e tests now that the correct version of CSI Proxy is being used. (See kubernetes/test-infra#24418.) This reverts commit f5bbfa7ae8d8cb0ed920163c9df6210666ffbed0.
Fixes #
```
none
```

chore: Revert "flake: Disable failing test"

---

Makefile

/kind feature
feat: remove 1903 1909 2004 Windows image which is end of life
Fixes #
```
feat: remove 1903 1909 2004 Windows image which is end of life
```

feat: remove 1903 1909 2004 Windows image which is end of life

---

.github/workflows/pluto.yaml

/kind test
test: add apiVersion deprecation test
Fixes #
```
none
```

test: add apiVersion deprecation test

---

.github/workflows/pluto.yaml

/kind test
test: add more apiVersion check test
Fixes #
```
none
```

test: add more apiVersion check test

---

.github/workflows/pluto.yaml
pkg/azurediskplugin/Dockerfile

/kind bug
fix: CVE-2021-43618 in Ubuntu image
Fixes #
```
test/azuredisk-csi:latest (debian 11.0)
=======================================
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+----------+------------------+----------+-------------------+------------------------+---------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |     FIXED VERSION      |                 TITLE                 |
+----------+------------------+----------+-------------------+------------------------+---------------------------------------+
| libgmp10 | CVE-2021-43618   | HIGH     | …
```

fix: CVE-2021-43618 in Ubuntu image

---

deploy/example/snapshot/README.md
deploy/example/snapshot/azuredisk-volume-snapshot.yaml
deploy/example/snapshot/storageclass-azuredisk-snapshot.yaml
docs/driver-parameters.md

doc: change snapshot v1beta1 to v1
Fixes #
```
none
```

doc: change snapshot v1beta1 to v1

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
test/e2e/dynamic_provisioning_test.go
test/e2e/pre_provisioning_test.go
test/e2e/testsuites/pre_provisioned_dangling_attach_volume_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

This PR adds a verification check for supported volume capabilities to CSI RPC requests.
Our driver doesn't support RWX access mode for filesystem volumes, yet we didn't have a specific check for preventing the use of such configuration.
Fixes #
```
none
```

bug: Adding supported VolumeCapabilites verification check to CSI RPC requests.

---

test/utils/controller-manager-log.sh

test: fix kcm log print issue
Fixes #
```
none
```

test: fix kcm log print issue

---

pkg/azuredisk/controllerserver_test.go
pkg/azureutils/azure_disk_utils_test.go
pkg/azureutils/osiohandler_test.go

/kind cleanup
Improves unit test code coverage of pkg/azueutils.
Fixes #
```
none
```

chore: Improve unit test coverage of pkg/azureutils

---

Makefile
hack/parse-prow-creds.sh

test: add workaround for capz tests
Fixes #
```
none
```

test: add workaround for capz tests

---

test/utils/controller-manager-log.sh

/kind test
test: fix get kcm logs error in e2e test
Fixes #
```
none
```

test: fix get kcm logs error in e2e test

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go

/kind bug
fix: tag parsing issue in CreateSnapshot
that's a common mistake for golang beginner
Fixes #1139
```
fix: tag parsing issue in CreateSnapshot
```

fix: tag parsing issue in CreateSnapshot

---

pkg/azurediskplugin/Dockerfile

patch CVE-2021-3995 and CVE-2021-3996
```
+---------------+------------------+----------+-------------------+------------------+--------------------------------------+
|    LIBRARY    | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |                TITLE                 |
+---------------+------------------+----------+-------------------+------------------+--------------------------------------+
| bsdutils      | CVE-2021-3995    | UNKNOWN  | 2.36.1-8          | 2.36.1-8+deb11u1 | -->avd.aquasec.com/nvd/cve-2021-3995 |
+               +------------------+          +                   +                  +--------------------------------------+
|               | CVE-2021-3996    |          | …
```

fix: patch CVE-2021-3995 and CVE-2021-3996

---

pkg/azurediskplugin/Dockerfile

/kind bug
fix: CVE-2021-3996 in image build
Fixes #
```
Total: 2 (UNKNOWN: 2, LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0)
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| bsdutils | CVE-2021-3995    | UNKNOWN  | 2.36.1-8          | 2.36.1-8+deb11u1 | -->avd.aquasec.com/nvd/cve-2021-3995 |
+          +------------------+ …
```

fix: CVE-2021-3996 in image build

---

pkg/azurediskplugin/Dockerfile

/kind cleanup
cleanup: remove unnecessary packages
Fixes #
```
none
```

cleanup: remove unnecessary packages

---

test/e2e/driver/azuredisk_driver.go
test/e2e/driver/driver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
The existing share disk test cases do not actually test the supported scenario; that is, mounting a shared disk to multiple pods on different nodes as a block device. This PR add E2E test case to the dynamic- and pre-provisioning tests that exercise this scenario.
```
none
```

test: Add shared disk E2E tests that match supported scenario

---

test/e2e/pre_provisioning_test.go

/kind cleanup
Removes a shared test case made obsolete and redundant by #1156 . See [discussion](https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1156#discussion_r792930618).
```
none
```

chore: Remove obsolete & redundant test shared disk case

---

.github/workflows/static.yaml
pkg/azurediskplugin/main.go
pkg/azureutils/azure_disk_utils.go
pkg/util/util_test.go

fix error
/kind test
test: add more go linters
Fixes #
```
test: add more go linters
```

test: add more go linters

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go

/kind test
adds a test to validate dynamic resizing on zones that support LiveResize
Fixes #
```
none
```

test: validate dynamically resized volumes

---

pkg/azuredisk/nodeserver_test.go

/kind cleanup
Fixes an incorrect usage of `fmt.Sprint` in `nodeserver_test.go`.
Fixes #
```
none
```

chore: Fix misuse of fmt.Sprint in nodeserver_test.go

---

deploy/example/resize/README.md

doc: refine online resize doc
Fixes #
```
none
```

doc: refine online resize doc

---

pkg/azuredisk/azuredisk.go

/kind bug
fix: GetDisk throttling issue
Fixes #
```
fix: GetDisk throttling issue
```

fix: GetDisk throttling issue

---

docs/driver-parameters.md
pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azurediskplugin/main.go

/kind feature
feat: disable async attach by default
Fixes #
```
chore: disable async attach by default
```

feat: disable async attach by default

---

charts/README.md
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go

/kind bug
fix: NodePublishVolume idempotent issue
Fixes #
```
fix: NodePublishVolume idempotent issue
```

fix: NodePublishVolume idempotent issue

---

deploy/example/storageclass-azuredisk-csi-azurestack.yaml
deploy/example/storageclass-azuredisk-csi-large-scale.yaml
deploy/example/storageclass-azuredisk-csi.yaml
deploy/example/topology/README.md

doc: refine ZRS disk example
Fixes #
```
none
```

doc: refine ZRS disk example

---

deploy/install-driver.sh
deploy/uninstall-driver.sh

/kind bug
fix: azure disk controller install issue
Fixes #
```
fix: azure disk controller install issue
```

fix: azure disk controller install issue

---

pkg/azuredisk/azuredisk.go
pkg/azurediskplugin/main.go

/kind feature
feat: disable ListVolumes and ListSnapshosts by default
Fixes #
<details>
E0222 15:45:56.787963       1 utils.go:100] GRPC error: rpc error: code = Internal desc = ListVolumes on rg(mc_xxx_taks001eu41t-one_westeurope) failed with error: Retriable: false, RetryAfter: 299s, HTTPStatusCode: 429, RawError: {"error":{"code":"SubscriptionRequestsThrottled","message":"Number of read requests for subscription 'xxx' exceeded the limit of '12000' for time interval '01:00:00'. Please try again after '300' seconds."}}
E0222 15:53:21.020227       1 utils.go:100] GRPC error: rpc error: code = Internal desc = ListVolumes on …

feat: disable ListVolumes and ListSnapshosts by default

---

deploy/rbac-csi-azuredisk-controller.yaml
deploy/rbac-csi-azuredisk-node.yaml

/kind cleanup
cleanup: remove unnecessary namespace config in ClusterRole
Fixes #1202
```
none
```

cleanup: remove unnecessary namespace config in ClusterRole

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/optimization/device_perf_linux_test.go
pkg/optimization/skus.go
pkg/optimization/skus_test.go

/kind cleanup
cleanup: get zone info in in driver initialization
get zone info actually is not necessary in driver initialization
Fixes #
```
none
```

cleanup: get zone info in in driver initialization

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azurediskplugin/Dockerfile

/kind bug
fix: CVE-2022-0778 in image build
Fixes #
```
fix: CVE-2022-0778 in image build
```

fix: CVE-2022-0778 in image build

---

pkg/azurediskplugin/Dockerfile

/kind bug
Fix vulnerability [CVE-2022-0778](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-0778).
Fixes #
```
none
```

[V2] fix: Fix CVE-2022-0778

---

Makefile
test/e2e/testsuites/pre_provisioned_dangling_attach_volume_tester.go
test/e2e/testsuites/testsuites.go

test: fix capz test failure
Fixes #
```
none
```

test: fix capz test failure

---

pkg/azurediskplugin/Dockerfile

/kind bug
Fixes CVE-2022-0778 by upgrading to alpine:3.15.1 and ensuring its components are up-to-date. With this change, it is no longer necessary to add the openssl package to update libssl.
```
none
```

[V2] fix: Fix CVE-2022-0778 for libretls

---

pkg/azuredisk/azuredisk_v2.go
pkg/controller/attach_detach.go
pkg/controller/azdrivernode.go
pkg/controller/azvolume.go
pkg/controller/common.go
pkg/controller/common_test.go
pkg/controller/node_availability.go
pkg/controller/pod.go
pkg/controller/pv.go
pkg/controller/replica.go

/kind bug
* There is a potential race between controller recovery operation and reconciler goroutine and this PR addresses that issue.
Fixes #
```
none
```

[V2] fix: prevent race between controller reconciler and controller recovery

---

test/e2e/dynamic_provisioning_test.go

test: fix volume cloning test failure on capz
Fixes #
```
none
```
/test pull-azuredisk-csi-driver-e2e-capz

test: fix volume cloning test failure on capz

---

pkg/controller/common.go

/kind bug
* Controller's operation queue relies on `list.List` data structure, which can get corrupted if `list.Remove(&a)` is used after `list.Init()`.
* This PR addresses this issue along with other identified bug of operation queue.
Fixes #
```
none
```

[V2] bug: controller operation queue fix

---

OWNERS

Add nearora to the reviewers/approvers list for main_v2 branch

---

test/external-e2e/run.sh

/kind test
test: run external 1.23 tests
Fixes #
```
none
```

test: run external 1.23 tests

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/nodeserver_v2.go
pkg/azurediskplugin/main.go

Increasing the default rest client QPS and disabling listVolume capability by default to optimize performance of the driver.
Fixes #
```
none
```

[V2] chore: Adding flags for qps and disabling listvolume by default.

---

pkg/provisioner/crdprovisioner.go

/kind bug
Issue: When a ControllerPublishVolume call comes for a replica attachment, it is moved to demoted state. If another ControllerPublishVolume  comes for the same attachment, the current implementation deletes the replica attachment because of this condition that whether the volume attachment is a replica or not becomes true here the 2nd time around: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/467066e583ee720abc58b66a95d3332269753112/pkg/provisioner/crdprovisioner.go#L631
Fix: Remove this condition from the UnpublishVolume function and create a separate function for deatching the volume
Fixes #
**Release …

[V2] fix: Avoid calling detach for ControllerUnpublish Volume

---

pkg/controller/common.go

/kind bug
* VolumeDetachRequested annotation is being added when it shouldn't be.
Fixes #
```
none
```

[V2] bug: fix AzVolumeAttachment clean-up

---

hack/azure-cluster-up.sh

/kind cleanup
This PR addresses ShellCheck warnings in the `azure-cluster-up.sh` script.
```
none
```

[V2] chore: Address ShellCheck warnings in azure-cluster-up.sh

---

pkg/provisioner/crdprovisioner.go
pkg/provisioner/crdprovisioner_test.go

* `ExpandVolume` does not reset the `AzVolume.Status.Error` and `AzVolume.Status.State` and the volume expand operation will never get requeued properly if the operaiton failed on its first attempt.
Fixes #
```
none
```

[V2] bug: expandVolume does not get retriggered upon failed operation

---

pkg/azurediskplugin/Dockerfile

/kind bug
fix: CVE-2018-25032
Fixes #
```
Total: 1 (UNKNOWN: 0, LOW: 0, MEDIUM: 0, HIGH: 1, CRITICAL: 0)
+---------+------------------+----------+-------------------+-------------------------+---------------------------------------+
| LIBRARY | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |      FIXED VERSION      |                 TITLE                 |
+---------+------------------+----------+-------------------+-------------------------+---------------------------------------+
| zlib1g  | CVE-2018-25032   | HIGH     | 1:1.2.11.dfsg-2   | 1:1.2.11.dfsg-2+deb11u1 | zlib: A flaw in zlib-1.2.11           |
|         | …
```

fix: CVE-2018-25032 in image build

---

deploy/example/pv-azuredisk-csi.yaml
deploy/example/pvc-azuredisk-csi-static.yaml

doc: refine static PV example
Fixes #
```
none
```

doc: refine static PV example

---

.github/workflows/static.yaml

/kind test
Cherry pick of #1268 .
```
none
```

[V2] test: fix golinter error

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_common.go

[V2] chore: Updating cloud provider azure

---

test/external-e2e/run.sh

/kind test
test: enable external slow tests
Fixes #
```
none
```

test: enable external slow tests

---

charts/index.yaml

[v2] chore: Re-generating index file for helm charts.

---

test/external-e2e/manifest/testdriver.yaml
test/external-e2e/run.sh

/kind test
test: enable external pvcDataSource test
Fixes #
```
none
```

test: enable external pvcDataSource test

---

hack/verify-examples.sh
test/e2e/dynamic_provisioning_test.go
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind test
test: support Win2022 test on capz
Fixes #
```
none
```

test: support Win2022 test on capz

---

pkg/azurediskplugin/Dockerfile

/kind bug
fix: CVE-2022-1271 in image build
```
+----------+------------------+----------+-------------------+-------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |   FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+-------------------+--------------------------------------+
| gzip     | CVE-2022-1271    | HIGH     | 1.10-4            | 1.10-4+deb11u1    | gzip: arbitrary-file-write           |
|          |                  |          |                   |                   | vulnerability                        |
|          |                  |          |                   | …
```

fix: CVE-2022-1271 in image build

---

hack/verify-examples.sh

/kind cleanup
When running e2e tests interactively, `/hack/verify-examples.sh` runs as a part of the `ginkgo.AfterSuite` test hook in `test/e2e/suite_test.go`. This script leaks a deployment and stateful set that can interfere to subsequent test runs that expect a clean system.
Fixes #1288 
```
none
```

[V2] fix: Fix verify-examples.sh leak resources created 🐞

---

pkg/azurediskplugin/Dockerfile

/kind cleanup
chore: refine package patching in image build
Fixes #
```
none
```

chore: refine package patching in image build

---

pkg/controller/azvolume.go
pkg/controller/common.go

/kind bug
* With current implementation, failed operation can end up getting requeued to a "to be deleted" operation queue if operation queue is cleaned up in the middle of the operation.
* This can lead to situations where an operation queue for a deleted volume continues rolling with failure and flooding logs and wasting resources.
Fixes #
```
none
```

[V2] bug: failed operation should not be requeued if operation queue is scheduled for deletion

---

.golangci.yml
cmd/az-analyze/cmd/azv.go

/kind cleanup
This PR squelches `forbidigo` errors for the `az-analyze` tool since it's a command line tool and expected to print to the console. 
This PR also address a `gosimple` error.
Fixes #1302 
```
none
```

[V2] chore: Address linter issues in az-analyze tool

---

go.mod
pkg/azureconstants/azure_constants.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver_test.go
pkg/azureutils/azure_disk_utils.go
pkg/controller/attach_detach.go
pkg/controller/attach_detach_test.go
pkg/controller/azdrivernode.go
pkg/controller/azdrivernode_test.go
pkg/controller/azvolume.go
pkg/controller/azvolume_test.go
pkg/controller/common.go
pkg/controller/node_availability.go
pkg/controller/node_availability_test.go
pkg/controller/pod.go
pkg/controller/pod_test.go
pkg/controller/pv.go
pkg/controller/pv_test.go
pkg/controller/replica.go
pkg/controller/replica_test.go
pkg/provisioner/cloudprovisioner.go
pkg/provisioner/cloudprovisioner_test.go
pkg/provisioner/conditionwaiter.go
pkg/provisioner/crdprovisioner.go
pkg/provisioner/crdprovisioner_test.go
pkg/workflow/logger.go
pkg/workflow/workflow.go
pkg/workflow/workflow_test.go

/kind feature
* Given the v2 driver’s current logging pattern, it is difficult to track the entire end to end workflow, adversely affecting the logs’ readability and the overall debugging experience.
* This PR leverages CRI annotations and golang context to enhance the logging pattern so that each workflow can be tracked end to end more easily.
Fixes #
```
none
```

[V2] feat: add end to end workflow logging

---

test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go

/kind bug
* `DynamicallyProvisionedCollocatedPodTest` seemed to be using node selector inconsistently and pods were being scheduled to different nodes.
Fixes #
* After pushing the change to main_v2, we can cherry-pick the commit to raise PR for v1 branch as well?
```
none
```

[V2] bug: collocated pod tester fix

---

pkg/azuredisk/azure_common_unix.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_v2.go

/kind bug
fix: resize failure on Windows
`resizer.Resize` is not implemented on Windows, it would get failure
Fixes #
```
fix: resize failure on Windows
```

fix: resize failure on Windows

---

pkg/provisioner/crdprovisioner.go

/kind bug
* AzVolume CRI status was not being updated after failed ExpandVolume operation, hence, the error field and CRI state was not reset properly to retrigger the failed operation.
Fixes #
```
none
```

[V2] bug: AzVolume CRI Status needs to be updated on ExpandVolume retries

---

pkg/azdiskschedulerextender/azdiskschedulerextender.go

/kind feature
Adds a `--kubeconfig` flag which is needed by Azure Kubernetes Service for the scheduler extender to run in the cluster control plane.
```
none
```

feat: Add kubeconfig flag to the scheduler extender

---

test/external-e2e/run.sh

/kind cleanup
Removes the use of `sudo` from the external e2e test runner script since this is neither necessary nor available in the kubetest environment.
```
none
```

[V2] chore: Fix external e2e test script for kubetest environment

---

test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_tester.go
test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
test/e2e/testsuites/testsuites.go

fix
/kind test
test: fix unstable issue for e2e test which checks file content
Fixes #
```
none
```

test: fix unstable e2e tests which check file content

---

test/scale/scale_tester.go

Call to sleep was missing in the scale test.
Fixes #
```
none
```

[V2] bug: Adding missing timeout in scale test 

---

test/e2e/dynamic_provisioning_test.go
test/resources/resource_setup.go

/kind bug
* Dynamic resize tests were failing because the test was attempting live resize on `STANDARD_LRS` instead of `STANDARDSSD_LRS`
* And test storageclass was being misconfigured for single zone clusters.
Fixes #
```
none
```

[V2] bug: address dynamic resizing failure and test storageclass setup

---

pkg/azuredisk/azure_common_darwin.go
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/azure_common_windows.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go
pkg/mounter/safe_mounter_v1beta_windows.go
pkg/mounter/safe_mounter_windows.go
test/external-e2e/run.sh

/kind bug
fix: NodeGetVolumeStats failure on Windows node, Original volume stat is broken on Windows node, it would get the os disk stat instead of volume
Fixes #
```
fix: NodeGetVolumeStats failure on Windows node
```

fix: NodeGetVolumeStats failure on Windows node

---

test/e2e/dynamic_provisioning_test.go

/kind test
Disable the "Should test an increase in replicas when scaling up" test case while investigating failures.
Fixes #
```
none
```

[V2] chore: Disable failing test

---

pkg/azuredisk/azuredisk_v2.go

/kind cleanup
Removes dead code from `azuredisk_v2.go`.
Fixes #
```
none
```

[V2] chore: Remove dead code from azuredisk_v2.go

---

test/e2e/dynamic_provisioning_test.go

/kind test
/kind flake
* Disables the flakey "Should test pod failover and check for correct number of replicas" on Windows pending investigation. Reopened #1349 .
* Disables "should check failed replica attachments are recreated after space is made from a volume detaching." test case pending resolution of #1378 .
Fixes #
```
none
```

[V2] flake: Disable flakey tests

---

pkg/controller/replica.go

/kind bug
* replica controller was not properly calling `triggerManageReplica` upon replica AzVolumeAttachment deletion causing problems in maintaining replica number for some volumes.
Fixes #
```
none
```

[V2] bug: replica deletion sometimes does not trigger manageReplica operation

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go

/kind cleanup
Fixes #
```
none
```

fix: Put GetDiskLun log after it is called

---

test/external-e2e/run.sh

/kind test
/kind cleanup
The are several test cases in the external end-to-end tests suite that are intended to run serially. These are marked by the `"[Serial]"` tag. This PR updates the external e2e test script to run these test cases sequentially to avoid failures caused by other tests running in parallel on the same node(s).
Fixes #
```
none
```

[V2] chore: Run serial external e2e tests sequentially

---

pkg/provisioner/crdprovisioner.go

/kind bug
/kind regression
An attach operation is only started by the `attach_detach` controller if the `AzVolumeAttachment.Status.Detail` field is `nil`. This PR set this field to `nil` when we need to retry an attach operation. This PR also updates the workflow annotations when the retry is triggered via `CrdProvisioner.WatchForAttach` or `CrdProvisioner.waitForLun`.
Fixes #
```
none
```

[V2] fix: fix retry of failed attach

---

pkg/azuredisk/version.go
pkg/azuredisk/version_test.go

/kind cleanup
chore: shorten userAgent
Fixes #
```
none
```

chore: shorten userAgent

---

test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go
test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go

/kind test
/kind flake
Fixes #
```
none
```

[V2] test: Ensure original pods exit before clone is mounted

---

pkg/azureconstants/azure_constants.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/azuredisk_v2_test.go
pkg/azuredisk/fake_azuredisk_v2.go
pkg/azuredisk/interface_v2.go
pkg/azuredisk/mockprovisioner/interface.go
pkg/provisioner/crdprovisioner.go
pkg/provisioner/fake_crdprovisioner.go
test/integration/controller/controller_test.go

/kind bug
Ensures the `AzDriverNode` object for a node is recreated if deleted.
Fixes #1356 
```
none
```

[V2] fix: ensure AzDriverNode recreated if deleted

---

pkg/azureconstants/azure_constants.go
pkg/azureutils/azure_disk_utils.go
pkg/controller/attach_detach.go
pkg/controller/attach_detach_test.go
pkg/controller/azvolume.go
pkg/controller/common.go
pkg/controller/pv.go
pkg/controller/replica.go
pkg/controller/volumeattachment.go
pkg/controller/volumeattachment_test.go
pkg/provisioner/cloudprovisioner.go
pkg/provisioner/crdprovisioner.go
pkg/provisioner/crdprovisioner_test.go
pkg/watcher/conditionwaiter.go
pkg/watcher/conditionwatcher.go
pkg/workflow/workflow.go
test/integration/run-test.sh

/kind regression
* This PR addresses several areas of problems along with optimizations within `azuredisk-csi-driver` pkg that had contributed to scale test regression.
* Another PR will be filed containing fix in `cloud-provider-azure` vendor pkg that had mainly contributed to the scale test regression.
Fixes #
```
none
```

[V2] bug: scale test regression fix

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_v2.go

/kind bug
fix: CSI function should return internal error
Fixes #
```
fix: CSI function should return internal error
```

fix: CSI function should return internal error

---

Makefile

chore: switch master branch to use v1.21.0
Fixes #
<details>
```
git checkout -b switch-master-1.21.0
sed -i 's/1.20.0/1.21.0/g' Makefile
$git_commit
git push origin switch-master-1.21.0
```
</details>
```
none
```

chore: switch master branch to use v1.21.0

---

pkg/azdiskschedulerextender/azdiskschedulerextender.go
pkg/azureconstants/azure_constants.go
pkg/azuredisk/azuredisk_v2.go
pkg/azureutils/azure_disk_utils.go
pkg/controller/attach_detach.go
pkg/controller/attach_detach_test.go
pkg/controller/azdrivernode.go
pkg/controller/azvolume.go
pkg/controller/common.go
pkg/controller/common_test.go
pkg/controller/replica.go
pkg/provisioner/cloudprovisioner_test.go
pkg/provisioner/crdprovisioner.go
pkg/provisioner/crdprovisioner_test.go
test/e2e/testsuites/azdiskschedulerextender_pod_scheduling_on_failover_multiple_pv_perf_tester.go
test/e2e/testsuites/dynamically_provisioned_garbage_collection_replica_attachment_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_with_replicas_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_scale_up_with_replicas.go
test/integration/controller/controller_test.go
test/resources/utils.go

request
/kind feature
* This PR includes a temporary change to allow detach of replica attachment for primary attachment request.
* It targets to handle other relevant data race issues.
Fixes #
```
none
```

[V2] feat: allow detaches of replica attachment for primary attachment

---

Makefile

Fixes #
<details>
```
git checkout -b switch-master-1.22.0
sed -i 's/1.21.0/1.22.0/g' Makefile
$git_commit
git push origin switch-master-1.22.0
```
</details>
```
none
```

chore: switch master branch to use v1.22.0

---

pkg/apis/client/clientset/versioned/fake/register.go
pkg/apis/client/clientset/versioned/scheme/register.go
pkg/azdiskschedulerextender/azdiskschedulerextender_test.go
pkg/azureutils/azure_disk_utils.go
pkg/controller/attach_detach.go
pkg/controller/azvolume.go
pkg/controller/common.go
pkg/controller/pod.go
pkg/controller/pv.go
pkg/controller/volumeattachment.go
pkg/mounter/safe_mounter_v1beta_windows.go
pkg/mounter/safe_mounter_windows.go
pkg/optimization/skus.go
test/e2e/testsuites/dynamically_provisioned_pod_affinity.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_with_replicas_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_node_affinity.go
test/e2e/testsuites/dynamically_provisioned_pod_node_selector.go
test/e2e/testsuites/dynamically_provisioned_pod_scale_up_with_replicas.go
test/e2e/testsuites/dynamically_provisioned_pod_toleration.go

/kind cleanup
This PR corrects formatting issues identified by gofmt 1.19 additional rules.
Fixes #
```
none
```

chore: gofmt 1.19 fixes

---

test/e2e/testsuites/dynamically_provisioned_collocated_pod_tester.go

/kind test
Sometimes Windows take longer than 5 minutes to pull down images. This PR extended the wait in one flaky test case to prevent test failures when this happens.
Fixes #
```
none
```

test: Wait longer for colocated pods to start

---

pkg/azureutils/azure_snapshot_utils_test.go

/kind test
add snapshot unit test
Fixes #1424
```
none
```

test: add snapshot unit test

---

pkg/azureutils/fake_hostutil_test.go
pkg/azureutils/fake_iohandler_test.go

/kind test
add fake host util and io handler unit test
Fixes #1424
```
none
```

test: add fake host util and io handler unit test

---

pkg/mounter/fake_safe_mounter.go
pkg/mounter/fake_safe_mounter_test.go

/kind test
add fake_safe_mounter unit test
Fixes #1424
```
none
```

test: add fake_safe_mounter unit test

---

pkg/optimization/device_perf.go
pkg/optimization/device_perf_linux.go
pkg/optimization/device_perf_linux_test.go
pkg/optimization/device_perf_test.go
pkg/optimization/device_perf_unsupported.go

/kind test
add device_perf_linux.go unit test
Fixes #1424
```
none
```

test: add device_perf_linux.go unit test

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
test/e2e/dynamic_provisioning_test.go

/kind bug
fix: invalid ultra disk default iops issue
Fixes #1442
this PR tries to fix the following issue:
```
"error": {
"code": "BadRequest",
"message": "The value 500 of parameter disk.diskIOPSReadWrite is not valid. The supported range for a UltraSSD_LRS disk of size 512 GB is between 512 and 153600."
}
```
```
fix: invalid ultra disk default iops issue
```

fix: invalid ultra disk default iops issue

---

pkg/azuredisk/controllerserver.go

/kind cleanup
Logs the VM provisioning state returned by `GetDiskLun` in order to help debug attach disk issues.
Fixes #
```
none
```

chore: log VM provisioning state

---

pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/version_test.go

/kind test
add azuredisk.go unit test
Fixes #1424
```
none
```

test: add azuredisk.go unit test

---

OWNERS

Add landreasyan to owners list.

---

pkg/csi-common/server_test.go

/kind test
reduce the time cost of ut
Fixes #
```
none
```

test: reduce the time cost of ut

---

Makefile

chore: switch master branch to use v1.23.0
Fixes #
<details>
```
git checkout -b switch-master-1.1.23.0
sed -i 's/1.22.0/1.23.0/g' Makefile
$git_commit
git push origin switch-master-1.1.23.0
```
</details>
```
none
```

chore: switch master branch to use v1.23.0

---

charts/README.md

Update version and fix a type in the README
Fixes #
```
none
```

[V2] chore: update version and fix typo

---

pkg/azureutils/azure_disk_utils.go

/kind bug
All current callers of `UpdateCRIWithRetry` expected it to return a non-`nil` updated object. In the case where only the status is being updated but the update function modifies the non-status state of the object, we could end up skipping any update attempts and return a `nil` object. This PR ensures we never return `nil` from this function.
Fixes #1470 
```
none
```

[V2] fix: ensure object is always returned by UpdateCRIWithRetry

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/azuredisk_v2_test.go
pkg/azuredisk/fake_azuredisk_v2.go
pkg/azuredisk/identityserver_v2.go
pkg/azuredisk/nodeserver_v2.go

/kind cleanup
Remove duplicate fields that are defined in the `DriverCore` and `DriverV2` with a single config field that points to the `AzDiskDriverConfiguration` object.
Fixes #1469
```
none
```

[V2] chore: remove duplicate fields in DriverV2 struct

---

.github/workflows/codespell.yml
pkg/azuredisk/controllerserver_test.go
pkg/azureutils/azure_disk_utils_test.go
pkg/optimization/device_perf_helper.go

/kind cleanup
Fixes recently flagged codespell errors.
Fixes #
```
none
```

chore: fixing codespell errors

---

pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/fake_azuredisk_v2.go
pkg/azuredisk/nodeserver_v2.go

/kind cleanup
Clear up some functions that are not used or necessary but only meaningful for testing. Move them to an appropriate testing file.
Fixes #
```
none
```

[V2] chore: refactor unused functions

---

pkg/controller/azdrivernode_test.go
pkg/controller/common_test.go

/kind test
Add unit test to azdrivernode.go in controller package.
Fixes #
```
none
```

[V2] test: add unit test to azdrivernode.go

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go

/kind bug
fix: reduce VMSS throttling when throttling happens
When throttling happens, this PR would return error directly instead of continuing next operation.
Fixes #
```
fix: reduce VMSS throttling when throttling happens
```

fix: reduce VMSS throttling when throttling happens

---

pkg/controller/azvolume_test.go

/kind test
Add a unit test to `pkg/controller/azvolume.go`
Fixes #
```
none
```

[V2] test: add unit test to azvolume.go

---

pkg/controller/attach_detach_test.go

/kind test
Add unit tests to `pkg/controller/attach_detach.go`
Fixes #
```
none
```

[V2] test: add unit tests to attach_detach.go

---

pkg/controller/replica_test.go

/kind test
Add and edit unit tests to `pkg/controller/replica.go`
Fixes #
```
none
```

[V2] test: add and edit unit tests to replica.go

---

pkg/controller/pod_test.go

/kind test
Add a unit test to `pkg/controller/pod.go`
Add the other node to existing tests such that they can test if replicas are created in the same node.
Fixes #
```
none
```

[V2] test: add and edit unit tests to pod.go

---

pkg/controller/common_test.go
pkg/controller/pv.go
pkg/controller/pv_test.go

/kind test
Add unit tests to `pkg/controller/pv.go`
Fixes #
```
none
```

[V2] test: add unit tests to pv.go

---

go.mod
go.sum
vendor/golang.org/x/net/AUTHORS
vendor/golang.org/x/net/CONTRIBUTORS
vendor/golang.org/x/net/context/context.go
vendor/golang.org/x/net/context/go17.go
vendor/golang.org/x/net/context/pre_go17.go
vendor/golang.org/x/net/html/render.go
vendor/golang.org/x/net/html/token.go
vendor/golang.org/x/net/http/httpguts/httplex.go
vendor/golang.org/x/net/http2/client_conn_pool.go
vendor/golang.org/x/net/http2/errors.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/hpack/encode.go
vendor/golang.org/x/net/http2/hpack/hpack.go
vendor/golang.org/x/net/http2/hpack/huffman.go
vendor/golang.org/x/net/http2/http2.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/net/http2/writesched_priority.go
vendor/golang.org/x/net/idna/trieval.go
vendor/golang.org/x/net/websocket/websocket.go
vendor/modules.txt

[V2] chore: update net/http to fix CVE-2022-27664 vulnerability

---

test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh

/kind test
test: run sanity test on csi-test v5.0.0
Fixes #
```
test: run sanity test on csi-test v5.0.0
```

test: run sanity test on csi-test v5.0.0

---

pkg/controller/attach_detach.go
pkg/controller/azvolume.go
pkg/controller/common.go
pkg/controller/replica.go
pkg/controller/shared_state.go

fix: minor bugfix in replic management logic
Fixes #
```
none
```

[V2] fix: minor bugfix in replic management logic

---

charts/latest-v2/azuredisk-csi-driver/values.yaml
deploy/latest-v2/csi-azuredisk-scheduler-extender.yaml

/kind chore
This PR updates the requested cpu and memory usage values to p50 numbers. This change was suggested in a review comment of the aks-rp PR.
Fixes #
```
none
```

[V2] chore: update values as per p50 numbers

---

charts/latest-v2/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest-v2/azuredisk-csi-driver/values.yaml
go.mod
go.sum
pkg/apis/azuredisk/v1beta2/types.go
pkg/azureconstants/azure_constants.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver.go
pkg/azurediskplugin/main.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
pkg/provisioner/cloudprovisioner.go
test/e2e/suite_test.go
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go

Adding options to configure attach/detach rate limiter on azure client. 
Fixes #
```
none
```

[V2] Adding options to configure attach/detach rate limiter on azure client

---

pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind bug
fix: zone format check when cloud config is empty
When cloud config is empty, location field is also empty, then zone check would always return false, this PR fixed the issue.
Fixes #
```
fix: zone format check when cloud config is empty
```

fix: zone format check when cloud config is empty

---

go.mod
go.sum
pkg/apis/azuredisk/v1beta2/types.go
pkg/azureconstants/azure_constants.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
pkg/controller/attach_detach.go
pkg/controller/attach_detach_test.go
pkg/controller/azvolume_test.go
pkg/controller/common.go
pkg/controller/common_test.go
pkg/controller/pod_test.go
pkg/controller/shared_state.go
pkg/provisioner/crdprovisioner.go
test/const/test_consts.go
test/upgrade/flags.go
test/upgrade/upgrade_test.go
vendor/k8s.io/csi-translation-lib/LICENSE
vendor/k8s.io/csi-translation-lib/plugins/aws_ebs.go
vendor/k8s.io/csi-translation-lib/plugins/azure_disk.go
vendor/k8s.io/csi-translation-lib/plugins/azure_file.go
vendor/k8s.io/csi-translation-lib/plugins/const.go
vendor/k8s.io/csi-translation-lib/plugins/gce_pd.go
vendor/k8s.io/csi-translation-lib/plugins/in_tree_volume.go
vendor/k8s.io/csi-translation-lib/plugins/openstack_cinder.go
vendor/k8s.io/csi-translation-lib/plugins/portworx.go
vendor/k8s.io/csi-translation-lib/plugins/rbd.go
vendor/k8s.io/csi-translation-lib/plugins/vsphere_volume.go
vendor/modules.txt

/kind bug
* When CRIs are recovered upon controller restart, there were issues with overwriting the volumeContext and publishContext with a nil value.
* This PR addresses this problem along with adding more logic for field population in recovery path.
Fixes #
```
none
```

[V2] fix: CRI recovery should not overwrite existing values

---

pkg/watcher/conditionwaiter.go

/kind cleanup
Adds caller information to `ConditionWaiter.Wait`'s workflow to make it easier to identify the callers' delay due to wait on some condition.
Fixes #
```
none
```

[V2] chore: add the caller to ConditionWaiter.Wait workflow

---

pkg/azureconstants/azure_constants.go
pkg/azureutils/azure_disk_utils.go

/kind cleanup
* This PR adds retry count to workflow logging in `UpdateCRIWithRetry` for more insights.
Fixes #
```
none
```

[V2] chore: add retry details to workflow logging in UpdateCRIWithRetry

---

cmd/az-log/README.md
cmd/az-log/cmd/common.go
cmd/az-log/cmd/controller.go

/kind bug
1. Add configuration setup such that the user can pass controller lease name and namespace. 
2. When handling controller plugin failover, logs will continue from the switching time rather than beginning.
Fixes #1527
```
none
```

[V2] fix: az-log panics when getting the controller logs

---

deploy/csi-snapshot-controller.yaml
hack/verify-all.sh
hack/verify-helm-chart-index.sh

/kind feature
feat: add helm repo install check
Fixes #
```
none
```

test: add helm repo install check

---

pkg/azurediskplugin/Dockerfile

/kind feature
chore: upgrade base image debian-base:bullseye-v1.4.2
Fixes #
```
none
```

chore: upgrade base image debian-base:bullseye-v1.4.2

---

pkg/azuredisk/controllerserver_v2.go
pkg/provisioner/fake_crdprovisioner.go

/kind test
Added `attach_volume_latency` metric for the controllerserver
Fixes #
```
none
```

[V2] feat: added attach_volume_latency metric for controllerserver

---

test/e2e/testsuites/azdiskschedulerextender_pod_scheduling_on_failover_multiple_pv_perf_tester.go
test/e2e/testsuites/dynamically_provisioned_garbage_collection_replica_attachment_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_with_replicas_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_scale_up_with_replicas.go
test/e2e/testsuites/pre_provisioned_dangling_attach_volume_tester.go
test/resources/pod.go
test/scale/azdisk_scale_test.go
test/scale/flags.go
test/scale/scale_tester.go
test/utils/node/node_utils.go
test/utils/pod/pod_utils.go
test/utils/volume/vol_utils.go

/kind test
- Removing unused scale tests.
- Adding a command line flag for the number of volumes to a pod.
- Adding a failover test at scale:
1. Creating the maximum replicas on the first half nodes by cordoning the second half nodes.
2. After all pods are running, cordoning the first half nodes, uncordoning the second half nodes, and wait for all replica attachments are attached.
3. Deleting all the running pods and measuring the failover latency.
Fixes #
```
none
```

[V2] test: add a failover scale test

---

Makefile
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
test/utils/testutil/env_utils.go
test/utils/testutil/test_ops_util.go

/kind test
Add more tests to make our code more robust.
Fixes #
```
none
```

[V2] test: Enable dynamically provisioned volume snapshot test in Windows cluster

---

Makefile
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
test/e2e/testsuites/testsuites.go

/kind test
Enable dynamically provisioned volume snapshot tests in Windows cluster. Previously, the tests are only tested in Linux.
Fixes #
```
none
```

test: Enable dynamically provisioned volume snapshot test in Windows cluster

---

test/e2e/dynamic_provisioning_test.go

/kind test
Enable DynamicallyProvisionedVolumeSnapshotTest in Windows cluster.
Fixes #
```
none
```

[V2] test: Enable test in windows

---

pkg/azdiskschedulerextender/azdiskschedulerextender_metrics.go

[V2] bug: fix in conversion for scheduler extender latency log

---

pkg/azureutils/azure_snapshot_utils.go

/kind cleanup
cleanup: remove unnecessary tp nil check
Fixes #
```
cleanup: remove unnecessary tp nil check
```

cleanup: remove unnecessary tp nil check

---

test/e2e/manifest/cluster-autoscaler.json

/kind test
Adds a cluster configuration for E2E testing with the cluster-autoscaler addon.
```
none
```

[V2] chore: Add template for testing with cluster-autoscaler

---

Makefile
test/const/test_consts.go

/kind test
/kind cleanup
Changes the default location of the artifacts directory to match what it was previously.
Fixes #
```
none
```

[V2] test: fix default artifacts directory

---

pkg/provisioner/crdprovisioner.go

/kind cleanup
On demote or detach, set the `err` variable in `CrdProvisioner.UnpublishVolume` so that the correct result is reported through workflow logging.
Fixes #
```
none
```

[V2] chore: fix CrdProvisioner.UnpublishVolume workflow result reporting

---

pkg/controller/attach_detach.go

/kind bug
When deleting the `AzVolumeAttachment` after a successful detach, use the context without a deadline to perform the delete. This is necessary to prevent orphaning the CRI if the delete comes near the end of the deadline.
This PR also adds error logging for the final status update and delete operations.
Fixes #
```
none
```

[V2] fix: use correct context for delete of AzVolumeAttachment on detach

---

pkg/provisioner/cloudprovisioner.go

/kind bug
* Fixes a bug where cloudprovisioner will not return result through result channel if disk is already attached.
Fixes #
```
none
```

[V2] fix: cloud-provisioner should always report through result channel before returning

---

pkg/azureutils/azure_disk_utils.go
pkg/controller/attach_detach.go
pkg/controller/azvolume.go
pkg/controller/shared_state.go
pkg/provisioner/crdprovisioner.go

/kind cleanup
Reduces workflow log verbosity by increasing the logging level for several informational traces.
Fixes #
```
none
```

[V2] chore: reduce workflow logging verbosity

---

test/e2e/manifest/cluster-autoscaler.json

/kind cleanup
The cluster-autoscaler template successfully deploys but the addon fails to start without `max-nodes`.
```
none
```

[V2] chore: add missing cluster-autoscaler parameter to template

---

test/e2e/manifest/cluster-autoscaler.json

/kind cleanup
Increases the provisioning timeout for the cluster-autoscaler addon as it scales up a VMSS cluster (the default timeout was causing unfavorable retry behavior).
Fixes #
```
none
```

[V2] chore: increase CAS node provisioning timeout

---

pkg/controller/attach_detach.go
pkg/controller/azvolume.go
pkg/controller/common.go
pkg/controller/pv.go
pkg/controller/shared_state.go

/kind bug
Requeues deleted objects for reconciliation when a grace period has been specified. This is also needed to prevent missing a deletion if the API server time skew puts the deletion time in the future relative to the controllers' clock.
Fixes #1371
```
none
```

[V2] fix: requeue reconciliation for deleted objects with grace period

---

test/e2e/pre_provisioning_test.go

/kind test
test: set disk perf in PremiumV2 test
Fixes #
```
none
```

test: set disk perf in PremiumV2 test

---

docs/azure-disk-v2-driver-design/create-volume-csi-workflow.md
docs/azure-disk-v2-driver-design/create-volume-static-provisioning.md
docs/azure-disk-v2-driver-design/delete-volume-csi-workflow.md
docs/azure-disk-v2-driver-design/delete-volume-static-provisioning.md
docs/azure-disk-v2-driver-design/publish-volume-csi-workflow.md
docs/azure-disk-v2-driver-design/replica-creation-workflow.md
docs/azure-disk-v2-driver-design/unpublish-volume-csi-workflow.md
pkg/provisioner/crdprovisioner.go

Adding flow diagrams for the most common driver workflows. 
Helpful links: 
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams
https://mermaid-js.github.io/mermaid/#/
Fixes #
```
none
```

[V2] chore: adding flow chart documentation for V2 driver csi calls

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_external_rg_volume_tester.go

Test: Adding a new test to verify volume and nodes in different resource groups

---

pkg/workflow/workflow.go

/kind cleanup
Fixes the addition of logging details to the workflow after creation so that they appear in subsequent logging output.
Fixes #
```
none
```

[V2] chore: fix addition of details after creation

---

test/e2e/manifest/cluster-autoscaler.json

/kind cleanup
Prevents `kubectl get --watch` from prematurely exiting after its timeout of 30-60min on clusters using the cluster-autoscaler template.
```
none
```

[V2] chore: increase max watch duration on CAS cluster

---

go.mod
pkg/controller/pv.go

/kind bug
Fixes #1617 
```
none
```

[V2] fix: update PV controller's Recover function to log the error 

---

pkg/azuredisk/azuredisk_v2.go
pkg/azureutils/azure_disk_utils.go
pkg/controller/common_test.go
pkg/controller/node.go
pkg/controller/node_test.go

/kind bug
1. delete orphaned azdrivernode when the cluster scales in.
2. change the way to return error in `Recover` function.
3. fix a typo in `azuredisk.go`
#1590 #1617
Fixes #
```
none
```

[V2] fix: delete orphaned azdrivernode and update error logs in Recover function

---

pkg/optimization/azure_skus_map.go

/kind bug
Add Standard_E64ds_v5 machines details in azure_skus_map.go
With pieces of info taken from https://learn.microsoft.com/en-us/azure/virtual-machines/edv5-edsv5-series#edsv5-series 
N/A
- [ x] uses [conventional commit messages](https://www.conventionalcommits.org/)
First commit / PR on K8s project(s)
```
none
```

fix: Add missing machine in SKU listings

---

docs/azure-disk-v2-driver-design/replica-creation-workflow.md

node_availability.go  is refactored to node.go
/kind cleanup
Fixes #
```
none
```

Update node_availability.go to node.go

---

pkg/controller/azvolume.go

[V2] perf: changed to use channel to communicate when delete azvolume

---

pkg/controller/azvolume.go
pkg/controller/replica.go
pkg/provisioner/crdprovisioner.go
pkg/watcher/conditionwatcher.go

/kind cleanup
`ConditionWatcher.NewConditionWaiter` does not fail, so the error return is unnecessary. Remove it to simplify usage.
Fixes #
```
none
```

[V2] chore: remove unneeded error return from NewConditionWaiter

---

go.mod
go.sum
vendor/golang.org/x/net/http2/hpack/encode.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/sys/windows/syscall_windows.go
vendor/golang.org/x/sys/windows/zsyscall_windows.go
vendor/modules.txt

/kind bug
fix: CVE-2022-41717
Fixes #
<details>
```
go get -u golang.org/x/net
go mod tidy
go mod vendor
```
</details>
```
fix: CVE-2022-41717
```

fix: CVE-2022-41717

---

pkg/azuredisk/azuredisk_v2.go
pkg/controller/attach_detach.go
pkg/controller/attach_detach_test.go
pkg/controller/azvolume.go
pkg/controller/azvolume_test.go
pkg/controller/node.go
pkg/controller/node_test.go

/kind bug
Fixes #1648
```
none
```

[V2] fix: make recover annotation unique per recovery

---

test/e2e/manifest/migration-windows.json
test/e2e/manifest/migration.json
test/e2e/manifest/multi-az.json
test/e2e/manifest/single-az.json

Reverts kubernetes-sigs/azuredisk-csi-driver#1668

Revert "fix e2e: disable podSecurity"

---

pkg/controller/shared_state.go
pkg/provisioner/crdprovisioner.go

/kind bug
1. update uninstall path in `crdProvisioner.DeleteVolume`
2. remove a non-used parameter from `shared_stated.getNodesForReplica`
3. fix a log typo
Fixes #1664
```
none
```

[V2] Fix: update uninstall path in crdProvisioner.DeleteVolume

---

go.mod
pkg/azuredisk/controllerserver_test.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
test/e2e/testsuites/testsuites.go
test/utils/azure/azure_helpers.go

/kind cleanup
Use k8s utils pointer instead of Azure autorest/to
- to.FooPtr becomes pointer.Foo
- to.Foo becomes pointer.FooDeref with an appropriate default
- to.StringSlicePtr becomes &
This is related to https://github.com/kubernetes/kubernetes/issues/112431 (but doesn’t fix it).
```
none
```

cleanup: Use k8s utils pointer instead of Azure autorest/to

---

pkg/azuredisk/controllerserver.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
pkg/controller/shared_state.go
pkg/provisioner/cloudprovisioner.go

/kind bug
* Make sure `AzVolume.Status` is updated when necessary for AzVolume recovery.
** Failure to do so causes an unnecessary call to `cloudprovisioner.CreateVolume`
* Make sure unsupported fields are filtered from `PV.Spec.CSI.VolumeAttributes` for populating `AzVolume.Spec.Parameters` .
Fixes #
```
none
```

[V2] fix: azvolume recovery bug fix - status update, parameter parsing

---

pkg/controller/node.go
pkg/controller/shared_state.go

/kind bug
When we scale out a new node, the instance type label isn't there as it's just created so the node won't be added to `availableAttachmentsMap`. This PR update the logic in predicate Update function to trigger reconciliation when the label is added.
Fixes #
```
none
```

[V2]fix: update predicate function of node controller

---

pkg/controller/common.go
pkg/controller/shared_state.go

/kind bug
* The current uninstallation logic has conflicts with changes introduced in https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1553.
* This PR addresses this issue and makes some refactoring to cleanup logic.
Fixes #
```
none
```

[V2] fix: make uninstallation compatible with backload DELETE change

---

test/external-e2e/manifest/testdriver.yaml

/kind test
test: add external stress e2e tests
Fixes #
```
test: add external stress e2e tests
```

test: add external stress e2e tests

---

pkg/controller/replica.go

/kind bug
When the driver is uninstalling and the detachment failed, we should delete the CRI and return. No need to update the CRI state.
Fixes #
```
none
```

[V2] fix: update uninstallation path in replica.go

---

pkg/azuredisk/azuredisk_v2.go
pkg/controller/shared_state.go

/kind bug
Because the update delay of cache client, some deleted CRIs still can be found, and the driver gets wrong data to process. For example, when a replica attachment failed and get deleted to restart the attach request, if the driver still found the deleted CRI from cache, we will get a smaller number of replica attachments than that we actually need to create. 
Fixes #
```
none
```

[V2] fix: only count replica attachments w/t deletion timestamp from cache client

---

docs/csi-debug.md
hack/AzureDiskCSIDriver.psd1
hack/AzureDiskCSIDriver.psm1
hack/boilerplate/boilerplate.psd1.txt
hack/boilerplate/boilerplate.psm1.txt

/kind feature
Add the `AzureDiskCSIDriver` PowerShell module to ease retrieval of CSI log messages and analysis of CSI operations.
Fixes #
```
none
```

[V2] feat: add PowerShell module for log/operation analysis

---

pkg/controller/shared_state.go

/kind bug
Fix a typo in `getQualifiedNodesForPodAffinityTerm` method that should have removed non-candidateNodes from replicaNodes so we can get correct filtered Nodes for creating replica attachments.
Fixes #
```
none
```

[V2] fix: update logic to get correct nodes for creating replica attachments

---

pkg/azurediskplugin/Dockerfile

/kind bug
fix: switch base image to fix CVEs
Fixes #
```
fix: switch base image to fix CVEs
```

fix: switch base image to fix CVEs

---

deploy/csi-azuredisk-driver.yaml
deploy/v1.21.0/csi-azuredisk-driver.yaml
deploy/v1.22.0/csi-azuredisk-driver.yaml
deploy/v1.23.0/csi-azuredisk-driver.yaml
deploy/v1.24.0/csi-azuredisk-driver.yaml
deploy/v1.25.0/csi-azuredisk-driver.yaml
deploy/v1.26.0/csi-azuredisk-driver.yaml
deploy/v1.26.1/csi-azuredisk-driver.yaml

/kind bug
fix: incorrect driver version in CSIDriver
Fixes #
```
fix: incorrect driver version in CSIDriver
```

fix: incorrect driver version in CSIDriver

---

pkg/controller/azvolume.go
pkg/controller/shared_state.go

/kind cleanup
Since `getVolumeCapabilityFromPv `is only used in `shared_state.go` and not used in `azvolume.go`, move it to `shared_state.go`.
Fixes #
```
none
```

[V2] refactor: relocate getVolumeCapabilityFromPv

---

docs/driver-parameters.md
pkg/azureconstants/azure_constants.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
test/e2e/driver/azuredisk_driver.go
test/e2e/driver/driver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go
test/e2e/testsuites/specs.go

/kind feature
feat: add dataAccessAuthMode parameter to snapshot storage class
Fixes #1702
```
feat: add dataAccessAuthMode parameter to snapshot storage class
```

feat: add dataAccessAuthMode parameter to snapshot storage class

---

Makefile

fix: buildx issue with provenance disabled
Fixes #
```
none
```

fix: buildx issue with provenance disabled

---

test/e2e/manifest/workload.json

/kind feature
creating workload manifest to use for workload tests

[V2] feat: creating workload manifest to use for workload tests

---

go.mod
go.sum
vendor/golang.org/x/net/html/parse.go
vendor/golang.org/x/net/html/token.go
vendor/golang.org/x/net/http2/flow.go
vendor/golang.org/x/net/http2/frame.go
vendor/golang.org/x/net/http2/hpack/hpack.go
vendor/golang.org/x/net/http2/server.go
vendor/golang.org/x/net/http2/transport.go
vendor/golang.org/x/net/trace/histogram.go
vendor/modules.txt

/kind bug
fix: CVE-2022-41723
Fixes #
```
fix: CVE-2022-41723
```

fix: CVE-2022-41723

---

test/e2e/manifest/scale-test.json

/kind test
matching scale test manifest with aurora

[V2] fix: matching scale test manifest with aurora

---

hack/get-logs.sh

/kind cleanup
Fixes getting logs from pods in a namespace other than `kube-system`.
Fixes #
```
none
```

[V2] chore: fix getting pods from alternate namespace

---

.github/workflows/static.yaml

tes: fix golint action failure
related to https://github.com/golangci/golangci-lint-action/issues/640
Fixes #
```
none
```

tes: fix golint action failure

---

.github/workflows/static.yaml

/kind cleanup
This is a cherry pick of #1748 
Fixes #
```
none
```

test: fix golint action failure

---

pkg/controller/attach_detach.go

/kind cleanup
Fixes #
```
none
```

[V2] refactor: use function AppendToUpdateCRIFunc

---

pkg/controller/common_test.go

/kind cleanup
"k8s.io/apimachinery/pkg/api/errors" has been imported twice. Let's delete it.
Fixes #
```
none
```

[V2] style: delete duplicated import of k8s.io/apimachinery/pkg/api/errors

---

docs/design-v2.md
pkg/azureutils/azure_disk_utils.go

/kind design
Limits the max value of max shares to a common value as per PRD discussions.
```
none
```

[V2] chore: limit max shares for all disks

---

pkg/azureutils/azure_disk_utils_test.go
test/upgrade/flags.go
test/utils/node/node_utils.go

/kind cleanup
1, Check for spelling errors fails: https://github.com/kubernetes-sigs/azuredisk-csi-driver/actions/runs/4367559819/jobs/7639028448
2, Delete duplicated imports.
Fixes #
```
none
```

[V2] style: clean up typo and duplicated imports

---

test/external-e2e/manifest/testdriver.yaml

/kind test
test: enable online expansion external test
Fixes #
```
none
```

test: enable online expansion external test

---

.github/workflows/codeql-analysis.yml
README.md

doc: add accessModes doc
Fixes #1763
```
none
```

doc: add accessModes doc

---

pkg/azureutils/azure_disk_utils_test.go

/kind test
Fixes #
```
none
```

[V2] chore: add parse max shares unit test

---

pkg/controller/pod.go

/kind bug
Without this fix, replica azVolumeAttachments may be created before its primary azVolumeAttachments. When the disk resource is being used by creating replica azVolumeAttachments, it may hold back the creation of a running pod.
Fixes #
```
none
```

[V2] fix: only create replica AzVolumeAttachments for the running pod when recovering pods

---

pkg/azureconstants/azure_constants.go

Fixes #
https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/1765
```
none
```

[V2] docs: add docs for different annotations.

---

Makefile

/kind cleanup
cleanup: remove 20H2 windows image build
Windows SAC releases (2004, 20H2) have been out-of-support for a while now so we shouldn't build contianer images for those platforms
Fixes #
```
none
```

cleanup: remove 20H2 windows image build

---

pkg/azureutils/azure_disk_utils.go
pkg/controller/attach_detach.go
pkg/controller/common.go
pkg/controller/common_test.go
pkg/controller/shared_state.go
pkg/controller/shared_state_test.go

/kind bug
In addition to fix the issue mentioned below, this PR also add a new unit test and updates an error from the existing one:
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/7c05b95d1f7c5d7927d4e2a4e12b4264152ba216/pkg/controller/shared_state_test.go#L1273 the test case is "when node is in cache", but it returns "NotFound" error for `GET` method.
Fixes #1780
```
none
```

[V2] fix: recover nodes with correct remaining capacity

---

hack/azure-cluster-up.sh

/kind cleanup
Since `aks-engine` is deprecated, the PR modifies the `azure-cluster-up.sh` to build out a cluster using `az aks` CLI.
Fixes #
```
none
```

[V2] chore: use aks cli instead of aks-engine

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind bug
fix: PremiumV2_LRS caching mode issue
https://learn.microsoft.com/en-us/azure/virtual-machines/disks-types#differences-between-premium-ssd-and-premium-ssd-v2
Unlike Premium SSDs, Premium SSD v2 doesn't have dedicated sizes. You can set a Premium SSD v2 to any supported size you prefer, and make granular adjustments to the performance without downtime. Premium SSD v2 doesn't support host caching but, benefits significantly from lower latency which addresses some of the same core problems host caching addresses. The ability to adjust IOPS, throughput, and size at any time also means you can avoid the maintenance overhead of having to stripe disks to meet your needs.
Fixes #1770 …

fix: PremiumV2_LRS caching mode issue

---

hack/azure-cluster-up.sh

/kind cleanup
Fixes the AKS preview extension update command.
Fixes #
```
none
```

[V2] chore: fix AKS preview extension update

---

pkg/controller/attach_detach.go

/kind bug
Fixes a panic on failure to attach a disk.
Fixes #
```
none
```

fix: fix attach failure panic

---

test/podFailover/controller/cmd/main.go

/kind bug
- pod readiness will error if pod hasn't been created yet
- checking for pod creation before checking readiness

[V2] fix: Fix pod failover ready

---

pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_v2.go
pkg/azureutils/azure_disk_utils_test.go
pkg/azureutils/fake_iohandler.go
pkg/azureutils/fake_iohandler_test.go
pkg/azureutils/osiohandler.go
pkg/mounter/fake_safe_mounter_test.go
pkg/tool/gen-disk-skus-map.go
test/utils/credentials/credentials.go
test/utils/credentials/credentials_test.go

/kind cleanup
Replace the deprecated ioutil method, Because they are no longer recommended in go version 1.16 or 1.17
Fixes #
```
none
```

cleanup: replace deprecated ioutil method

---

pkg/controller/replica.go

/kind bug
Fixes #
```
none
```

[V2] fix: update handleReplicaDelete function in replica controller

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azureutils/azure_disk_utils.go
test/e2e/dynamic_provisioning_test.go

/kind cleanup
cleanup: combine waitForSnapshotCopy func
Fixes #
```
none
```

cleanup: combine waitForSnapshotCopy func

---

docs/driver-parameters.md
pkg/azureconstants/azure_constants.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add publicNetworkAccess parameter in storage class
Fixes #1768
```
feat: add publicNetworkAccess parameter in storage class
```

feat: add publicNetworkAccess parameter in storage class

---

test/e2e/dynamic_provisioning_test.go

test: fix snapshot test failure
Fixes #
```
none
```

[release-1.26] test: fix snapshot test failure

---

pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver_test.go

/kind test
test: move ut for waitForSnapshotCopy to azuredisk_test.go
Fixes #1840 
```
none
```

test: move ut for waitForSnapshotCopy to azuredisk_test.go

---

.github/dependabot.yaml

/kind test
Add dependabot job for dockerfiles
Fixes #
```
none
```

Build: Add dependabot job for dockerfiles

---

docs/driver-parameters.md
pkg/azureconstants/azure_constants.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azureutils/azure_disk_utils.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add enablePerformancePlus in storage class
Fixes #
```
feat: add enablePerformancePlus in storage class
```

feat: add enablePerformancePlus in storage class

---

Makefile
pkg/azureutils/azure_disk_utils.go
pkg/os/disk/disk.go

/kind cleanup
cleanup: reduce host process disk partition logs
Fixes #
```
none
```

cleanup: reduce host process disk partition logs

---

pkg/controller/common.go
pkg/controller/node.go
pkg/controller/replica_test.go
pkg/controller/shared_state.go

/kind cleanup
Since `azdrivernode` and `node_availability` controllers have been combined into `node` controller (PR #1612), this PR updates the operation requester accordingly.
Fixes #
```
none
```

[V2] chore: cleanup operation requester

---

test/scale/scale_tester.go
test/utils/volume/vol_utils.go

/kind test
This PR updates scale tester with two issues:
1. we want to check if replica azvolumeattachments are over issued during scale-out process, which shouldn't happen under current design.
2. correct that the scale-in test isn't completed until all azvolumeattachments are deleted.  
Fixes #
```
none
```

[V2] chore: update scale tester

---

pkg/controller/common.go
pkg/controller/replica.go
pkg/controller/replica_test.go

/kind bug
Once detachment of an azvolumeattachment failed, we observed that more than one `handleReplicaDelete` and `manageReplicas` were callled in separated goroutines. We don't expect to overly create the CRI with the reasons that could make attach workload heavier or take a risk that more than expected number of CRI get attached.
This happened because all update events will trigger reconciler of replica controller. For a detaching operation, adding detach request annotation, update state to Detaching, DetachmentFailed, and ForceDetachPending all trigger the reconciler to call `handleReplicaDelete` in a goroutine. We want to ensure only one call during a detaching cycle.
Fixes # …

[V2] fix: update predicate of replica controller to prevent over creating replica AzVolumeAttachment

---

docs/driver-parameters.md
pkg/azureconstants/azure_constants.go
pkg/azuredisk/controllerserver.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add attachDiskInitialDelay parameter in storage class
Fixes #
```
feat: add attachDiskInitialDelay parameter in storage class
```

[release-1.27] feat: add attachDiskInitialDelay parameter in storage class

---

docs/driver-parameters.md
pkg/azureconstants/azure_constants.go
pkg/azuredisk/controllerserver.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add attachDiskInitialDelay parameter in storage class
Fixes #
```
feat: add attachDiskInitialDelay parameter in storage class
```

[release-1.26] feat: add attachDiskInitialDelay parameter in storage class

---

pkg/azuredisk/nodeserver.go

/kind bug
fix: missing log when IMDS is not available on windows node
Fixes #
```
fix: missing log when IMDS is not available on windows node
```

fix: missing log when IMDS is not available on windows node

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/mockpersistentvolume/interface.go
test/e2e/testsuites/testsuites.go

/kind cleanup
pkg is being imported more than once
Fixes #
```
none
```

chore: pkg imported more than once

---

deploy/csi-azuredisk-node-windows-hostprocess.yaml

/kind cleanup
cleanup: use InClusterConfig by default on Windows node
Fixes #
```
none
```

cleanup: use InClusterConfig by default on Windows node

---

pkg/controller/common.go
pkg/controller/shared_state.go

/kind bug
Fixes a segfault due to a race condition leading to an empty queue on entry to the `addToOperationQueue` goroutine.
Fixes #
```
none
```

[V2] fix: fix segfault due to empty operation queue

---

pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/disk/disk.go
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go

/kind bug
fix: ensure that readonly is disabled when disks are brought online
This PR could fix the cloned volume not recognized on the same Windows node (when source volume is also mounted on the same node)
Fixes #
```
fix: ensure that readonly is disabled when disks are brought online
```

fix: cloned volume could not be recognized on Windows node when source volume is mounted on the same node

---

pkg/azuredisk/azure_dd_max_disk_count.go

/kind feature
chore: update max data disk count table
Fixes #
```
none
```

chore: update max data disk count table

---

pkg/azureutils/azure_disk_utils.go
pkg/controller/attach_detach.go

/kind bug
Fixes error handling of `AzVolumeAttachment` attach status updates and improves resiliency to transient network connectivity issues.
Fixes #
```
none
```

[V2] fix: fix error handling of attach status updates

---

test/podFailover/controller/cmd/main.go

/kind test
adding logs when pod failover test cordons and deferring uncordon

[V2] chore: adding logs when pod failover test cordons and deferring uncordon

---

docs/driver-parameters.md

While testing Azure driver in OpenShift we've encountered authorizations issues while using documented permissions: https://github.com/openshift/cluster-storage-operator/pull/388
It might be worth evaluating and documenting those if correct.
Fixes #
```
none
```

doc: add permissions for CSI driver controller

---

pkg/azuredisk/nodeserver_test.go
pkg/os/volume/volume.go

/kind bug
fix: use env var in powershell cmdlet
Fixes #
```
fix: use env var in powershell cmdlet
```

fix: use env var in powershell cmdlet

---

pkg/azuredisk/nodeserver_test.go
pkg/os/disk/disk.go
pkg/os/filesystem/filesystem.go
pkg/os/volume/volume.go

/kind cleanup
cleanup: windows mount code
Fixes #
```
none
```

cleanup: windows mount code

---

hack/azure-cluster-up.sh
pkg/apis/azuredisk/v1beta2/types.go
pkg/azureconstants/azure_constants.go
pkg/azuredisk/azuredisk.go
pkg/azurediskplugin/main.go
pkg/controller/common.go
pkg/controller/common_test.go
pkg/controller/shared_state.go
pkg/controller/shared_state_test.go

/kind feature
Replica attachment failures may last longer than the life-span of an event,
so this PR introduces a lightweight event refresher
to ensure that these failures remain visible for as long as they still apply.
Fixes #
```
none
```

[V2] feat: persist replica attachment failures

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind cleanup
cleanup: refine Volume capabilities not supported error
This PR makes the error message(`Volume capabilities not supported`) easier to understand
Fixes #
```
none
```

cleanup: refine Volume capabilities not supported error

---

pkg/azuredisk/controllerserver.go

/kind cleanup
chore: refine create-volume metrics
Fixes #
```
none
```

chore: refine create-volume metrics

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/fake_azuredisk.go
pkg/azurediskplugin/main.go

/kind bug
fix: Ultra and PremiumV2 disk snapshot delay issue
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/1953
Fixes #
```
fix: Ultra and PremiumV2 disk snapshot delay issue
```

[release-1.28] fix: Ultra and PremiumV2 disk snapshot delay issue

---

.github/workflows/codespell.yml
deploy/example/azure.json

doc: fix code spelling errors
Fixes #
```
none
```

[release-1.27] doc: fix code spelling errors

---

.github/workflows/codespell.yml
deploy/example/azure.json

doc: fix code spelling errors
Fixes #
```
none
```

[release-1.28] doc: fix code spelling errors

---

.github/workflows/codespell.yml
deploy/example/azure.json

doc: fix code spelling errors
Fixes #
```
none
```

[release-1.29] doc: fix code spelling errors

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_snapshot_tester.go

/kind test
test: skip anti-affinity in hpc deployment test since conflicting UUID issue is fixed on HPC deployment mode
Fixes #
```
none
```

test: skip anti-affinity in hpc deployment test

---

deploy/example/nginx-pod-azuredisk.yaml
deploy/example/nginx-pod-ephemeral.yaml
deploy/example/pv-azuredisk-csi.yaml
deploy/example/statefulset-nonroot.yaml
deploy/example/statefulset-nozone.yaml
deploy/example/statefulset.yaml

doc: fix readOnly setting doc
- following csi.readOnly is not supported in CSI driver
```
csi:
driver: file.csi.azure.com
readOnly: false
```
Fixes #
```
none
```

doc: fix readOnly setting doc

---

deploy/example/storageclass-azuredisk-csi-allowed-topology.yaml
deploy/example/storageclass-azuredisk-csi.yaml

doc: recommend available skuNames
Fixes #
```
none
```

doc: recommend available skuNames

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

test: fix multi-zone test failure on capz multi-zone cluster
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2098
Fixes #
```
none
```

[release-1.27] test: fix multi-zone test failure on capz multi-zone cluster

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

test: fix multi-zone test failure on capz multi-zone cluster
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2098
Fixes #
```
none
```

[release-1.26] test: fix multi-zone test failure on capz multi-zone cluster

---

pkg/azurediskplugin/Dockerfile
test/e2e/dynamic_provisioning_test.go

/kind feature
chore: upgrade base image to alpine 3.18.4
Fixes #2026
```
none
```

chore: upgrade base image to alpine 3.18.4

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

/kind cleanup
test: remove zone restrictions in e2e tests
Fixes #
```
none
```

test: remove zone restrictions in e2e tests

---

test/external-e2e/run.sh

/kind test
test: upgrade to external 1.27 e2e tests
Fixes #
```
none
```

test: upgrade to external 1.27 e2e tests

---

.github/workflows/static.yaml
.golangci.yml

/kind cleanup
Chores: put lint args into golangci-lint config file
Fixes #
golint is deprecated and replaced by revive.
```
none
```

Chores: put lint args into golangci-lint config file

---

.github/workflows/static.yaml
.golangci.yml
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/identityserver.go
pkg/azuredisk/nodeserver.go
pkg/azurediskplugin/main.go
pkg/azureutils/fake_iohandler.go
pkg/csi-common/server_test.go
pkg/mounter/fake_safe_mounter.go
pkg/mounter/safe_mounter_unix.go
pkg/optimization/azure_skus_map.go
pkg/optimization/skus_test.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
test/e2e/testsuites/specs.go
test/utils/azure/azure_helpers.go

/kind test
This is a cherry-pick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2073
Fixes #
```
none
```

[release-1.27] test: upgrade golangci/golangci-lint-action to v1.54

---

.github/workflows/static.yaml
.golangci.yml
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/identityserver.go
pkg/azuredisk/nodeserver.go
pkg/azurediskplugin/main.go
pkg/azureutils/fake_iohandler.go
pkg/csi-common/server_test.go
pkg/mounter/fake_safe_mounter.go
pkg/mounter/safe_mounter_unix.go
pkg/optimization/azure_skus_map.go
pkg/optimization/skus_test.go
pkg/os/filesystem/filesystem.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
test/e2e/testsuites/specs.go
test/utils/azure/azure_helpers.go

/kind test
This is a cherry-pick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2073
Fixes #
```
none
```

[release-1.28] test: upgrade golangci/golangci-lint-action to v1.54

---

.github/workflows/static.yaml
.golangci.yml
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/identityserver.go
pkg/azuredisk/nodeserver.go
pkg/azurediskplugin/main.go
pkg/azureutils/fake_iohandler.go
pkg/csi-common/server_test.go
pkg/mounter/fake_safe_mounter.go
pkg/mounter/safe_mounter_unix.go
pkg/optimization/azure_skus_map.go
pkg/optimization/skus_test.go
pkg/os/filesystem/filesystem.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
test/e2e/testsuites/specs.go
test/utils/azure/azure_helpers.go

/kind test
This is a cherry-pick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2073
Fixes #
```
none
```

[release-1.29] test: upgrade golangci/golangci-lint-action to v1.54

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/azuredisk_option_test.go
pkg/azuredisk/azuredisk_v2.go
pkg/azurediskplugin/main.go

/kind cleanup
Refactor: move flags definition to config functions
move initialization code to NewDriver func
Fixes #
nodeid check is moved to DriverCore factory method. 
expose metrics function is moved to DriverCore.Run()
```
none
```

Refactor: move flags definition to config functions

---

pkg/azuredisk/nodeserver.go

/kind cleanup
chore: adjust logging in node daemonset since perf optimization is disabled by default
Fixes #
```
none
```

chore: adjust logging in node daemonset

---

go.mod
hack/verify-gomod.sh
vendor/modules.txt

/kind cleanup
cleanup: fix k8s.io/endpointslice dependency
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2014
Fixes #
```
none
```

cleanup: fix k8s.io/endpointslice dependency

---

pkg/azuredisk/controllerserver.go

/kind feature
feat: support more ZRS skus
In the future, more ZRS skus would be provided, this PR makes sure that new ZRS skus could be supported in the driver without code change.
Fixes #
```
feat: support more ZRS skus
```

feat: support more ZRS skus

---

pkg/azuredisk/controllerserver.go

/kind feature
feat: support more ZRS skus
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2171
Fixes #
```
none
```

[release-1.29] feat: support more ZRS skus in volume affinity

---

pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/nodeserver.go
pkg/azurediskplugin/WindowsHostProcess.Dockerfile
pkg/csi-common/driver.go

/kind feature
feat: introduce reserved-data-disk-slot-num for improved data disk volume management
Fixes #2169
```
feat: introduce reserved-data-disk-slot-num for improved data disk volume management
```

feat: introduce reserved-data-disk-slot-num for improved data disk volume management

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/nodeserver.go
pkg/azurediskplugin/main.go
pkg/csi-common/driver.go

/kind feature
feat: introduce reserved-data-disk-slot-num for improved data disk volume management
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2173
Fixes #
```
none
```

[release-1.29] feat: introduce reserved-data-disk-slot-num for improved data disk volume management

---

.github/workflows/linux.yml

test: fix goveralls
Fixes #
```
none
```

test: fix goveralls

---

pkg/azuredisk/azuredisk_option.go

/kind bug
fix: enable check-disk-lun-collision during disk attach by default
Fixes #
```
fix: enable check-disk-lun-collision during disk attach by default
```

fix: enable check-disk-lun-collision during disk attach by default

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/fake_azuredisk.go
test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go

/kind bug
fix: copy volume error in cross zone scenario
```
I0313 13:57:56.051087       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I0313 13:57:56.051117       1 utils.go:106] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.disk.csi.azure.com/zone":"eastus2euap-1","topology.kubernetes.io/zone":"eastus2euap-1"}}],"requisite":[{"segments":{"topology.disk.csi.azure.com/zone":"eastus2euap-1","topology.kubernetes.io/zone":"eastus2euap-1"}}]},"capacity_range":{"required_bytes":10737418240},"name":"pvc-971e9fdb-496e-4426-9e05-9f895786bc24","parameters":{"csi.storage.k8s.io/pv/name":"pvc-971e9fdb-496e-4426-9e05-9f895786bc24","csi.storage.k8s.io/pvc/name":"pvc-azuredisk-cloning","csi …
```

fix: copy volume error in cross zone scenario

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/fake_azuredisk.go

/kind bug
fix: refine check disk lun collision logic
as long as get volume attachments takes longer than 1s, this PR would skip checking disk lun collision logic
Fixes #
```
fix: refine check disk lun collision logic
```

fix: refine check disk lun collision logic

---

pkg/azurediskplugin/main.go

/kind bug
fix: enable check-disk-lun-collision during disk attach by default
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2208
Fixes #
```
fix: enable check-disk-lun-collision during disk attach by default
```

[release-1.29] fix: enable check-disk-lun-collision during disk attach by default

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/fake_azuredisk.go

/kind bug
fix: refine check disk lun collision logic
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2239
as long as get volume attachments takes longer than 1s, this PR would skip checking disk lun collision logic
Fixes #
```
fix: refine check disk lun collision logic
```

[release-1.29] fix: refine check disk lun collision logic

---

pkg/azuredisk/controllerserver.go

/kind bug
fix: stop attaching disk when get disk lun failed
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2260
Fixes #
```
fix: stop attaching disk when get disk lun failed
```

[release-1.29] fix: stop attaching disk when get disk lun failed

---

pkg/os/volume/volume.go

/kind cleanup
cleanup: remove unused windows code
Fixes #
```
none
```

cleanup: remove unused windows code

---

pkg/os/filesystem/filesystem.go

/kind cleanup
cleanup: remove unused code
Fixes #
```
none
```

cleanup: remove unused code

---

pkg/azuredisk/azuredisk.go

/kind bug
fix: use alternative driver name in used lun check
Fixes #
```
fix: use alternative driver name in used lun check
```

fix: use alternative driver name in used lun check

---

.github/workflows/codespell.yml
.github/workflows/trivy.yaml

test: fix codespell error
Fixes #
```
none
```

test: fix codespell error

---

pkg/azureutils/azure_disk_utils.go

/kind cleanup
chore: adjust powershell cmd log level
Fixes #
```
none
```

chore: adjust powershell cmd log level

---

pkg/azureconstants/azure_constants.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azureutils/azure_disk_utils.go
pkg/util/util.go
pkg/util/util_test.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go

/kind feature
feat: add tag value delimieter parameter and allow tag values containing commas and equal sign
referring to issue https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/2323
Fixes #
```
none
```

feat: add tagValueDelimiter parameter

---

pkg/azureconstants/azure_constants.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azureutils/azure_disk_utils.go
pkg/util/util.go
pkg/util/util_test.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go

/kind feature
[release-1.29] feat: add tagValueDelimiter parameter
cherry-pick https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2388
Fixes #
```
none
```

[release-1.29] feat: add tagValueDelimiter parameter

---

deploy/example/windows/deployment.yaml
deploy/example/windows/statefulset.yaml
hack/verify-examples.sh

/kind test
test: change default windows tests to use ltsc2022 image
Fixes #
```
none
```

test: change default windows tests to use ltsc2022 image

---

pkg/azuredisk/azuredisk.go

/kind bug
fix: only enable removeNotReadyTaint on driver node daemonset
Fixes #
```
fix: only enable removeNotReadyTaint on node daemonset
```

fix: only enable removeNotReadyTaint on driver node daemonset

---

pkg/azuredisk/azuredisk.go

/kind bug
fix: checkDiskLun throttling issue
When get VolumeAttachments costing long time, this PR would skip checking the disk lun collsion to avoid slow disk attach.
Fixes #
```
fix: checkDiskLun throttling issue
```

fix: checkDiskLun throttling issue

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azure_managedDiskController.go
pkg/azuredisk/azure_managedDiskController_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver_test.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
test/e2e/testsuites/testsuites.go

chore: Replace deprecated "k8s.io/utils/pointer" with "k8s.io/utils/ptr"

---

.github/workflows/static.yaml
pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azure_managedDiskController.go
pkg/azuredisk/azure_managedDiskController_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go
pkg/csi-common/utils.go
pkg/csi-common/utils_test.go
pkg/os/volume/volume.go
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go

cleanup: upgrade golint version and fix golint errors

---

pkg/azurediskplugin/Dockerfile

/kind feature
chore: upgrade to base image alpine 3.20.2
Fixes #
```
none
```

chore: upgrade to base image alpine 3.20.2

---

test/e2e/dynamic_provisioning_test.go

test: skip "should create a volume azuredisk with tag" test on Windows
Fixes #
```
none
```

test: skip "should create a volume azuredisk with tag" test on Windows

---

.github/workflows/trivy.yaml
go.mod

chore: upgrade golang version
```
azurefileplugin (gobinary)
==========================
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬─────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                            Title                            │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼─────────────────────────────────────────────────────────────┤
│ stdlib  │ CVE-2024-[34](https://github.com/kubernetes-sigs/azurefile-csi-driver/actions/runs/10708260683/job/298480 …
```

chore: upgrade golang version

---

pkg/mounter/safe_mounter_host_process_windows.go

/kind bug
fix: resize failure when cloning a volume with bigger size on Windows
Fixes #
<details>
```
I0911 03:33:45.082561    8340 utils.go:105] GRPC call: /csi.v1.Node/NodeStageVolume
I0911 03:33:45.082588    8340 utils.go:106] GRPC request: {"publish_context":{"LUN":"3"},"staging_target_path":"\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\disk.csi.azure.com\\72bb2b07b6028371cea50fb631344dc9113f0846681814572edb765f698195da\\globalmount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":7}},"volume_context":{"csi.storage.k8s.io/pv/name":"pvc-3842e94f-15b1-41fa-80aa-407b03b6f624","csi.storage.k8s.io/pvc/name":"p …
```

fix: resize failure when cloning a volume with bigger size on Windows

---

.github/workflows/trivy.yaml
go.mod
vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt

cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2498
chore: upgrade golang version
```
azurefileplugin (gobinary)
==========================
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬─────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                            Title                            │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼─────────────────────────────────────────────────────────────┤
│ stdlib  │ …
```

[release-1.30] chore: upgrade golang version

---

.github/workflows/trivy.yaml
go.mod
vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt

cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2498
chore: upgrade golang version
```
azurefileplugin (gobinary)
==========================
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬─────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                            Title                            │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼─────────────────────────────────────────────────────────────┤
│ stdlib  │ …
```

[release-1.28] chore: upgrade golang version

---

.github/workflows/trivy.yaml
go.mod
vendor/k8s.io/kubernetes/test/e2e/framework/testfiles/testdata/a/foo.txt

cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2498
chore: upgrade golang version
```
azurefileplugin (gobinary)
==========================
Total: 3 (UNKNOWN: 0, LOW: 0, MEDIUM: 2, HIGH: 1, CRITICAL: 0)
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬─────────────────────────────────────────────────────────────┐
│ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                            Title                            │
├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼─────────────────────────────────────────────────────────────┤
│ stdlib  │ …
```

[release-1.29] chore: upgrade golang version

---

.github/workflows/static.yaml
.golangci.yml
hack/verify-golint.sh

chore: update static.yaml to avoid .golangci.yml dependency

---

pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/fake_azuredisk_v2.go

/kind test
test: run windows ut with host process enabled
Fixes #
```
none
```

test: run windows ut with host process enabled

---

pkg/azureconstants/azure_constants.go
pkg/azuredisk/azure_managedDiskController.go
pkg/azuredisk/controllerserver.go

/kind feature
feat: add pre-defined tags in snapshot creation, this PR would add following tags in snapshot creation:
- `k8s-azure-created-by`: `kubernetes-azure-dd`
- `kubernetes.io-created-for-snapshot-namespace`: `namespace`
- `kubernetes.io-created-for-snapshot-name`: `name`
- `source_volume_id`:`/subscriptions/xxx/resourceGroups/capz-kiobac/providers/Microsoft.Compute/disks/xxx`
Fixes https://github.com/Azure/AKS/issues/4550
```
feat: add pre-defined tags in snapshot creation
```

feat: add pre-defined tags in snapshot creation

---

pkg/azureconstants/azure_constants.go
pkg/azuredisk/azure_managedDiskController.go
pkg/azuredisk/controllerserver.go

/kind feature
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2561
feat: add pre-defined tags in snapshot creation, this PR would add following tags in snapshot creation:
- `k8s-azure-created-by`: `kubernetes-azure-dd`
- `kubernetes.io-created-for-snapshot-namespace`: `namespace`
- `kubernetes.io-created-for-snapshot-name`: `name`
- `source_volume_id`:`/subscriptions/xxx/resourceGroups/capz-kiobac/providers/Microsoft.Compute/disks/xxx`
Fixes #
```
feat: add pre-defined tags in snapshot creation
```

[release-1.30] feat: add pre-defined tags in snapshot creation

---

charts/index.yaml
deploy/example/cloning/nginx-pod-restored-cloning.yaml
deploy/example/daemonset-azuredisk-ephemeral.yaml
deploy/example/deployment.yaml
deploy/example/nginx-pod-azuredisk.yaml
deploy/example/nginx-pod-ephemeral.yaml
deploy/example/rawblock/README.md
deploy/example/rawblock/nginx-pod-azuredisk.yaml
deploy/example/sharedisk/README.md
deploy/example/sharedisk/deployment.yaml
deploy/example/snapshot/nginx-pod-restored-snapshot.yaml
deploy/example/statefulset-nonroot.yaml
deploy/example/statefulset-nozone.yaml
deploy/example/statefulset.yaml
docs/known-issues/node-shutdown-recovery/statefulset-azuredisk.yaml

doc: support example pod running on arm64 node
Fixes #
```
none
```

doc: support example pod running on arm64 node

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/modules.txt

/kind bug
fix: CVE-2024-51744
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2591
Fixes #
```
fix: CVE-2024-51744
```

[release-1.31] fix: CVE-2024-51744

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/modules.txt

/kind bug
fix: CVE-2024-51744
Fixes #
```
fix: CVE-2024-51744
```

fix: CVE-2024-51744

---

go.mod
go.sum
vendor/github.com/golang-jwt/jwt/v4/parser.go
vendor/modules.txt

/kind bug
fix: CVE-2024-51744
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2591
Fixes #
```
fix: CVE-2024-51744
```

[release-1.30] fix: CVE-2024-51744

---

pkg/azurediskplugin/Dockerfile

/kind feature
chore: upgrade alpine base image to 3.18.9
Fixes #
```
none
```

chore: upgrade alpine base image to 3.18.9

---

pkg/azuredisk/nodeserver_test.go
pkg/os/volume/volume.go

/kind feature
feat: replace Get-Item powershell cmd with golang api on Windows HostProcess mode
Fixes #2436 
```
feat: replace Get-Item powershell cmd with golang api on Windows HostProcess mode
```

feat: replace Get-Item powershell cmd with golang api on Windows HostProcess mode

---

test/external-e2e/manifest/testdriver.yaml

test: disable offline expansion tests
Fixes #
```
none
```

test: disable offline expansion tests

---

pkg/azuredisk/azure_dd_max_disk_count.go

/kind feature
chore: update max data disk num
Fixes #
```
none
```

chore: update max data disk num

---

pkg/azureconstants/azure_constants.go

/kind bug
fix: tagValueDelimiter parameter mismatch
Fixes #2323
```
fix: tagValueDelimiter parameter mismatch
```

fix: tagValueDelimiter parameter mismatch

---

pkg/azureconstants/azure_constants.go

/kind bug
fix: tagValueDelimiter parameter mismatch
cherrpick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2624
Fixes #
```
fix: tagValueDelimiter parameter mismatch
```

[release-1.29] fix: tagValueDelimiter parameter mismatch

---

pkg/azuredisk/azure_controller_common.go

/kind cleanup
cleanup: refine logging
Fixes #
```
none
```

cleanup: refine logging

---

pkg/azuredisk/azuredisk_option.go

/kind cleanup
chore: set concurrent-format-timeout as 100s, proceeding fix of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2616
Fixes #
```
none
```

chore: set concurrent-format-timeout as 100s

---

.github/dependabot.yaml

/kind test
update deps in one pr.
Fixes #
```
none
```

Chores:update deps in one pr.

---

Makefile

/kind test
test: fix building latest-windows-hp tag
Fixes #
```
none
```

test: fix building latest-windows-hp tag

---

go.mod
go.sum
vendor/golang.org/x/crypto/ssh/server.go
vendor/modules.txt

/kind bug
fix: CVE-2024-45337
Fixes #
```
fix: CVE-2024-45337
```

fix: CVE-2024-45337

---

test/external-e2e/run.sh

test: run 1.31 external tests
Fixes #
```
none
```

test: run 1.31 external tests

---

test/external-e2e/run.sh

test: run 1.31 external tests
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2720
Fixes #
```
none
```

[release-1.29] test: run 1.31 external tests

---

test/external-e2e/run.sh

test: run 1.31 external tests
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2720
Fixes #
```
none
```

[release-1.30] test: run 1.31 external tests

---

pkg/os/volume/volume.go

/kind cleanup
cleanup: refine Windows Resizevolume func
Fixes #
```
none
```

cleanup: refine Windows Resizevolume func

---

pkg/os/volume/volume.go

/kind cleanup
cleanup: refine resizevolume error log on Windows
Fixes #
```
none
```

cleanup: refine resizevolume error log on Windows

---

test/external-e2e/run.sh

test: fix external e2e test failure
Fixes #
```
none
```

test: fix external e2e test failure

---

test/external-e2e/run.sh

test: fix external e2e test failure
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2758
Fixes #
```
none
```

[release-1.30] test: fix external e2e test failure

---

pkg/azurediskplugin/main.go
pkg/azurediskplugin/main_test.go

/kind test
test: add unit test for main function
Fixes #
```
none
```

test: add unit test for main function

---

pkg/azuredisk/azure_common_linux.go

/kind feature
feat: add directmount option to fix fsck stuck issue on Linux node, rename `noformat` to `directmount` option which is more reasonable
this PR is a proceeding fix of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2751
Fixes #
```
feat: add directmount option to fix fsck stuck issue on Linux node
```

feat: add directmount option to fix fsck stuck issue on Linux node

---

pkg/os/disk/types.go
pkg/os/filesystem/filesystem.go
pkg/os/volume/volume.go

/kind cleanup
cleanup: only build on Windows for  pkg/os/ dir
Fixes #
```
none
```

cleanup: only build on Windows for pkg/os/ dir

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver_test.go

/kind bug
fix: get disk stuck issue, this PR sets the 1min timeout
Fixes #2716
```
fix: get disk stuck issue
```

fix: get disk stuck issue

---

pkg/azuredisk/azuredisk.go

/kind bug
fix: get disk stuck issue, this PR sets the 1min timeout
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2783
Fixes # 
```
fix: get disk stuck issue
```

[release-1.29] fix: get disk stuck issue

---

.github/workflows/linux.yml

/kind test
test: exclude some go fake files in ut coverage
Fixes #
```
none
```

test: exclude some go fake files in ut coverage

---

pkg/azuredisk/azuredisk_option.go
pkg/azurediskplugin/main.go

/kind feature
chore: set GoMaxProcs as 2
Fixes #
```
none
```

chore: set GoMaxProcs as 2

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: disable two redundant e2e tests
Fixes #
```
none
```

test: disable two redundant e2e tests

---

test/e2e/testsuites/testsuites.go

test: fix pv deletion timeout
Fixes #
```
none
```

test: fix pv deletion timeout

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver_test.go

This pull request includes changes to the `pkg/azuredisk/fake_azuredisk.go` file to clean up and simplify the code by commenting out unused code related to the `cloud` field in the `fakeDriverV1` struct.
Codebase simplification:
* [`pkg/azuredisk/fake_azuredisk.go`](diffhunk://#diff-de4e349c62980354b511
828ca376990dbd5029196a49e7ad85d7316157d2d6c3R104): Commented out the `cloud` field in the `fakeDriverV1` struct and the associated `getCloud` and `setCloud` methods as they are not currently used. [[1]](diffhunk://#diff-de4e349c62980354b511828ca376990dbd5029196a49e7ad85d7316157d2d6c3R104) [[2]](diffhunk://#diff-de4e349c62980354b511828ca376990dbd5029196a49e7ad85d7316157d2d6c3R167-R174) …

test: refine UT for CreateSnapshot

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_managedDiskController.go
pkg/azuredisk/azure_managedDiskController_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/fake_azuredisk.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
test/e2e/testsuites/testsuites.go

/kind cleanup
chore: use GetInfoFromURI func to make URI parsing logic clear
Fixes #
```
none
```

chore: use GetInfoFromURI func to make URI parsing logic clear

---

pkg/azurediskplugin/Dockerfile

/kind feature
chore: Upgrade alpine base image to 3.18.11
Fixes #
```
none
```

chore: Upgrade alpine base image to 3.18.11

---

go.mod
go.sum
vendor/k8s.io/kubernetes/pkg/features/kube_features.go
vendor/k8s.io/kubernetes/pkg/volume/util/device_util_linux.go
vendor/k8s.io/kubernetes/pkg/volume/util/recyclerclient/recycler_client.go
vendor/k8s.io/kubernetes/pkg/volume/util/util.go
vendor/k8s.io/kubernetes/test/e2e/framework/flake_reporting_util.go
vendor/k8s.io/kubernetes/test/e2e/framework/framework.go
vendor/k8s.io/kubernetes/test/e2e/framework/node/resource.go
vendor/k8s.io/kubernetes/test/e2e/framework/skipper/skipper.go
vendor/k8s.io/kubernetes/test/utils/density_utils.go
vendor/k8s.io/kubernetes/test/utils/deployment.go
vendor/k8s.io/kubernetes/test/utils/image/manifest.go
vendor/k8s.io/kubernetes/test/utils/runners.go
vendor/modules.txt

/kind bug
fix: CVE-2025-0426
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2874
```
Total: 1 (UNKNOWN: 0, MEDIUM: 1, HIGH: 0, CRITICAL: 0)
┌───────────────────┬───────────────┬──────────┬────────┬───────────────────┬──────────────────────────────────┬────────────────────────────────────────────────────────┐
│      Library      │ Vulnerability │ Severity │ Status │ Installed Version │          Fixed Version           │                         Title                          │
├───────────────────┼───────────────┼──────────┼────────┼───────────────────┼──────────────────────────────────┼────────────────────────────────────────────────────────┤
│ k8s.io/kubernetes │ CVE-2025-0426 │ MEDIUM   │ …
```

[release-1.31] fix: CVE-2025-0426

---

pkg/azuredisk/azure_controller_common.go

/kind cleanup
cleanup: remove unused unlock variable
Fixes #
```
none
```

cleanup: remove unused unlock variable

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/fake_azuredisk.go

/kind cleanup
cleanup: add context parameter in a few functions
Fixes #
```
none
```

cleanup: add context parameter in a few functions

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/fake_azuredisk.go

/kind cleanup
cleanup: add context parameter in a few functions
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2882
Fixes #
```
none
```

[release-1.31] cleanup: add context parameter in a few functions

---

pkg/azuredisk/controllerserver.go

/kind bug
fix: ignore GetDisk timeout during disk attach
Fixes #
```
fix: ignore GetDisk timeout during disk attach
```

fix: ignore GetDisk timeout during disk attach

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go

/kind bug
This PR merges mutable parameters that come from the volume creation request allowing volumes to be created with the correct attributes
Fixes #
```
none
```

fix: merge mutable parameters for disk creation to support ModifyVolume changes

---

pkg/azuredisk/azure_managedDiskController.go

/kind bug
fix: avoid get disk call in disk creation
Fixes #
```
fix: avoid get disk call in disk creation
```

fix: avoid get disk call in disk creation

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azure_managedDiskController.go
pkg/azuredisk/azure_managedDiskController_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go

fix
/kind cleanup
chore: refine GetDisk operation
Fixes #
```
none
```

chore: refine GetDisk operation

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/trace/provider.go

/kind bug
fix: merge OTEL metrics with legacy registerer
related to fix: https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8594
Fixes #
```
fix: merge OTEL metrics with legacy registerer
```

fix: merge OTEL metrics with legacy registerer

---

pkg/azurediskplugin/Dockerfile

/kind feature
chore: upgrade base image alpine to v1.18.12
Fixes #
```
none
```

chore: upgrade base image alpine to v1.18.12

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go

/kind bug
fix: increase TaintRemovalInitialDelay as 30s
this could avoid race condition between taint add and remove by CSI driver
Fixes #
```
fix: increase TaintRemovalInitialDelay as 30s
```

fix: increase TaintRemovalInitialDelay as 30s

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go

/kind bug
fix: increase TaintRemovalInitialDelay as 30s
this could avoid race condition between taint add and remove by CSI driver
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2977
Fixes #
```
fix: increase TaintRemovalInitialDelay as 30s
```

[release-1.31] fix: increase TaintRemovalInitialDelay as 30s

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver.go

/kind cleanup
cleanup: remove DisableUpdateCache flag
Fixes #
```
none
```

cleanup: remove DisableUpdateCache flag

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go

/kind bug
fix: remove unnecessary get vmss call during disk attach
Fixes #
```
fix: remove unnecessary get vmss call during disk attach
```

fix: remove unnecessary get vmss call during disk attach

---

pkg/azuredisk/azure_controller_common.go

/kind cleanup
cleanup: add one log for dangling volume issue
Fixes #
```
none
```

cleanup: add one log for dangling volume issue

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go

/kind bug
fix: disk detach failure on AzureStack Hub
related to https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8920
Fixes #3045
```
fix: disk detach failure on AzureStack Hub
```

fix: disk detach failure on AzureStack Hub

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_standard.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmss.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_controller_vmssflex.go

/kind bug
fix: disk detach failure on AzureStack Hub
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/3047
Fixes #
```
fix: disk detach failure on AzureStack Hub
```

[release-1.32] fix: disk detach failure on AzureStack Hub

---

go.mod

/kind cleanup
cleanup: add toolchain in go.mod to unblock autobot upgrade
Fixes #
```
none
```

cleanup: add toolchain in go.mod to unblock autobot upgrade

---

deploy/example/vpa/install-vpa.sh
deploy/example/vpa/uninstall-vpa.sh

/kind bug
fix: vpa install and uninstall script
Fixes #
```
none
```

fix: vpa install and uninstall script

---

pkg/os/volume/volume_cim.go

/kind cleanup
cleanup: refine resize volume error logging on Windows node using WMI API
Fixes #
https://learn.microsoft.com/en-us/windows-hardware/drivers/storage/msft-partition-getsupportedsizes
```
none
```

cleanup: refine resize volume error logging on Windows node using WMI API

---

deploy/crd-csi-snapshot.yaml

doc: fix snapshot crd illegal characters in deploy, missing to fix in deploy package in pr:https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/3061
Fixes #
```
none
```

doc: fix snapshot crd illegal characters in deploy

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azure_managedDiskController.go
pkg/util/util.go

/kind cleanup
cleanup: only wait for disk detach when hit MaximumDataDisksExceeded error
Fixes #
```
none
```

cleanup: only wait for disk detach when hit MaximumDataDisksExceeded error

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go

/kind bug
fix: adjust the batch size as per the number of disks allowed
cherrpick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/3039
Fixes #
```
fix: adjust the batch size as per the number of disks allowed
```

[release-1.31] fix: adjust the batch size as per the number of disks allowed

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go

/kind bug
fix: adjust the batch size as per the number of disks allowed
cherrpick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/3039
Fixes #
```
fix: adjust the batch size as per the number of disks allowed
```

[release-1.30] fix: adjust the batch size as per the number of disks allowed

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azure_managedDiskController.go
pkg/util/util.go

/kind cleanup
cleanup: only wait for disk detach when hit MaximumDataDisksExceeded
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/3074
Fixes #
```
none
```

[release-1.31] cleanup: only wait for disk detach when hit MaximumDataDisksExceeded

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/nodeserver_test.go

test: improve TestGetMaxDataDiskCount unit test

---

pkg/azuredisk/nodeserver.go

/kind bug
fix: vmss flex node naming parsing issue
Fixes #
```
none
```

fix: vmss flex node naming parsing issue

---

pkg/azuredisk/azure_common_linux.go
pkg/azurediskplugin/Dockerfile

/kind feature
chore: upgrade alpine base image
https://alpinelinux.org/releases/
Fixes #3104
https://www.man7.org/linux/man-pages/man8/mkfs.xfs.8.html
```
none
```

chore: upgrade alpine base image

---

pkg/azuredisk/azure_common_linux.go
pkg/azurediskplugin/Dockerfile

/kind cleanup
This is a cherry-pick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/3106 for release 1.31.
```
none
```

[release-1.31] chore: upgrade alpine base image `release 1.31`

---

pkg/azureconstants/azure_constants.go
pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go

Addressing issue reported here: https://github.com/Azure/AKS/issues/4544
Fixes #
```
none
```

fix: make disk and snapshot uri regex case insensitive everywhere

---

OWNERS

chore: add new owners to the owners list

---

charts/index.yaml

/kind bug
chore: fix helm chart index on release-1.33
Fixes #
```
none
```

[release-1.33] fix: helm chart index on release-1.33

---

go.mod
go.sum
vendor/golang.org/x/oauth2/LICENSE
vendor/golang.org/x/oauth2/README.md
vendor/golang.org/x/oauth2/internal/doc.go
vendor/golang.org/x/oauth2/internal/oauth2.go
vendor/golang.org/x/oauth2/internal/token.go
vendor/golang.org/x/oauth2/internal/transport.go
vendor/golang.org/x/oauth2/oauth2.go
vendor/golang.org/x/oauth2/pkce.go
vendor/golang.org/x/oauth2/token.go
vendor/golang.org/x/oauth2/transport.go
vendor/modules.txt

/kind bug
fix: CVE-2025-22868
Fixes #
```
fix: CVE-2025-22868
```

[release-1.30] fix: CVE-2025-22868

---

pkg/azuredisk/azure_managedDiskController.go

/kind cleanup
chore: disable public network access for new disk creation by default
Fixes #
```
none
```

chore: disable public network access for new disk creation by default

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go

/kind cleanup
chore: keep disk taint removal in a loop by default
Fixes #
```
none
```

chore: keep disk taint removal in a loop by default

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go

/kind cleanup
chore: keep disk taint removal in a loop by default
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/3226
Fixes #
```
none
```

[release-1.33] chore: keep disk taint removal in a loop by default

---

pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go

/kind cleanup
chore: keep disk taint removal in a loop by default
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/3226
Fixes #
```
none
```

[release-1.32] chore: keep disk taint removal in a loop by default

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets_repo.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/config/azure_cache.go

/kind cleanup
chore: upgrade Azure cloud provider lib
Fixes #
```
none
```

chore: upgrade Azure cloud provider lib

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmsets_repo.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_vmss.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/config/azure_cache.go

/kind feature
chore: upgrade Azure cloud provider lib
Fixes #
```
none
```

[release-1.33] chore: upgrade Azure cloud provider lib

---

pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/fake_azuredisk.go
pkg/azureutils/azure_snapshot_utils.go
pkg/azureutils/azure_snapshot_utils_test.go

/kind bug
perf: rely on readyToUse flag to monitor snapshot progress
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/3141
Fixes #
```
none
```

perf: rely on readyToUse flag to monitor snapshot progress

---

test/e2e/dynamic_provisioning_test.go

/kind flake
test: disable MaximumDataDisksExceeded flaky test case
Fixes #
```
none
```

test: disable MaximumDataDisksExceeded flaky test case

---

hack/verify-helm-chart-index.sh

test: ignore latest tgz file in helm chart index verification
Fixes #
<details>
```
Images in deploy/ matches those in the latest helm chart.
begin to verify all URLs in /home/prow/go/src/sigs.k8s.io/blob-csi-driver/charts/index.yaml ...
warning: https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/release-1.26/charts/latest/blob-csi-driver-1.26.7.tgz is invalid
check whether /home/prow/go/src/sigs.k8s.io/blob-csi-driverhttps://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/release-1.26/charts/latest/blob-csi-driver-1.26.7.tgz exists …
```

test: ignore latest tgz file in helm chart index verification

---

pkg/azuredisk/controllerserver.go

/kind bug
fix: ZRS disk should support 4 zones
eastus2euap region already supports 4 availability zones now
Fixes #
```
none
```

fix: ZRS disk should support 4 zones

---

test/utils/azure/azure_helpers.go

test: fix sanity test failure
Fixes #
```
none
```

test: fix sanity test failure

---

pkg/azuredisk/azuredisk_option.go

Reverts kubernetes-sigs/azuredisk-csi-driver#3358

Revert "fix: disable enable-minimum-retry-after by default"
