kubernetes-sigs/azuredisk-csi-driver

pkg/azuredisk/azuredisk_test.go

Fixes #4 
Add unit tests for `getDiskName` and `isManagedDisk` from azurefile.go

Add unit tests for azuredisk.go

---

.travis.yml
README.md
deploy/azuredisk-csi-driver.yaml
deploy/csi-azuredisk-attacher.yaml
deploy/csi-azuredisk-provisioner.yaml
pkg/azuredisk/controllerserver.go
test/integration/run-test.sh

This PR also fixed an issue: make attach disk idempotent, otherwise there would be error when attaching a disk to a node, like following(that's because original attach disk is not idempotent):
```
Events:
Type     Reason                  Age                 From                               Message
----     ------                  ----                ----                               -------
Normal   Scheduled               2m10s               default-scheduler                  Successfully assigned default/nginx-azuredisk to k8s-agentpool-34398540-0
Warning  FailedAttachVolume      115s                attachdetach-controller            AttachVolume.Attach failed for volume "pvc-ce388ed4-2f9a-11e9-8ba9-000d3a004ffb" : attachment timeout for volume …
```

Move to use CSI 1.0.0

---

deploy/azuredisk-csi-driver.yaml

/kind bug
This commit tunes liveness check specs for azure CSI disk driver based on some observations made by running the drivers in azure cluster for 1 hr. Earlier specs was too strict for the driver which was causing driver pod to restart without any driver failure.
The observations are:
-> Earlier the period of liveness check was too frequent around 2s which was adding a heavy network traffic weight on the pods.
-> The timeout value was around 3s which is very less for a csi driver to respond.
-> Failure theshold was 1 which causes the pod restart if the request was not completed in 3s.
```
tunes livenessprobe specs for csi drivers
```

refactor: tunes livenessprobe specs for csi drivers

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go

Signed off by: Priyanshu Khandelwal masquerade0097@gmail.com
/kind bug
Fix the following Sanity test failure 
```
[Fail] Controller Service ControllerPublishVolume [It] should fail when the volume does not exist 
/home/priyanshu/work/src/github.com/csi-driver/azuredisk-csi-driver/vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go:883
```
Addresses #46 
```
Fail ControllerPublishVolume when volume does not exist
```

Fail ControllerPublishVolume when volume doesn't exist

---

pkg/azuredisk/controllerserver.go

Signed-off-by: Priyanshu Khandelwal masquerade0097@gmail.com
/kind bug
Fix the following sanity test failure
```
[Fail] Controller Service ControllerPublishVolume [It] should fail when the node does not exist 
/home/priyanshu/work/src/github.com/csi-driver/azuredisk-csi-driver/vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go:941
```
Addresses #46 
```
Fail ControllerPublishVolume sanity test when node does not exist 
```

Fail ControllerPublishVolume when no node exists

---

Gopkg.lock
Makefile
pkg/azuredisk/azuredisk.go
pkg/azuredisk/version.go
pkg/azurediskplugin/main.go

/kind feature
This commit adds version flag in azuredisk plugin along with some metadata information like commit id and build date. Output of `azurediskplugin --version`:
```
$ ./_output/azurediskplugin --version
Build Date: "2019-03-27T17:33:17Z"
Compiler: gc
Driver Name: disk.csi.azure.com
Driver Version: v0.2.0-alpha
Git Commit: 37087f14c162df8566c0a75b3477ad6d47eb676b
Go Version: go1.11.5
Platform: linux/amd64
Topology Key: topology.disk.csi.azure.com/zone
```
The same information is now also printed in logs as well. Below is an example of this:
```
$ kubectl logs -f csi-azuredisk-rccc5 -n kube-system -c azuredisk
I0327 17:35:59.084225       1 azuredisk.go:65] …
```

enhance(version): Add version flag in azuredisk plugin

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go

/kind bug
Fixes the following failure in sanity testing - 
```
[Fail] Controller Service DeleteVolume [It] should succeed when an invalid volume id is used 
/home/priyanshu/work/src/github.com/csi-driver/azuredisk-csi-driver/vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/controller.go:543
```
Fixes #
```
fix DeleteVolume sanity test for invalid volumeId
```

fix DeleteVolume sanity test for invalid volumeId

---

pkg/azuredisk/nodeserver.go

/kind bug
When 2 pods mount same disk pvc on the same node, there will be error like error:
```
target "/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-de4f7c7d-5c76-11e9-9ea8-000d3a269e74/globalmount" is not a valid mount point
```
Fixes #73
```
fix error when 2 pods mount same disk pvc on the same node
```

fix error when 2 pods mount same disk pvc on the same node

---

OWNERS_ALIASES

I'm doing some org/repo-wide OWNERS file parsing, and this is an
invalid OWNERS_ALIASES file.  It doesn't actually contain any aliases so
doesn't seem like there's much point in keeping it around.  Our 
`verify-owners` plugin should catch these in the future.

remove invalid OWNERS_ALIASES file

---

Gopkg.lock
Gopkg.toml

/kind api-change
remove unnecessary go-autorest dep in Go dep
https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/93 introduces an unnecessary go dep config, now remove it
Fixes #
```
none
```

fix: remove unnecessary go-autorest dep in Go dep

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go

/kind bug
This PR makes the azure disk URI as case insensitive, otherwise there could be error like following if customer ignore the disk URI case:
```
Error expanding volume "del-me/test-pvc" of plugin kubernetes.io/azure-disk : invalid disk URI: /subscriptions/xxx/resourcegroups/xxx/providers/Microsoft.Compute/disks/Test_Resize_1/”
```
backport PR: https://github.com/kubernetes/kubernetes/pull/79020
Fixes #
```
fix: make azure disk URI as case insensitive
```

fix: make azure disk URI as case insensitive

---

deploy/csi-azuredisk-controller.yaml
pkg/azurediskplugin/main.go

/kind feature
feat: enable prometheus metrics in deployment
Fixes #
```
$ kubectl get svc -n kube-system | grep azuredisk
csi-azuredisk-controller   ClusterIP   10.0.207.216   <none>        10252/TCP       8s
$ curl http://10.0.207.216:10252/metrics
$ curl http://10.0.207.216:10252/metrics | grep cloudprovider | grep -e sum -e count 0cloudprovider_azure_api_request_duration_seconds_sum{request="disks_create_or_update",resource_group="mc_andy-virtualnode_andy-virtualnode_eastus2",source="",subscription_id="..."} 5.655316338
cloudprovider_azure_api_request_duration_seconds_count{request="disks_create_or_update",resource_group="mc_andy-virtualnode_andy-vi …
```

feat: enable prometheus metrics in deployment

---

pkg/azuredisk/nodeserver.go

>
> /kind bug
When we can't get instance type, it should be set "". 
Then the function will return defaultAzureVolumeLimit.
```
[Fail] Node Service NodeGetInfo [It] should return approproate values
/root/go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go:146
[Fail] Node Service [It] should work
/root/go/src/github.com/kubernetes-sigs/azuredisk-csi-driver/vendor/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go:375
```
With the PR, these two failures will be fixed.
Fixes #46 …

fix: return the default MaxVolumesPerNode

---

deploy/csi-azuredisk-controller.yaml
pkg/azuredisk/controllerserver.go

/kind feature
feat: fix CSI migration issue, this PR would:
- upgrade csi-provioner, csi-attacher version to support in-tree volume driver migration to CSI driver
- fix CSI translation issue: `kind` value unrecognized by in-tree volume driver.
Fixes #
```
feat: fix CSI migration issue
```

feat: fix CSI migration issue

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/nodeserver.go

/kind feature
Since azuredisk could be resized when mounted, we just need to implement `func ControllerExpandVolume()`. The method `func NodeExpandVolume()` does not need to be implemented.
Fixes #55 
```
support volume resize
```

feat: support volume resize

---

Makefile
charts/README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/example/cloning/README.md
deploy/example/cloning/nginx-pod-restored-cloning.yaml
deploy/example/cloning/pvc-azuredisk-cloning.yaml
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
test/e2e/dynamic_provisioning.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_volume_cloning.go
test/e2e/testsuites/specs.go
test/utils/azuredisk_log.sh

/kind feature
Support `volume cloning` feature. 
Now we can create a managed disk from an existing managed disk.
Fixes #153 #197 
The related sanity tests have passed.
```
support volume cloning
```

feat: support volume cloning

---

deploy/csi-azuredisk-node.yaml
hack/verify-all.sh
hack/verify-helm-chart.sh

>
> /kind bug
> /kind design
> /kind test
> /kind flake
/kind test
Added a check in `pull-azuredisk-csi-driver-verify` that will compare image version in helm chart with manifests in the deploy folder, and return an exit code 1 if a mismatch is found.
Fixes #203 
Fixes #197
```
```

Keep helm chart in sync with manifests in deploy folder

---

test/e2e/testsuites/testsuites.go

/kind test
found a disk detect perf regression issue due to getVMSS TTL changed from 10min to 1min, related PR: https://github.com/kubernetes/kubernetes/pull/86006
This PR changed e2e pod ready timeout from 15min to 10min, to make sure e2e test could catch that issue, and 10min should be long enough. WDYT @chewong 
Fixes #
```
none
```

test: reduce e2e pod ready timeout to 10min

---

pkg/azuredisk/azure_common_linux.go

/kind bug
fix: disk could not mounted on Standard_DC4s/DC2s instances
thanks  @joekottke for the detailed analysis, this PR should be the better way to fix this issue
Fixes #212
```
fix: disk could not be mounted on Standard_DC4s/DC2s instances
```

fix: disk could not be mounted on Standard_DC4s/DC2s instances

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go

/kind bug
Fix the volume not found bug following [example](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-azuredisk-static-provisioninguse-an-existing-azure-disk).
The disk URI regex validation should be case insensitive such as `subscriptions`, `resourcegroups`, `Microsoft.Compute`...
```
ignore case for managedDiskPathRE and diskSnapshotPathRE
```

ignore case for managedDiskPathRE and diskSnapshotPathRE

---

docs/driver-parameters.md
pkg/azuredisk/controllerserver.go
pkg/util/util.go
pkg/util/util_test.go

>
> /kind bug
> /kind design
> /kind test
/kind feature
> /kind flake
This is to allow uses to add custom tags to the disks that created by csi driver
Fixes #178 
```
tags parameter is added in parameters, usage example:
parameters:
...
tags: 'foo=aaa,bar=bbb' # Add this parameter to set azure disk tags
```

Support for tags parameter

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml

>
> /kind bug
> /kind design
> /kind test
> /kind flake
We need to set resource requests/limits for azure CSI driver pods. 
Fixes #129 
```
Setting CPU/Memory requests/limits for azure csi driver containers
```

Setting cpu/memory requests/limits for csi driver containers

---

test/e2e/manifest/multi-az.json
test/e2e/manifest/single-az.json

>
> /kind bug
> /kind design
> /kind test
> /kind flake
Extracted changes from #261 so that e2e test in #261 can be run on a VMAS cluster with MSI enabled after this PR is merged
Fixes #256
```
```

Enable MSI option for VMAS cluster

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml
pkg/azurediskplugin/main.go
test/utils/check_driver_pods_restart.sh

/kind feature
This PR changes the port nums and also deletes the service which is for metrics, and if user wants to get metrics, could create following service:
```
---	
apiVersion: v1	
kind: Service	
metadata:	
name: csi-azuredisk-controller	
namespace: kube-system	
spec:	
selector:	
app: csi-azuredisk-controller	
ports:	
- port: 29604	
targetPort: 29604
type: ClusterIP
```
```
controller
health: 29602
metrics: 29604
node
health: 29603
```
Fixes #
```
none
```

chore: change port num for this driver

---

pkg/azuredisk/nodeserver.go

/kind bug
This PR improves disk detection inside VM, as suggested by @kosta709 thanks a lot!
```
regarding nodeserver.go - yes it polls every second, but if /dev/... is not there (findDiskByLun returns "") it returns fmt.Errorf("azureDisk - findDiskByLun(%v) failed within timeout", lun). and exits from wait.Poll
It causes to kubelet retry NodePublishVolume with exponensial backoff, and because /dev/disk/azure/... can appear 15-60s after first first call it can reach 2m timeout.
So I suggest to just return false, nil and let wait.Poll to retry instead of kubelet.
```
Fixes #
```
fix: improve disk detection inside VM
```

fix: improve disk detection inside VM

---

charts/README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-node.yaml
pkg/azurediskplugin/main.go

/kind bug
/kind flake
After refactored, azure cloud provider uses the Kube registry to export metrics. We should register the handler associated with the Kube registry, instead of that is built-in in the Prometheus default registry.
https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/component-base/metrics/legacyregistry/registry.go#L39-L47
Fixes #280 
```
```

 fix: use KubeRegistry instead of prometheus default registry

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
deploy/csi-azuredisk-driver.yaml
docs/driver-parameters.md
pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/nodeserver.go

/kind feature
This PR:
- did a cleanup with `getDevicePathWithLUN` func
- adds azure disk WriteAccelerator support
added a new parameter(`writeAcceleratorEnabled` case insensitive) in azure disk storage class, for static provisioning, user needs to add a new tag(`writeacceleratorenabled` case **sensitive**) on azure disk before using as disk PV.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: ssd
provisioner: kubernetes.io/azure-disk
parameters:
skuname: Premium_LRS
writeAcceleratorEnabled: "true"
```
- background
For high performance applications, like databases, using Write Accelerator on disks where the database log is stored can improve performance. If customers are already using M or Mv2 VM …

feat: add azure disk WriteAccelerator support

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/fake_azuredisk.go
pkg/csi-common/driver_test.go
pkg/csi-common/fake_driver.go
pkg/csi-common/nodeserver-default_test.go
test/utils/credentials/credentials.go

/kind bug
/kind test
/kind flake
- add some unit tests for CreateVolume() and DeleteVolume()
- correct the max volume size unit to compare with requestGiB
- use `NewFakeCSIDriver()` instead of `NewFakeDriver()` to avoid ambiguity, becasue `NewFakeDriver()` will be used for azuredisk.Driver
Fixes #
```
```

test: add some unit tests for CreateVolume() and DeleteVolume()

---

pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/nodeserver_test.go

/kind test
add unit test for ensureMountPoint func.
Fixes #268 
Since the `Unmount` and `MakeDir` functions of FakeMounter always return nil error, we cannot cover their error scenarios.
```
```

test: add the unit test for ensureMountPoint func

---

pkg/azuredisk/nodeserver.go

/kind bug
In CSI Spec, it requires that the SP MUST delete the file or directory it created at this path.
Ref: https://github.com/container-storage-interface/spec/blob/master/spec.md#nodeunpublishvolume
Fixes #
The PR will solve the problem in the issue #283.
```
```

fix: correct the behavior of deleting the target direcotory

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/nodeserver.go

/kind feature
this PR would handle broken mount in both `NodeStage` and `NodePublish`
- detect the broken mount path
- unmount broken mount path
- remount mount path
similar fix as https://github.com/kubernetes-sigs/blobfuse-csi-driver/pull/117
Fixes #
```
feat: support corrupted mount
```

fix: support corrupted mount

---

deploy/example/snapshot/README.md

Signed-off-by: Steve Kriss <krisss@vmware.com>
>
> /kind bug
> /kind design
> /kind test
> /kind flake
Fix commands in snapshots example to use correct path when checking volume contents
Fixes #
See correct mountPaths: 
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/nginx-pod-azuredisk.yaml#L18
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/deploy/example/snapshot/nginx-pod-restored-sn …

docs fix: use correct path to check volume contents

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
hack/verify-helm-chart.sh

/kind cleanup
According to Kubernetes CSI Developer Documentation, the cluster-driver-registrar side-car which was used to create CSIDriver objects in Kubernetes 1.13 has been deprecated for Kubernetes 1.16. No cluster-driver-registrar has been released for Kubernetes 1.14 and later.
Fixes #335 
```
remove cluster driver registrar
```

chore: remove cluster driver registrar

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go

>
> /kind bug
> /kind design
> /kind test
> /kind flake
For `should create a deployment object, write and read to it, delete the pod and write and read to it again` test case, we should ensure the text file created by the deployment exists before deleting the pod.
/test pull-in-tree-azure-disk-e2e-windows
Fixes https://github.com/kubernetes/kubernetes/pull/89768#issuecomment-607910662.
```
```

test: deflake deployment test case

---

Makefile
README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
charts/v0.6.0/azuredisk-csi-driver/templates/csi-azuredisk-driver.yaml
deploy/csi-azuredisk-driver.yaml
deploy/v0.6.0/csi-azuredisk-driver.yaml

/kind flake
Since we won't support inline feature in the near future, the `volumeLifecycleModes` field is unnecessary. So that azuredisk-csi-driver can be still compatible with v1.14+.
Fixes #
```
```

chore: remove volumeLifecycleModes in CSIDriver

---

hack/verify-golint.sh

/kind flake 
Currently the go get for golangci-lint is failing with:
```
$ go get github.com/golangci/golangci-lint/cmd/golangci-lint
go/src/github.com/golangci/golangci-lint/pkg/golinters/golint.go:21:14: l.LintPkg undefined (type *"github.com/golangci/lint-1".Linter has no field or method LintPkg)
go/src/github.com/golangci/golangci-lint/pkg/golinters/gomnd.go:13:6: cannot use magic_numbers.Analyzer (type *"github.com/tommy-muehle/go-mnd/vendor/golang.org/x/tools/go/analysis".Analyzer) as type *"golang.org/x/tools/go/analysis".Analyzer in array or slice literal
```
The README.md of golangci-lint recommends to do not use go get for installation - https://github.com/golangci/golangci-lint#go.
This PR also pins the …

Do not install golangci-lint with 'go get'

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/v0.5.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/v0.6.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/v0.7.0/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-controller.yaml
deploy/v0.5.0/csi-azuredisk-controller.yaml
deploy/v0.6.0/csi-azuredisk-controller.yaml
deploy/v0.7.0/csi-azuredisk-controller.yaml

/kind cleanup
`--provisioner` and `--connection-timeout` flags are deprecated and have no effect since v1.1.0 of csi-provisioner. Ref https://github.com/kubernetes-csi/external-provisioner/blob/v1.6.0/CHANGELOG-1.1.md
Fixes #
```
NONE
```

Remove deprecated csi-provisioner args

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/rbac-csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/csi-azuredisk-controller.yaml
deploy/rbac-csi-azuredisk-controller.yaml

/kind feature
chore: upgrade csi-attacher to v2.2.0
To support `LIST_VOLUMES_PUBLISHED_NODES` capability
Fixes #339
/hold
hold on, need to check whether csi-attacher `v2.2.0` supports v1.14 or not
```
none
```

chore: upgrade csi-attacher to v2.2.0

---

test/e2e/dynamic_provisioning_test.go

Reverts kubernetes-sigs/azuredisk-csi-driver#383
actually it's not a necessary test change, `zoned` is always true for managed disk

Revert "test: enable topology for azure disk in-tree e2e tests"

---

charts/latest/azuredisk-csi-driver/templates/crd-csi-snapshot.yaml
charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
charts/latest/azuredisk-csi-driver/values.yaml
deploy/crd-csi-snapshot.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-snapshot-controller.yaml
hack/verify-yamllint.sh

/kind feature
chore: upgrade snapshot controller to v2.1.1
v2.1.1 snapshot resources are under:
https://github.com/kubernetes-csi/external-snapshotter/tree/v2.1.1/config/crd
https://github.com/kubernetes-csi/external-snapshotter/tree/v2.1.1/deploy/kubernetes
Fixes #
```
~/go/src/github.com/kubernetes-csi/external-snapshotter/config/crd# cat snapshot.storage.k8s.io_volumesnapshots.yaml snapshot.storage.k8s.io_volumesnapshotclasses.yaml snapshot.storage.k8s.io_volumesnapshotcontents.yaml > /tmp/crd-csi-snapshot.yaml
```
```
chore: upgrade snapshot controller to v2.1.1
```

chore: upgrade snapshot controller to v2.1.1

---

Makefile
test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

/kind test
test: add publish image support
original `az acr build` does not work on Windows due to https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/396
Fixes #
```
cd $csi_disk
export REGISTRY_NAME=
export REGISTRY=$REGISTRY_NAME.azurecr.io
export IMAGE_NAME=public/k8s/csi/azuredisk-csi
export CI=1
export PUBLISH=1
make azuredisk-container
make push
make push-latest
```
```
none
```

test: add publish image support

---

README.md
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node.yaml
pkg/azuredisk/azure.go
pkg/azuredisk/azure_test.go

/kind feature
feat: use `azure-cred-file` configmap in `kube-system` namespace to specify azure-cred-file path
> To specify a different cloud provider config file, create `azure-cred-file` configmap before driver installation, e.g. for OpenShift, it's `/etc/kubernetes/cloud.conf`
> ```console
> kubectl create configmap azure-cred-file --from-literal=path="/etc/kubernetes/cloud.conf" --from-literal=path-windows="C:\\k\\cloud.conf" -n kube-system
> ```
Fixes #398
```
feat: use `azure-cred-file` configmap in `kube-system` namespace to specify azure-cred-file path
```

feat: use `azure-cred-file` configmap in `kube-system` namespace to specify azure-cred-file path

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/testsuites.go

/kind test
test: set timeout as 10min for windows pod
Fixes #
as I could find out, the successful pod start time could be around 2.5min, while in some cases, it would exceed 5min(not sure why), increase the timeout to 10min in this windows e2e case first.
below are some logs for case `ginkgo.It("should create a deployment object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-disk] [disk.csi.azure.com] [Windows]"`:
```
May  6 14:28:51.908: INFO: Running '/usr/local/bin/kubectl --kubeconfig=/root/tmp531642905/kubeconfig/kubeconfig.eastus2.json exec azuredisk-volume-tester-jtx6n-574b7769b4-h9dsv …
```

test: set timeout as 10min for windows pod

---

pkg/azuredisk/controllerserver.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go

/kind test
test: fix resize e2e test failure
Fixes #
fixed the resize e2e test failure:
```
[pod/csi-azuredisk-controller-5fbc7fdc6b-fk8q2/azuredisk] I0721 01:13:53.468923       1 utils.go:112] GRPC call: /csi.v1.Controller/ControllerExpandVolume
[pod/csi-azuredisk-controller-5fbc7fdc6b-fk8q2/azuredisk] I0721 01:13:53.469033       1 utils.go:113] GRPC request: volume_id:"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-f50c87d9-cae6-11ea-83ab-52a5d34da032/providers/Microsoft.Compute/disks/pvc-f742d627-4878-47f1-86c8-37512347dbb1" capacity_range:<required_bytes:11811160064 > …
```

test: fix resize e2e test failure

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node.yaml
deploy/csi-snapshot-controller.yaml

/kind flake
Set the reasonable CPU and Memory.
- Reduce limit of azuredisk container CPU and Memory to one fifth.
- Reduce limit of sidecar containers  CPU and Memory to one tenth.
Fixes #
Use `kubectl top pod` command to get the usage data.
```
POD                                        NAME              CPU(cores)   MEMORY(bytes)   
csi-azuredisk-controller-8d64dfcc8-js7gp   csi-resizer       1m           7Mi             
csi-azuredisk-controller-8d64dfcc8-js7gp   liveness-probe    1m           5Mi             
csi-azuredisk-controller-8d64dfcc8-js7gp   azuredisk         1m           10Mi …
```

chore: reduce limit of CPUand Memory

---

test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go

/kind test
test: fix in-tree resie e2e test failure
```
Dynamic Provisioning [single-az] should create a volume on demand and resize it [disk.csi.azure.com] [Windows] expand_less | 46s
-- | --
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:499 Test Panicked /usr/local/go/src/runtime/panic.go:212  Panic: runtime error: invalid memory address or nil pointer dereference  Full stack: sigs.k8s.io/azuredisk-csi-driver/test/e2e/testsuites.(*DynamicallyProvisionedResizeVolumeTest).Run(0xc000623328, 0x20fd0e0, 0xc000322c60, 0xc000704dc0) 	/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go:97 +0x903 …
```

test: fix in-tree resie e2e test failure

---

test/e2e/dynamic_provisioning_test.go
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/specs.go
test/e2e/testsuites/testsuites.go

/kind bug
Only when using the command `Get-Content` to check the content, the error sometimes happens. So here I just change one related command, not all commands.
Fixes #381 and https://github.com/kubernetes/kubernetes/issues/94269
```
none
```

fix: use CMD command to avoid the encoding issue

---

Makefile
test/sanity/run-tests-all-clouds.sh

/kind cleanup
This turns on GO111MODULE by default in the Makefile.
```
none
```

Make GO111MODULE on by default in Makefile

---

charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node.yaml
pkg/azurediskplugin/Dockerfile
pkg/azurediskplugin/dev.Dockerfile

Reverts kubernetes-sigs/azuredisk-csi-driver#558
Original PR did not improve the security, that PR is just for bypass security scanning, while would introduce various permission setting issue.

Revert "fix: create nonroot user in Dockerfile"

---

.github/workflows/windows.yml
pkg/azuredisk/azure_test.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/fake_mounter.go
pkg/azuredisk/nodeserver_test.go
test/utils/testutil/testutil.go

Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>
/kind test
Enable windows unit tests and add CSI proxy mount to workflow
Fixes #525 
```
none
```

test: enable csi-proxy.exe in workflow and enable windows unit tests

---

.github/workflows/darwin.yaml
.github/workflows/linux.yml
.github/workflows/windows.yml
Makefile
pkg/azuredisk/azure_common_test.go
pkg/azuredisk/nodeserver_test.go
test/utils/testutil/testutil.go

Signed-off-by: Mayank Shah <mayankshah1614@gmail.com>
/kind test
Add MacOS unit test workflow
Fixes #
@andyzhangx  This is a duplicate of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/555; working on this clean branch to fix any further test failures as seen in the above mentioned PR 
```
none
```

CI: Add darwin unit test workflow

---

pkg/azuredisk/nodeserver.go

/kind bug
As this [ticket](https://bugzilla.redhat.com/show_bug.cgi?id=1405238) described, for some old version `findmnt`, if the volume path does not exist, using flag `--target` will not give you any error (exit code is 0), which is not what we want.
In Azure Stack test, `findmnt` with the flag `--target` always gives exit code 0 no matter what path it is given. However, the flag `--mountpoint` works fine.
As the `findmnt` [manual](https://man7.org/linux/man-pages/man8/findmnt.8.html) says, "It's recommended to use the option --mountpoint when checks of path elements are unwanted and path is a strictly specified mountpoint."
Fixes #
**Special notes for your …

fix: use --mountpoint instead of --target for findmnt

---

test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh

/kind test
test: use a different path for csi-sanity test
original path would cause following error with go 1.14+:
```
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/csi-test/cmd/csi-sanity /home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver
make[1]: Entering directory '/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/csi-test/cmd/csi-sanity'
go test -ldflags "-w -X github.com/kubernetes-csi/csi-test/cmd/csi-sanity.VERSION=v1.1.0-172-g82b0519-HEAD -extldflags '-z relro -z now'" -c -o csi-sanity
sanity_test.go:24:2: cannot find package "." in:
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/vendor/github.com/kubernetes-csi/csi-test/pkg/sanity
FAIL	sigs.k8s.io/azuredisk-csi-driver/csi-test/cmd/csi-sanity [setup …
```

test: use a different path for csi-sanity test

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/utils/check_driver_pods_restart.sh

/kind test
Fixes the output text encoding for the Windows statefulset and deployment e2e test cases by using the Powershell Out-File cmdlet.
Fixes a minor spelling error in test result logging.
Fixes #381, #615
Re-enables one of the two test cases (statefulset) for #615. The deployment e2e test is still waiting for fix https://github.com/kubernetes/kubernetes/pull/95456.
```
none
```

test: fix windows output encoding for statefulset and deployment e2e test cases

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/fake_azuredisk.go
test/integration/run-test.sh
test/sanity/run-test.sh

/kind feature
Fixes #378 #617 
```
feat: Implement ListVolumes
```

feat: Implement ListVolumes

---

test/sanity/run-test.sh
test/sanity/run-tests-all-clouds.sh

/kind test
test: upgrade sanity-test to v4.0.2
the following two sanity tests actually could not pass since
- node should be idempotent: CI is running inside container in google cloud
- controller should be idempotent:  there is delete volume error in the test cleanup since at that time disk is still attached to the node
```
[91m[1mSummarizing 2 Failures:[0m
[91m[1m[Fail] [0m[90mNode Service [0m[91m[1m[It] should be idempotent [0m
[37m/home/prow/go/src/github.com/kubernetes-csi/csi-test/pkg/sanity/node.go:140[0m
[91m[1m[Fail] [0m[90mController Service [Controller Server] [0m[91m[1m[AfterEach] volume lifecycle [0m[90mshould be idempotent [0m …
```

test: upgrade sanity-test to v4.0.2

---

test/e2e/dynamic_provisioning_test.go

test: disable statefulset test on CSI Windows

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/nodeserver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_cloning_tester.go

/kind bug
Fixes #528 
```
none
```

fix: resize filesystem if cloned volume capacity is larger than the source volume

---

test/e2e/dynamic_provisioning_test.go

test: disable clone test in multi-zone cluster
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/665/pull-azuredisk-csi-driver-e2e-multi-az/1349708105583169536/build-log.txt
```
Jan 14 14:01:00.259: INFO: At 2021-01-14 13:45:47 +0000 UTC - event for pvc-tc58v: {persistentvolume-controller } WaitForFirstConsumer: waiting for first consumer to be created before binding
Jan 14 14:01:00.259: INFO: At 2021-01-14 13:45:48 +0000 UTC - event for pvc-tc58v: {disk.csi.azure.com_k8s-agentpool-21767807-vmss000001_7072752f-24d1-4343-af35-eba1d34b194f } ProvisioningFailed: failed to provision volume with StorageClass …
```

test: disable clone test in multi-zone cluster

---

.github/workflows/windows.yml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-controller.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node-windows.yaml
charts/latest/azuredisk-csi-driver/templates/csi-azuredisk-node.yaml
charts/latest/azuredisk-csi-driver/templates/csi-snapshot-controller.yaml
deploy/csi-azuredisk-controller.yaml
deploy/csi-azuredisk-node-windows.yaml
deploy/csi-azuredisk-node.yaml
deploy/csi-snapshot-controller.yaml
hack/verify-examples.sh
pkg/csi-common/controllerserver-default.go
pkg/csi-common/identityserver-default.go
pkg/csi-common/nodeserver-default.go
pkg/csi-common/utils.go
pkg/csi-common/utils_test.go

/kind bug
fix: reduce driver logs
- don't print following method logs by default
following 3 method logs constitute 99.8% logs of all driver logs, this PR set the log level of following 3 methods as `10`, and it would not show in driver logs by default(<= `5` will show in driver logs)
```
/csi.v1.Identity/Probe
/csi.v1.Node/NodeGetCapabilities
/csi.v1.Node/NodeGetVolumeStats
```
- set log level of csi side car contains as 2
This could reduce `17,280` logs every day of csi-provisioner, csi-resizer, etc which has lease election, following logs would show every 5s:
```
I0119 12:57:02.073355       1 leaderelection.go:282] successfully renewed lease kube-system/blob-csi-azure-com
I0119 12:57:07.081182       1 …
```

fix: reduce driver logs

---

test/e2e/manifest/migration-windows.json

/kind bug
Optionally add one or more of the following kinds if applicable:
Updates windows image version to use in the e2e test manifest. New windows version has mitigation for driver DaemonSet crashes.
Fixes #553 
@andyzhangx Please review.
```
none
```

fix: Use new windows server image to avoid driver daemonset failure

---

pkg/azuredisk/azure.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/mockcorev1/doc.go
pkg/azuredisk/mockcorev1/interface.go
pkg/azuredisk/mockkubeclient/doc.go
pkg/azuredisk/mockkubeclient/interface.go
pkg/azuredisk/mockpersistentvolume/doc.go
pkg/azuredisk/mockpersistentvolume/interface.go
test/integration/run-test.sh

/kind bug
Fixes #632 
```
none
```

fix: ListVolumes should be able to return volumes from external rgs as well

---

test/e2e/dynamic_provisioning_test.go

test: disable statefulset test for Windows in-tree driver since it's failing for long time
https://testgrid.k8s.io/sig-windows-master-release#aks-engine-windows-dockershim-azure-disk-master
```
• Failure [120.604 seconds]
Dynamic Provisioning
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:38
[single-az]
/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:41
should create a statefulset object, write and read to it, delete the pod and write and read to it again [kubernetes.io/azure-disk] [disk.csi.azure.com] [Windows] [It] 
```
Fixes https://github.com/kubernetes/kubernetes/issues/99947 …

test: disable statefulset test for Windows in-tree driver

---

.github/workflows/windows.yml
pkg/azuredisk/controllerserver.go

/kind feature
feat: support ZRS disk
To support ZRS disk on one subscription, run:
```console
az feature register --name SsdZrsManagedDisks --namespace Microsoft.Compute
az feature list -o table --query "[?contains(name, 'Microsoft.Compute/SsdZrsManagedDisks')].{Name:name,State:properties.state}"
az provider register --namespace Microsoft.Compute
```
- `nodeAffinity` of ZRS disk
```
spec:
accessModes:
- ReadWriteOnce
capacity:
storage: 10Gi
claimRef:
apiVersion: v1
kind: PersistentVolumeClaim
name: persistent-storage-statefulset-azuredisk-0
namespace: default
resourceVersion: "48991"
uid: 47534b37-c817-464a-8b8e-c37427f77c00
csi:
driver: disk.csi.azure.com
volumeAttributes:
skuname: StandardSSD_ZRS …
```

feat: support ZRS disk

---

pkg/azuredisk/controllerserver.go

/kind feature
feat: support allowedTopologies in storage class for ZRS disk
following `allowedTopologies` config would be respected by this PR, and PV would have corresponding `nodeAffinity` setting:
```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
name: managed-csi-zone
provisioner: disk.csi.azure.com
parameters:
skuname: StandardSSD_ZRS  # alias: storageaccounttype, available values: Standard_LRS, Premium_LRS, StandardSSD_LRS, UltraSSD_LRS
reclaimPolicy: Delete
allowedTopologies:
- matchLabelExpressions:
- key: topology.disk.csi.azure.com/zone
values:
- eastus2euap-1
- eastus2euap-2
```
```yaml
nodeAffinity:
required:
nodeSelectorTerms:
- matchExpressions:
- key: topology.disk.csi.azure.com/zone …
```

feat: support allowedTopologies in storage class for ZRS disk

---

Makefile
test/external-e2e/run.sh

Add k8s external e2e tests
Fixes #
```
none
```

Setup k8s external e2e tests

---

test/external-e2e/manifest/testdriver.yaml
test/external-e2e/run.sh

fail external-e2e prow job on test failure
/kind test
Fixes #
```
none
```

fail external-e2e prow job on test failure

---

Makefile
docs/csi-dev.md
pkg/azurediskplugin/Dockerfile
pkg/azurediskplugin/Windows.Dockerfile
pkg/azurediskplugin/dev.Dockerfile
test/integration/run-test.sh
test/sanity/run-test.sh

/kind cleanup
Fixes the Makefile `container-all` target to build the correct architecture binary and splits outputs into architecture-specific directories to ensure the correct binary is used when building the container image.
The initial support for the arm64 build through `container-all` appeared to work but actually picked up the amd64 build because the incorrect `ARCH=$${arch} $(MAKE) azurefile` command would fail to re-build the binary for each architecture. The amd64 build was still in the dependency list for the `container-all` target, and subsequent container build commands would simply use the previously built amd64 binary. …

chore: Fix arm64 container build

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go

/kind cleanup
Currently, if you request a 1MiB volume using the in-tree driver, then the corresponding created PVC has a capacity of 1 GiB. We currently create a backend disk that's rounded up to the nearest GiB, but the PVC uses the capacity initially specified, which is different from the in-tree driver.
This PR updates the CSi driver to 
Fixes #
```
Updates the CreateVolumeResponse to use a rounded GiB of the specified request.
```

Adjust PVC capacity to mirror in-tree behavior

---

test/performance/kubestone-storageclass.yaml

fix perfProfile in the storageclass for performance test
/kind bug
Fixes the stale perfProfile in the performance test related yaml
Fixes #
```
none
```

bug: fix perfProfile in the storageclass for performance test

---

Makefile
pkg/azuredisk/device_perf_optimization.go
pkg/azuredisk/device_perf_optimization_helper.go
pkg/azuredisk/device_perf_optimization_linux.go
pkg/azuredisk/device_perf_optimization_unsupported.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_v2.go
test/e2e/pre_provisioning_test.go

/kind cleanup
chore: little refactor of perf_optimization code
Fixes #
```
none
```

chore: little refactor of perf_optimization code

---

docs/enhancements/feat-add-ability-to-tune-azuredisk-performance-parameters.md

cleaning up the kep document
Fixes #
```
none
```

chore: clean-up perf optimization kep document

---

deploy/example/nginx-pod-azuredisk-inline.yaml
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/testsuites.go

/kind test
original test should be fixed by https://github.com/kubernetes/kubernetes/pull/101495, re-renable statefulset e2e test
Fixes #703
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/895/pull-azuredisk-csi-driver-e2e-multi-az/1404979802825297920/build-log.txt
```
[91m[1m• Failure [75.948 seconds][0m
Dynamic Provisioning
[90m/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:40[0m
[multi-az]
[90m/home/prow/go/src/sigs.k8s.io/azuredisk-csi-driver/test/e2e/dynamic_provisioning_test.go:47[0m
[91m[1mshould create a volume on demand and …
```

test: re-renable statefulset e2e test

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_tester.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
test/e2e/testsuites/specs.go

/kind test
If the test is ran in a region that supports ZRS, it will set storage class parameters to use ZRS. 
Fixes #
```
none
```

test: added check to test ZRS in dynamically provisioned test suite 

---

pkg/azuredisk/nodeserver.go

/kind bug
Add `nouuid` mount option to all XFS mounts to be able to mount a volume and its restored snapshot on the same node. Without the option, such a mount fails, because XFS detects that two different volumes with the same filesystem UUID are being mounted.
Fixes #954
```
It is now possible to mount a volume with XFS filesystem and its restored snapshot on the same node.
```

Disable uuid checks on XFS

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go

/kind bug
fix: panic when vm size not in SkuMap table
If vm size is not in skuMap now, (e.g. standard_nd12s), `csi-azuredisk-node` DeamonSet would crash now.
This PR print a warning if vm size is not in supported list.
Fixes #
- driver node panic is like following:
```
I0901 15:25:01.078827       1 skus.go:120] PopulateNodeAndSkuInfo: Starting to populate node and disk sku information.
I0901 15:25:01.093092       1 skus.go:139] PopulateNodeAndSkuInfo: Populated node and disk sku information. NodeInfo=&{Standard_ND12s 0 eastus 0 0 0 0 0 0}
F0901 15:25:01.093111       1 azuredisk.go:195] Failed to get node info. Error: …
```

fix: panic when vm size not in SkuMap table

---

docs/driver-parameters.md
pkg/azureconstants/azure_constants.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
test/e2e/dynamic_provisioning_test.go

/kind feature
Allows useragent to be set through the storage class
Fixes #
```
none
```

feat: allow storage class setting of useragent

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind feature
feat: expose metadata for static PV attachment
Fixes #
```console
NAME                                                                   ATTACHER             PV                                         NODE                           ATTACHED   AGE
csi-b848a2790e08e279bd52b47c1db0177d5d804cfbccc64e28b3392028f972527d   disk.csi.azure.com   pv-azuredisk                               aks-disk-18870927-vmss000000   true       10m
apiVersion: storage.k8s.io/v1
kind: VolumeAttachment
metadata:
annotations:
csi.alpha.kubernetes.io/node-id: aks-disk-18870927-vmss000000
creationTimestamp: "2021-09-03T10:46:59Z"
finalizers:
- …
```

feat: expose metadata for static PV attachment

---

deploy/csi-azuredisk-controller.yaml
deploy/install-driver.sh
pkg/azurediskplugin/main.go

/kind feature
feat: support disable-avset-nodes in install-driver.sh script
This PR is mainly for fixing e2e tests on capz with vmss & vmas mixed node pools. 
Fixes #
```console
./deploy/install-driver.sh master local,snapshot,enable-avset
```
Should set `disable-avset-nodes` as `true` for non mixed node pools, otherwise this driver would introduce uncessary vm list operations.
https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_azuredisk-csi-driver/1007/pull-azuredisk-csi-driver-e2e-single-az/1435169955581530112/build-log.txt
```
<*errors.errorString | 0xc000765220>: {
s: "Attach volume …
```

feat: support disable-avset-nodes in install-driver.sh script

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/fake_azuredisk_v2.go
pkg/azurediskplugin/main.go
pkg/mounter/fake_safe_mounter.go
pkg/mounter/safe_mounter_unix.go
pkg/mounter/safe_mounter_unix_test.go
pkg/mounter/safe_mounter_windows.go

/kind feature
feat: switch back to csi-proxy v1beta interface on Windows due to breaking change
Before k8s 1.22, all default windows disk type is MBR, and `Type` of `Get-Partition` for MBR disk is `IFS`, PR(https://github.com/kubernetes-csi/csi-proxy/pull/145) brings the breaking change. This PR switch back to csi-proxy v1beta interface on Windows until the new release(csi-proxy v1.1.0) with the fix is released.
Fixes https://github.com/Azure/AKS/issues/2568
/hold
```
feat: switch back to csi-proxy v1beta interface on Windows
```

feat: switch back to csi-proxy v1beta interface on Windows

---

pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go

/kind bug
fix: missing static PV data in VolumeAttachments
Fixes #
```
fix: missing static PV data in VolumeAttachments
```

fix: missing static PV data in VolumeAttachments

---

pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

Currently, v1 and v2 drivers have separate implementation for initializing the cloud provider. This PR is to refactor and merge these differences in order to eliminate any duplicate code.  
Fixes #
```
none
```

chore: Refactoring cloud provider initialization to merge v1 and v2 driver implementations.

---

Makefile

/kind cleanup
The pipeline used to build and publish container images to the MCR supports the use of environment variables, but requires their value be used to customize the build and not just their presence. In order to support building both the V1 & V2 driver from the same pipeline, this PR changes the Makefile to rely on the value of the `BUILD_V2` environment variable to determine whether to build the V1 or V2 driver.
Although the V2 driver will be built from the `main_v2` branch, this change is necessary on master to correctly build the V1 driver and avoid inadvertently building and publish an incomplete V2 driver image from master when the pipeline definition is updated.
Fixes # …

chore: MCR pipeline support for V2 driver build

---

Makefile

Reverts kubernetes-sigs/azuredisk-csi-driver#1106

Revert "cleanup: remove arm64 build workaround"

---

test/utils/check_driver_pods_restart.sh

/kind cleanup
The `test/utils/check_driver_pods_restart.sh` currently fails with the following syntax error:
```log
2022/03/04 13:45:00 Check driver pods if restarts ...
check the driver pods if restarts ...
test/utils/check_driver_pods_restart.sh: line 38: [: 0 0 0 0 0: integer expression expected
======================================================================================
```
This PR fixes the script using a more straightforward way of getting the pods with non-zero restart counts.
Fixes #
```
none
```

chore: Fix script to check for driver pod restarts

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go
pkg/azurediskplugin/main.go
test/sanity/run-test.sh

/kind feature
fix: disable disk capacity check in CreateVolume
This could reduce on disk get operation in CreateVolume
Fixes #
<details>
```
I0310 12:04:21.351288       1 utils.go:77] GRPC call: /csi.v1.Controller/CreateVolume
I0310 12:04:21.351315       1 utils.go:78] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.disk.csi.azure.com/zone":"westus2-1","topology.kubernetes.io/zone":"westus2-1"}},{"segments":{"topology.disk.csi.azure.com/zone":"","topology.kubernetes.io/zone":"0"}}],"requisite":[{"segments":{"topology.disk.csi.azure.com/zone":"westus2-1","topology.kubernetes.io/zone":"westus2-1"}},{"seg …
```

fix: disable disk capacity check in CreateVolume

---

pkg/azurediskplugin/Dockerfile
pkg/azurediskplugin/Windows.Dockerfile

/kind bug
fix: CVE issues in image build
Fixes #
```console
+-------------+------------------+----------+-------------------+-----------------+---------------------------------------+
|   LIBRARY   | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION  |                 TITLE                 |
+-------------+------------------+----------+-------------------+-----------------+---------------------------------------+
| libc-bin    | CVE-2021-33574   | CRITICAL | 2.[31](https://github.com/kubernetes-sigs/azuredisk-csi-driver/runs/5707112390?check_suite_focus=true#step:6:31)-13+deb11u2   | 2.31-13+deb11u3 | glibc: mq_notify …
```

fix: CVE issues in image build

---

pkg/controller/common.go
pkg/provisioner/crdprovisioner.go

/kind bug
* With the asynchronous attach feature, it is possible for `ControllerUnpublishVolume` request to be issued while the volume attachment operation is happening asynchronously in the background.
* In this case, the `AzVolumeAttachment.Status.Detail` will not be populated and therefore, the `CrdProvisioner` will make a deletion request for the CRI without making a detachment request.
* In which case, the volume attachment gets lost and its associated volume will not be able to be deleted.
Fixes #
```
none
```

[V2] bug: UnpublishVolume should not delete the CRI without detaching

---

test/utils/check_driver_pods_restart.sh

There is an issue in the test/utils/check_driver_pods_restart.sh where POD_WITH_RESTART is not defined. It is meant to be set in a for-loop from the PODS_WITH_RESTARTS array. This issue manifests when running e2e tests, but it does not cause a test failure. I cherrypicked Ed's fix from master and brought it to main_v2. 
/kind bug
This fixes an issues with a script that runs during e2e tests.
Fixes #1284 
- I cherrypicked Ed's change because I thought that this would be the best way to maintain git hygiene. Please let me know if there is a better method.
- I also expected that the bot would prompt me to sign the CLA, as I do not …

[V2] fix: Fix script to check for driver pod restarts🐞

---

pkg/azureconstants/azure_constants.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_v2.go

/kind cleanup
chore: refine metrics naming
Fixes #
<details>
```
"Observed Request Latency" latency_seconds=2.50810107 request="azuredisk_csi_driver_controller_create_volume" resource_group="kubetest-oef2qxb0" subscription_id="0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e" source="disk.csi.azure.com" volumeid="/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-oef2qxb0/providers/Microsoft.Compute/disks/pvc-66ccdc93-6388-469d-9ef6-334c448cd786" result_code="succeeded"
"Observed Request Latency" latency_seconds=5.291692881 request="azuredisk_csi_driver_controller_delete_volume" resource_group="kubetest-oef2qxb0" …
```

chore: refine metrics naming

---

test/e2e/azdiskschedulerextender_test.go
test/e2e/driver/azuredisk_driver.go
test/e2e/dynamic_provisioning_test.go
test/e2e/pre_provisioning_test.go
test/e2e/testsuites/azdiskschedulerextender_pod_scheduling_on_failover_multiple_pv_perf_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_with_replicas_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_scale_up_with_replicas.go
test/integration/controller/controller_test.go
test/podFailover/controller/main.go
test/resources/deployment.go
test/resources/pvc.go
test/resources/resource_setup.go
test/resources/statefulset.go
test/resources/utils.go
test/resources/volumes.go
test/scale/azdisk_scale_test.go
test/upgrade/upgrade_test.go

/kind cleanup
* e2e test relies on storage class parameters for many of its functionalities and the sku name field is handled case sensitive in these test utils when it should be case insensitive.
* This is causing certain bugs as below:
A ZRS disk is created for multi-az case but with storage class parameter sku name field hard coded.
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/04aba1e20ce3598d77e359198e4579335eb27024/test/e2e/dynamic_provisioning_test.go#L1652
But because the test util expects `consts.SkuNameField`, which is in lowercase, as storageclass parameter key, we never end up setting the volume's binding mode to `VolumeBindingImmediate` …

[V2] chore: e2e test util fixes

---

pkg/azureutils/azure_disk_utils.go

/kind bug
This PR fixes an issue where the `TestAttachDetachReconcile` and `TestAzVolumeControllerReconcile` unit tests are failing sporadically. This occurs mostly during the macOS build, but it is easy to trigger the race condition on Linux as well (at least on my machine).
You might execute the following commands to validate the fix:
```fish
for i in (seq 1 100); /usr/local/go/bin/go test -timeout 10m -run '^TestAttachDetachReconcile$' sigs.k8s.io/azuredisk-csi-driver/pkg/controller -race -count=1; end
for i in (seq 1 100); /usr/local/go/bin/go test -timeout 10m -run '^TestAzVolumeControllerReconcile$' sigs.k8s.io/azuredisk-csi-driver/pkg/controller -race -count=1; end
``` …

[V2] fix: fix issue where in/out param pointer was being written to, causing race condition🐞

---

pkg/azureconstants/azure_constants.go
pkg/azureutils/azure_disk_utils.go

/kind cleanup
* If `UpdateCRIWithRetry` fails within an untracked goroutine, it may leave the CRI in a transient state, unable to recover.
* To prevent this, if `UpdateCRIWithRetry` called from such goroutine fails with an error, it makes sense to exit the process and let a new leader take over to start the recovery.
* **Which issue(s) this PR fixes**:
Fixes #
```
none
```

[V2] chore: exit process on UpdateCRIWithRetry net errors for untracked goroutines

---

pkg/controller/common.go
pkg/controller/node_availability.go
pkg/controller/replica.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
test/e2e/testsuites/dynamically_provisioned_garbage_collection_replica_attachment_tester.go
test/resources/utils.go

/kind feature
"After volumes are garbage collected and attachment capacity opens up on a node, prompts an attempt to create previously failed replicas." - from original PR #1244 
I removed passing is copying `ctx` into the closure because it is not need. It passed in `deletionCtx` as `ctx` but `workflowCtx` is passed into `r.controllerSharedState.garbageCollectReplicas`. Because of this, I investigated this. Copying it into the closure is not needed because `context.Context` is immutable and the closure does not change the variable outside of its scope.
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/8cf65b5d12eb5e075b8e5ecc295c2df5576864b9/pkg/controller …

[V2] feat: add replica creation after volumes are garbage collected and space is freed up 🌈

---

test/const/test_consts.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_tester.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_with_replicas_tester.go
test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
test/resources/deployment.go
test/resources/statefulset.go
test/resources/utils.go

/kind bug
/kind flake
This change fixes a test issue in the several e2e tests, where we are looking for a file in pods to contain a certain string. The `framework.LookForStringInPodExec` method fails the test automatically if the command executed has a non-zero exit code. This can happen if the pod has not completed writing to the file. 
There are some additional methods like `framework.RunHostCmd` that we might consider using, but these assume the pod is running Linux. Because of this, I decided to roll our own method.
I changed name from `Exec` => `PollForStringInPodsExec` to make it clearer that the command passed in will be executed multiple times.
There is some …

[V2] fix: fix issue where file is read before written in e2e tests 🐞

---

test/podFailover/README.md

master branch doesn't have the specified resources
Fixes #
```
none
```

[V2] doc: update pod failover test links

---

pkg/azdiskschedulerextender/azdiskschedulerextender.go

/kind bug
* AzDiskScheduler was filtering results based on volume access mode checks and this was leading to early exits.
* It should not filter based on volume access mode checks but instead prioritize.
Fixes #
```
none
```

[V2] bug: azdiskscheduler volume access mode check for prioritize instead of filter

---

pkg/azureconstants/azure_constants.go
pkg/controller/azvolume.go
pkg/controller/azvolume_test.go
pkg/controller/common.go
pkg/controller/replica.go
pkg/controller/replica_test.go
pkg/provisioner/crdprovisioner.go
pkg/provisioner/crdprovisioner_test.go
pkg/watcher/conditionwaiter.go
pkg/watcher/conditionwatcher.go

instead of requeuing
/kind chore
* `AzVolume` controller originally relied on reconciler requeue to wait for replica `AzVolumeAttachment` to be fully deleted but this can lead to huge backoffs causing a significant delay in volume deletion.
* This PR leverages condition watcher / waiter component to have `AzVolume` controller wait for the replica AzVolumeAttachments to be deleted to avoid over issuance of requeue
* And replaces existing polling in replica controller with event triggered waiter package.
Fixes #
```
none
```

[V2] chore: DeleteVolume should wait for replicas to be fully deleted

---

pkg/azuredisk/azure_common_windows.go
pkg/provisioner/nodeprovisioner_windows.go
test/e2e/dynamic_provisioning_test.go

/kind bug
1. Ensures the volume cache is flushed to disk during unmount. (Merge of #1350 from master.)
2. Re-enable pod failover tests on Windows to debug failures.
Fixes #1349 
```
none
```

[V2] fix: cache data loss issue on Windows when unmount disk

---

pkg/azdiskschedulerextender/azdiskschedulerextender.go
pkg/azdiskschedulerextender/azdiskschedulerextender_test.go

…V2 driver disks.
Added on optimization in the extender to skip processing on prioritize and filter calls for non-v2 driver volumes. Currently, only prioritize is skipped until we fix #1097 in the controller but the functionality is added for both calls. 
Fixes #
```
none
```

[V2] feat: Skipping prioritize/(filter) extender processing for non-v2 disks

---

pkg/azuredisk/nodeserver_v2.go

[V2] fix: Fix for intermittent failure for NodeStageVolume request

---

pkg/azureutils/azure_disk_utils.go
pkg/controller/attach_detach.go
pkg/controller/azvolume.go
pkg/controller/pv.go
pkg/controller/replica.go
pkg/controller/volumeattachment.go
pkg/provisioner/crdprovisioner.go

/kind bug
/kind cleanup
/kind regression
1. Improves type safety of `azureutils.UpdateCRIWithRetry` and fix usage of `azureutils.AppendUpdateFunc` so that update functions are chained correctly. Update function chains are used on the operation error recovery path. The previous implementation wasn't chaining correctly and prevented retries of failed operations from succeeded.
2. Ensures the final CRI status update occurs when the operation context is cancelled, or its deadline is exceeded.
Fixes #
```
none
```

[V2] fix: Fix CRI update on error recovery

---

test/e2e/testsuites/dynamically_provisioned_pod_node_selector.go

/kind test
/kind flake
The pod node selector test needs to wait longer for pod startup because Windows CAP-Z clusters can take more than 5 minutes to pull the image.
Fixes #
```
none
```

[V2] flake: pod node selector test needs to wait long for pods on Windows

---

test/scale/azdisk_scale_test.go
test/scale/flags.go

/kind test
**What this PR does / why we need it:**
creating a flag to indicate the number of replicas to run scale tests
**Which issue(s) this PR fixes:**
Fixes #
**Requirements:**
**Special notes for your reviewer:**
**Release note:**
`none`

[V2] test: adding flag for replicas to run scale tests

---

deploy/csi-snapshot-controller.yaml

As per [KEP 2067](https://github.com/kubernetes/enhancements/blob/master/keps/sig-cluster-lifecycle/kubeadm/2067-rename-master-label-taint/README.md), `node-role.kubernetes.io/master` taint is replaced with `node-role.kubernetes.io/control-plane`. However, the csi-snapshot-controller is using `node-role.kubernetes.io/controlplane` toleration (note that `controlplane` doesn't have a period). This PR proposes a fix for this issue by adding a new `node-role.kubernetes.io/control-plane` toleration while keeping the old one because of backward compatibility.
None
This PR updates only "template" manifests. Should we …

chore: add node-role.kubernetes.io/control-plane to csi-snapshot-controller

---

pkg/azureconstants/azure_constants.go
pkg/azuredisk/azuredisk_v2.go

**What this PR does / why we need it:**
- The RateLimiterLatency metric uses a HistogramVec imported from the metrics package to measure throttling in the driver
- Uses the metric library in client-go to enable and register the new metric in the `azuredisk_v2.go` file 
Which issue(s) this PR fixes:
Fixes #
**Requirements:**
**Special notes for your reviewer:
Release note:**

[V2] feat: add rate limiter latency metric to find throttling

---

test/scale/scale_test.go

In order to show test output for the scale test in Azure Dev Ops, I need a JUnit XML file output. The E2E tests currently write a JUnit XML file in a similar way.
/kind test
I read the report directory (ARTIFACTS environment variable) and write out a junit_01.xml file. This is similar to the use of the JUnit reporter in the e2e tests. 
```
none
```

[V2] test: add junit test output to scale test 🔧

---

test/podFailover/automation-run.yaml
test/podFailover/controller/main.go

/kind test
adding the ability to use a pre-created storage class in pod-failover tests
to widen the platforms that can be tested by the pod-failover tests
For example adding the ability to BYO storage class allows testing to be done
on AzDisk and AzStor without having to build many different images
```
none
```

[V2] chore: add BYO storage class for pod-failover tests

---

pkg/controller/common.go

/kind cleanup
[V2] Fix "Volume persistent-storage not csi" misclassified error log line
Fixes #1416
```
none
```

[V2] fix: Volume persistent-storage not csi error log

---

pkg/azurediskplugin/Windows.Dockerfile

/kind cleanup
Currently, we depend on "cached" version servercore from the GCR to build the driver image for Windows. Most Go programs require only the binaries from nanoserver, but also one binary (NetApi32) from servercore. "servercore" is very large, so we pull from the "cached" version to speed up builds. This cached version is built by the kubernetes repo for the linux/amd64 and linux/arm64 platforms.
However, in ADO, we are only able to pull from MCR images. In order to provide this functionality while preserving the speedup from using the servercore-cache outside of ADO, I added the `SERVERCORE_IMAGE` and `SERVERCORE_PLATFORM` build-args to let me set `SERVERCORE_PLATFORM=windows/amd64` and …

[V2] chore: Add ability to point at different image for servercore 🔧

---

pkg/azuredisk/nodeserver_test.go
pkg/csi-common/server_test.go

/kind test
add nodeserver.go unit test
Fixes #1424
```
none
```

test: add nodeserver.go unit test

---

pkg/controller/attach_detach.go
pkg/controller/attach_detach_test.go
pkg/controller/azdrivernode.go
pkg/controller/azdrivernode_test.go
pkg/controller/azvolume.go
pkg/controller/azvolume_test.go
pkg/controller/common.go
pkg/controller/common_test.go
pkg/controller/node_availability.go
pkg/controller/node_availability_test.go
pkg/controller/pod.go
pkg/controller/pod_test.go
pkg/controller/pv.go
pkg/controller/pv_test.go
pkg/controller/replica.go
pkg/controller/replica_test.go
pkg/controller/shared_state.go
pkg/controller/volumeattachment.go
pkg/controller/volumeattachment_test.go

/kind cleanup
Currently, the SharedState struct and its related functions are scattered through source files in the pkg/controller package. This makes maintaining them harder. This PR refactors the SharedState struct and moves it and its related method to a separate file, making it easier to maintain.
Fixes #1412
Adding SharedState specific unit tests will be taken care as part of a separate PR.
```
none
```

[V2] chore: Move SharedState struct and related functions to shared_state.go

---

.github/workflows/codespell.yml
cmd/az-analyze/README.md
cmd/az-log/cmd/get.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver_test.go
pkg/azureutils/azure_disk_utils_test.go
pkg/optimization/device_perf_helper.go
test/e2e/testsuites/dynamically_provisioned_pod_failover_with_replicas_tester.go

/kind cleanup
Fixing codespell test errors
```
none
```

[V2] fix: fixing codespell errors

---

.github/workflows/static.yaml
.github/workflows/trivy-v2.yaml
.github/workflows/trivy.yaml

GitHub Actions has deprecated the `ubuntu-18.04` runner. This morning, they conducted a scheduled blackout:
https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/
I replaced `ubuntu-18.04` with `ubuntu-latest` in our GitHub workflows, as we already use it in the other workflow files. 
/kind cleanup
Fixes #
```
none
```

[V2] build: update ubuntu-18.04 to ubuntu-latest in GitHub workflows 🏭

---

pkg/controller/replica_test.go
pkg/controller/shared_state.go
pkg/controller/shared_state_test.go

/kind cleanup
Added Unit Tests for the SharedState struct and methods
Fixes #1412
```
none
```

[V2] chore: added unit tests for SharedState

---

.codespellrc
.github/workflows/codespell.yml
.pre-commit-config.yaml
docs/csi-dev.md
hack/verify-helm-chart-files.sh

/kind cleanup
Adds pre-commit and pre-push validation of changes. Requires the installation of pre-commit hooks as documented in [csi-dev.md](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/231f1ceef00d8dd5f3c57f3bcbbe2b3daa67f88a/docs/csi-dev.md)
Fixes #
```
none
```

[V2] chore: add pre-commit and pre-push validation

---

test/podFailover/controller/chart/templates/podfailurecrd.yaml

/kind bug
pod failure status listed failuretype and heartbeat as required
fields making the workload pods fail.
changing crd definition to make these fields optional
```
none
```

[v2] fix: fixing pod failure status

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/util/util.go

/kind bug
fix: Ultra Disk DefaultDiskMBPSReadWrite calc issue
This PR fixed a corner case with following Ultra Disk DefaultDiskMBPSReadWrite default value issue:
<details>
```
I0831 14:31:34.966292       1 utils.go:77] GRPC call: /csi.v1.Controller/CreateVolume
I0831 14:31:34.966314       1 utils.go:78] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.disk.csi.azure.com/zone":""}}],"requisite":[{"segments":{"topology.disk.csi.azure.com/zone":""}}]},"capacity_range":{"required_bytes":70367670435840},"name":"pvc-65ca543f-75f1-4ba8-9a2e-b7bb050f442d","parameters":{"cachingMode":"None","csi.storage.k8s.io/pv/name":"pvc-65ca543f-75f1-4ba8-9a2e-b7bb050f442d","csi.storage.k8s.io/pvc/name":"pvc-azu …
```

fix: Ultra Disk DefaultDiskMBPSReadWrite calc issue

---

test/e2e/manifest/pod-failover.json
test/podFailover/workload/chart/templates/workload.yaml
test/podFailover/workload/scenarios/azDiskV2-Replicas.yaml
test/podFailover/workload/scenarios/azDiskV2-noReplicas.yaml

/kind feature
adding ability to specify workload type to pod failover tests
```
none
```

fix: adding optional workload value to pod-failover

---

test/e2e/manifest/pod-failover.json
test/podFailover/controller/cmd/main.go
test/podFailover/workload/chart/templates/workload.yaml
test/podFailover/workload/scenarios/azDiskV2-Replicas.yaml
test/podFailover/workload/scenarios/sameNodeFailover.yaml

/kind bug
Adds scheduler extender to pod failover workload pods so v2 with replica works as intended
Fixes same node failovers
Changes SKU of pod failover template to make sure the max disks is enough
```
none
```

[V2] fix: adding scheduler to pod-failover workload pods

---

test/podFailover/workload/chart/templates/workload.yaml

/kind bug
- adding cluster provisioner variable so scheduler name is not set when using AKS CLI clusters
```
none
```

[V2] fix: adding cluster provisioner variable

---

pkg/controller/attach_detach.go
pkg/controller/attach_detach_test.go
pkg/controller/azdrivernode_test.go
pkg/controller/azvolume_test.go
pkg/controller/common.go
pkg/controller/replica.go
pkg/controller/replica_test.go
pkg/controller/shared_state.go
pkg/provisioner/crdprovisioner.go
pkg/provisioner/crdprovisioner_test.go

/kind feature
* This backloads API DELETE calls on AzVolumeAttachment objects to mitigate API server throttling.
Fixes #
```
none
```

[V2] feat: backload API DELETE call to deload api server calls upon detachment

---

pkg/provisioner/crdprovisioner.go

/kind cleanup
Adds the caller value to the workflows for `CrdProvisioner.WaitFor(Attach|Detach)`.
Fixes #
```
none
```

[V2] chore: add caller to WaitFor(Attach|Detach)

---

pkg/controller/azdrivernode.go
pkg/controller/azvolume.go
pkg/controller/common.go
pkg/controller/shared_state.go

* Replica AzVolumeAttachments need to be detached and deleted during driver uninstall.
* This PR is necessary to unblock other tasks as 1) updating driver uninstall que and 2) adding allocation map.
Fixes #
```
none
```

[V2] fix: replicas aren't getting cleaned up during driver uninstall

---

pkg/controller/attach_detach.go
pkg/controller/attach_detach_test.go
pkg/controller/azdrivernode.go
pkg/controller/azdrivernode_test.go
pkg/controller/common.go
pkg/controller/common_test.go
pkg/controller/node_availability_test.go
pkg/controller/pod_test.go
pkg/controller/replica_test.go
pkg/controller/shared_state.go
pkg/controller/shared_state_test.go

/kind bug
Fixes #
**Passed tests:**
(node's max attachment count is 8. disk MaxShares = 2)
2 nodes, 8 disks
3 nodes, 11 disks
20 nodes, 20 disks
30 nodes, 30 disks
**How I verified:**
$kubectl get azvolumeattachment -A | grep Replica and 
$kubectl get azvolumeattachment -A | grep Primary 
can print out correct azvolumeattachments
```
none
```

[V2] fix: add nodeDiskAvailabilityMap

---

Makefile

/kind bug
/kind test
When TEST_CCM is enabled, CCM will be built with [ci-build-azure-ccm.sh](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/scripts/ci-build-azure-ccm.sh). However, this will cause the env variable naming conflict: env variable IMAGE_TAG is used by this file for CCM tag at line 46:https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/scripts/ci-build-azure-ccm.sh#L46, and at the same time it is also used by the CSI Driver make file with a different meaning for the CSI tag: https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/Makefile#L37. Because of that, the CSI image generated will have the wrong image URI and thus cannot be pushed to the ACR …

[chore] Fix E2E failure in VMSS Flex cluster

---

pkg/azuredisk/azuredisk_test.go
pkg/azureutils/azure_disk_utils_test.go
test/integration/integration_test.go
test/sanity/sanity_test.go
test/utils/credentials/credentials_test.go

/kind cleanup
A testing cleanup.
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
```go
func TestFoo(t *testing.T) {
// before
key := "ENV"
originalEnv := os.Getenv(key)
if err := os.Setenv(key, "new value"); err != nil {
t.Fatal(err)
}
defer func() {
if err := os.Setenv(key, originalEnv); err != nil {
t.Logf("failed to set env %s back to original value: %v", key, err)
}
}()
// after
t.Setenv(key, "new value")
}
``` …

test: use `T.Setenv` to set env vars in tests

---

pkg/mounter/safe_mounter_v1beta_windows.go

/kind bug
fix: volume metrics on Windows csi-proxy v1beta
Fixes #
- correct `NodeGetVolumeStats` response
```
I1128 13:06:41.438471    6376 utils.go:77] GRPC call: /csi.v1.Node/NodeGetVolumeStats
I1128 13:06:41.438998    6376 utils.go:78] GRPC request: {"volume_id":"/subscriptions/0e46bd28-a80f-4d3a-8200-d9eb8d80cb2e/resourceGroups/kubetest-5zrwevie/providers/Microsoft.Compute/disks/pvc-b7977a80-d0b0-4b7a-bf70-10e16ae07123","volume_path":"c:\\var\\lib\\kubelet\\pods\\e94d925a-9045-4fe8-a834-d7403a5dade2\\volumes\\kubernetes.io~csi\\pvc-b7977a80-d0b0-4b7a-bf70-10e16ae07123\\mount"}
I1128 13:06:41.982617    6376 …
```

fix: volume metrics on Windows csi-proxy v1beta

---

pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/interface_v2.go
pkg/azuredisk/mockprovisioner/interface.go
pkg/azureutils/informer_common.go
pkg/controller/common_test.go
pkg/controller/shared_state.go
pkg/provisioner/crdprovisioner.go
pkg/provisioner/crdprovisioner_test.go
pkg/watcher/conditionwatcher.go
test/integration/controller/controller_test.go

/kind cleanup
Start informers centrally and share them with crdprovisioner and controllers to prevent dependency.
Fixes #
```
none
```

[V2] refactor: start informers in one place

---

pkg/provisioner/crdprovisioner.go

/kind bug
* The PR addresses scenarios as below:
1. `ControllerCreateVolume` fails with a timeout
2. `CloudProvisioner.CreateVolume` eventually fails and updates `AzVolume` with an error and `VolumeCreationFailed` state.
3. `crdProvisioner` will reset `AzVolume.Status.State` to `VolumeOperationPending` with the expectation for `azvolume controller` to retrigger `createVolume` operation and update the state to `VolumeCreating`. 
4. However, given the reconciler concurrency limit in `azvolume controller`, the state transition may not happen within `ControllerCreateVolume` context timeout.
5. If the state remains in `VolumeOperationPending` on the next `ControllerCreateVolume` call, the driver emits a `unexpected create …

[V2] fix: don't return unncessary error in crdProvisioner.CreateVolume

---

pkg/azureutils/azure_disk_utils.go
pkg/controller/attach_detach.go
pkg/controller/azvolume.go
pkg/controller/common.go
pkg/controller/common_test.go
pkg/controller/node.go
pkg/controller/pod_test.go
pkg/controller/pv.go
pkg/controller/pv_test.go
pkg/controller/shared_state.go

/kind cleanup
* Current PV controller issues a delete request for `AzVolume` CRI upon seeing a deletionTimestamp for `PV` but this can be problematic when user issues `ControllerUnpublishVolume` after marking the preprovisioned PV with a deletion timestamp, as 
`AzVolume` may no longer be able to be found in cluster when trying to unpublish the volume, ultimately resulting in detach failures.
* Also, when deleting `AzVolume` for pre-provisioned volume, `PV controller` needs to be able to retrigger a failed deletion.
* The PR addresses these issue.
Fixes #
```
none
```

[V2] fix: handle pre-provisioned volume deletion at the right time

---

pkg/controller/attach_detach.go
pkg/controller/attach_detach_test.go

/kind bug
This PR fixes an issue in 1AzVolumeAttachment1 recovery. If the 1AzVolumeAttachment1 is in the `Attaching` state when the driver crashes, we recover the state by setting the status to `AttachmentPending`, as we do not know where in the `Attaching` state the controller was in when it crashed.
However, the code is checking if `azVolumeAttachment.Status.Detail` is `nil` prior to calling `triggerAttach`. Setting the `Status.Detail` and `Status.Error` to `nil` will ensure that the driver completes the attachment upon recovery. 
This issue was exposed because we are seeing driver OOM issues.
```
none
```

[V2] fix: clear status error and detail in AzVolumeAttachment recovery if in in Attaching state 🐞

---

test/podFailover/workload/chart/templates/workload.yaml

/kind bug
- using scheduler name based on install method, not cluster provisioner

[V2] fix: changing scheduler name logic to install method

---

pkg/controller/common.go
pkg/controller/replica.go
pkg/controller/shared_state.go

/kind bug
We saw [`manageReplicas`](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/3f5114357ac4c342eef8fd174d1e0c706edb11d3/pkg/controller/shared_state.go#L1233) is called twice for one volume to create its replica attachment. The root causes are:
1. incorrect logic in [`shouldRequeueReplicaOperation`](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/3f5114357ac4c342eef8fd174d1e0c706edb11d3/pkg/controller/common.go#L249) to return `true` so that the replica operation is added to queue again.
2. When the replica attachment failed with non-retriable error, the CRI will be deleted and open another [goroutine](https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/3f5114357ac4c342eef8fd174d1e0c …

[V2] fix: prevent requesting replica attachment in a row for one volume

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/fake_azuredisk_v2.go

/kind bug
fix: panic when allow-empty-cloud-config is set
Fixes #1696
```
fix: panic when allow-empty-cloud-config is set
```

fix: panic when allow-empty-cloud-config is set

---

Makefile
test/external-e2e/run.sh

/kind cleanup
`buildkit` v0.11.0 enables provenance attestation in the image manifest by default. This is causing our local builds to fail with the following error when generating the manifest list:
```sh
docker manifest create --amend xxx/azuredisk-csi:latest_v2  xxx/azuredisk-csi:latest_v2-linux-amd64  xxx/azuredisk-csi:latest_v2-linux-arm64  xxx/azuredisk-csi:latest_v2-windows-1809-amd64  xxx/azuredisk-csi:latest_v2-windows-20H2-amd64  xxx/azuredisk-csi:latest_v2-windows-ltsc2022-amd64
docker.io/xxx/azuredisk-csi:latest_v2-linux-amd64 is a manifest list
make[1]: *** [Makefile:269: push-manifest] Error 1
make[1]: Leaving directory '/home/xxx/go/src/xxx/azuredisk-csi-driver'
make: *** [Makefile:129: e2e-bootstrap] Error …
```

[V2] build: disable provenance attestation to work around docker issue

---

go.mod
vendor/modules.txt

/kind cleanup
Pin `k8s.io/dynamic-resource-allocation` to enable offline build & depencency check.
This has failed:
```
$ go list -mod=readonly -m all
go: k8s.io/dynamic-resource-allocation@v0.0.0: invalid version: unknown revision v0.0.0
```
I don't know why, but `go mod tidy` with go 1.18.10 moved `github.com/Azure/go-autorest/autorest/to` to the last `require` section too.
Fixes #
```
none
```

Pin k8s.io/dynamic-resource-allocation version

---

pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go

/kind bug
fix: second expand volume failure on Ubuntu 22.04
This is related to bug: https://bugzilla.redhat.com/show_bug.cgi?id=2128863 on Ubuntu 22.04, second `resize2fs` always failed with following error:
```
Warning  FailedMount             0s (x5 over 8s)  kubelet                  MountVolume.Setup failed while expanding volume for volume "pvc-8e0170f3-c7f1-413d-909f-5f1c7487f098" : Expander.NodeExpand failed to expand the volume : rpc error: code = Internal desc = could not resize volume "/subscriptions/xxx/resourceGroups/mc_andy-aks125_andy-aks125_eastus2/providers/Microsoft.Compute/disks/pvc-8e0170f3-c7f1-413d-909f-5f1c7487f098" ("/dev/sdc"):  resize of device /dev/sdc failed: exit status 1. resize2fs output: …
```

fix: second expand volume failure on Ubuntu 22.04

---

pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/interface_v2.go
pkg/azuredisk/mockprovisioner/interface.go
pkg/controller/shared_state.go
pkg/provisioner/crdprovisioner.go
pkg/provisioner/crdprovisioner_test.go
pkg/provisioner/fake_crdprovisioner.go
test/upgrade/flags.go

/kind bug
* Currently, only CrdProvisioner.PublishVolume is capable of detaching replicas to make resources available for primary attachment.
* However, due to async attach behavior and possible races between CrdProvisioner and the CRD controllers, CrdProvisioner.WaitForAttach also needs to be able to detach replicas for primary.
Fixes #
```
none
```

[V2] bug: WaitForAttach call should also be able to detach replicas for primary

---

pkg/controller/attach_detach.go
pkg/controller/replica.go

/kind bug
When running the scale test with replicas, we saw that cloudprovisioner could return retriable error at the first attempt to create a replica AzVolumeAttachment, and then return not retriable error due to throttling. Under this scenario, the driver will delete the CRI without detach, so we lose the track of that disk attachment that would cause exhausting MaxShares or not being able to delete disks that are still attached to VMs. This PR is to handle inconsistent error types returned during retries.
This PR also fixes that we only add `ReplicaVolumeAttachRetryAnnotation` to replica AzVolumeAttachment.
Fixes #
**Release …

[V2] fix: replica AzVolumeAttachment retries return inconsistent error type

---

test/podFailover/workload/cmd/main.go

/kind cleanup
- making report pod failover downtime a goroutine
- hoping to increase the chance that pods will report timestamps everytime they come online

[V2] chore: reporting pod failover downtime async

---

deploy/example/statefulset-nonroot.yaml
deploy/example/statefulset-nozone.yaml
deploy/example/statefulset.yaml
deploy/example/windows/statefulset.yaml

The volume.beta.kubernetes.io/storage-class annotation is deprecated since v1.9. 
Changed it to a new way to deal with some e2e issues.

test(e2e): change the storageclass configuration method in the test file

---

test/external-e2e/run.sh
test/utils/azuredisk_log.sh

test: fix external e2e test failure
Fixes #
test: fix external e2e test failure
```
none
```

[release-1.26] test: fix external e2e test failure

---

deploy/csi-azuredisk-controller.yaml
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/fake_azuredisk.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_volume_snapshot_cross_region_tester.go
test/e2e/testsuites/testsuites.go

/kind feature
feat: add copy snapshot in cross region directly
Fixes #1694
test log
```
I0327 11:35:05.765036       1 controllerserver.go:893] begin to create snapshot(local_snapshot-4d074b39-8a9b-493a-a101-dc110548227b, incremental: true) under rg(mc_aks-yxytest_group_aks-yxytest_eastus) region(eastus)
I0327 11:35:08.224270       1 controllerserver.go:902] create snapshot(local_snapshot-4d074b39-8a9b-493a-a101-dc110548227b) under rg(mc_aks-yxytest_group_aks-yxytest_eastus) region(eastus) successfully
I0327 11:35:08.273543       1 util.go:124] Send.sendRequest got response with ContentLength -1, StatusCode 200 and responseBody length …
```

feat: add copy snapshot in cross region directly

---

docs/driver-parameters.md
pkg/azureconstants/azure_constants.go
pkg/azuredisk/controllerserver.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
test/e2e/dynamic_provisioning_test.go

/kind feature
feat: add attachDiskInitialDelay parameter in storage class
Fixes #
```
feat: add attachDiskInitialDelay parameter in storage class
```

feat: add attachDiskInitialDelay parameter in storage class

---

pkg/azurediskplugin/main.go
pkg/controller/attach_detach.go
pkg/controller/attach_detach_test.go

/kind bug
This PR fixes an issue when context.DeadlineExceeded occurs when trying to attach a replica volume attachment to a node. The code had an issue where 'err' was referenced while 'attachErr' should have been referenced. 
As a result, the `disk.csi.azure.com/replica-volume-attach-retry: true` annotation was not added to the replica attachment CRI. When `disk.csi.azure.com/replica-volume-attach-retry` is not `true` and attachment failed, the CRI will be deleted and a new one will be created.
This caused a new CRI to be created to attach to a new node. This fails because the volume is already attached to the other node for which deadline exceeded. I added a test to check that the annotation gets added in this …

[V2] fix: retry annotation not being added for replica volume attachment CRI when context.DeadlineExceeded occurs on attach 🐞

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/fake_azuredisk.go
pkg/azurediskplugin/main.go

/kind bug
fix: Ultra and PremiumV2 disk snapshot delay issue
create snapshot on 100GB Ultra disk would requires 6min, this PR waits until it succeeds
<details>
- create snapshot on 100GB Ultra disk would requires 6min
```
I0830 14:08:22.405778       1 utils.go:77] GRPC call: /csi.v1.Controller/CreateSnapshot
I0830 14:08:22.405803       1 utils.go:78] GRPC request: {"name":"snapshot-43b7d797-d33b-4cfd-8e13-e048a8cc7a34","parameters":{"incremental":"true"},"source_volume_id":"/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/mc_andy-aks126_andy-aks126_eastus2/providers/Microsoft.Compute/disks/pvc-a9aaf673-1fce-440c-a365-55729223a1bf"}
I0830 14:08:22.405983       1 controllerserver.go:925] begin to create …
```

fix: Ultra and PremiumV2 disk snapshot delay issue

---

pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind bug
When creating the [cloud provider config file](https://cloud-provider-azure.sigs.k8s.io/install/configs/), one can specify the `location` in two (valid for Azure) formats:
* upper case with spaces, e.g. "East US"
* lower case with no spaces, e.g. "eastus"
The driver (as well as other applications making use of the config) will accept and work with both formats.
An issue only arises if nodes in the cluster are created in specific availability zones, e.g. "East US 2":
The topology key (`topology.disk.csi.azure.com/zone`) of the node will always be set to non zone.
The `CreateVolume` rpc of the controller server will be unable to schedule the disk in the correct zone, since the azuredisk topology key is set to an …

fix: ensure Kubernets conformant format for location

---

.github/workflows/codespell.yml
deploy/example/azure.json

doc: fix code spelling errors
Fixes #
```
none
```

doc: fix code spelling errors

---

hack/verify-helm-chart.sh

test: fix verify-helm-chart failure
```
helm chart index verified.
Running helm lint
==> Linting /home/prow/go/src/sigs.k8s.io/blob-csi-driver/charts/latest/blob-csi-driver
[INFO] Chart.yaml: icon is recommended
1 chart(s) linted, 0 chart(s) failed
Comparing image version between helm chart and manifests in deploy folder
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. …
```

test: fix verify-helm-chart failure

---

go.mod
hack/verify-gomod.sh
vendor/modules.txt

cleanup: fix k8s.io/endpointslice dependency
Fixes #2008
```
none
```

cleanup: fix k8s.io/endpointslice dependency

---

.github/workflows/static.yaml
.golangci.yml
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/identityserver.go
pkg/azuredisk/nodeserver.go
pkg/azurediskplugin/main.go
pkg/azureutils/fake_iohandler.go
pkg/csi-common/server_test.go
pkg/mounter/fake_safe_mounter.go
pkg/mounter/safe_mounter_unix.go
pkg/optimization/azure_skus_map.go
pkg/optimization/skus_test.go
pkg/os/filesystem/filesystem.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
test/e2e/testsuites/specs.go

/kind test
test: upgrade golangci/golangci-lint-action to v1.54
Fixes #
```
none
```

test: upgrade golangci/golangci-lint-action to v1.54

---

pkg/azuredisk/controllerserver.go

/kind bug
[bug] improve attach error message
csi-attacher has limit for attach/detach error message. When the CSI error message length is more than 1024, it will get error:
```
I1127 02:46:27.220987       1 csi_handler.go:258] Failed to save attach error to "csi-9a0cbb0637aadd0e423ee0c25225b5d8d84e377a1d8a90ab5e05f2872e9964e3": VolumeAttachment.storage.k8s.io "csi-9a0cbb0637aadd0e423ee0c25225b5d8d84e377a1d8a90ab5e05f2872e9964e3" is invalid: status.attachError.message: Too long: must have at most 262144 bytes
```
Because of it, volumeattachment cannot save error message from csi, then it only get timeout error in pod events.
Fixes # …

fix: improve disk attach/detach error message

---

test/e2e/dynamic_provisioning_test.go
test/e2e/suite_test.go

test: fix multi-zone test failure on capz multi-zone cluster
Fixes #
```
none
```

test: fix multi-zone test failure on capz multi-zone cluster

---

test/external-e2e/manifest/testdriver.yaml
test/external-e2e/run.sh

chore: upgrade ginkgo to v2

---

.github/workflows/static.yaml
.golangci.yml
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/identityserver.go
pkg/azuredisk/nodeserver.go
pkg/azurediskplugin/main.go
pkg/azureutils/fake_iohandler.go
pkg/csi-common/server_test.go
pkg/mounter/fake_safe_mounter.go
pkg/mounter/safe_mounter_unix.go
pkg/optimization/azure_skus_map.go
pkg/optimization/skus_test.go
test/e2e/dynamic_provisioning_test.go
test/e2e/testsuites/dynamically_provisioned_delete_pod_tester.go
test/e2e/testsuites/dynamically_provisioned_read_only_volume_tester.go
test/e2e/testsuites/dynamically_provisioned_shared_disk_tester.go
test/e2e/testsuites/dynamically_provisioned_statefulset_e2e_tester.go
test/e2e/testsuites/pre_provisioned_inline_volume_tester.go
test/e2e/testsuites/pre_provisioned_read_only_volume_tester.go
test/e2e/testsuites/pre_provisioned_shared_disk_tester.go
test/e2e/testsuites/specs.go
test/utils/azure/azure_helpers.go

/kind test
This is a cherry-pick of #2073 
Fixes #
```
none
```

[release-1.26] test: upgrade golangci/golangci-lint-action to v1.54

---

test/podFailover/workload/chart/templates/workload.yaml

/kind feature
Adding ability to bring your own storage class to pod failover tests.

chore: adding ability to BYO storage classes for pod failover

---

docs/driver-parameters.md

doc: update permissions and caching mode doc
Fixes #2199
```
none
```

doc: update permissions and caching mode doc

---

pkg/azuredisk/azuredisk_test.go
pkg/azureutils/azure_disk_utils.go

/kind bug
fix: Workload identity is not working.
Fixes #2229
```
fix: Workload identity is not working.
```

fix: Workload identity is not working.

---

pkg/azuredisk/azure_managedDiskController.go
pkg/util/util.go
pkg/util/util_test.go

/kind bug
fix: allow special char in tag value
Fixes #2245
```
fix: allow special char in tag value
```

fix: allow special char in tag value

---

pkg/azuredisk/controllerserver.go

/kind bug
fix: stop attaching disk when get disk lun failed
the driver should only attach disk when disk lun is not found on that VM
- current error messages
```
E0326 01:48:28.227240 1 azure_controller_common.go:547] error of getting data disks for node aks-xxx-vmss000002: Retriable: true, RetryAfter: 0s, HTTPStatusCode: 500, RawError: {"error":{"code":"InternalServerError","message":"Encountered internal server error. Diagnostic information: timestamp '20240326T014828Z', subscription id 'xxx', tracking id 'c336091e-8e0e-4f9f-a21e-27faeed73a94', request correlation id 'c336091e-8e0e-4f9f-a21e-27faeed73a94'."}}
2024-03-26 01:48:28.0000000	csi-azuredisk-controller			I0326 01:48:28.227258 1 controllerserver.go:411] …
```

fix: stop attaching disk when get disk lun failed

---

pkg/os/volume/volume.go

/kind bug
fix: possible dead loop in GetVolumeStats
related to issue #2235
Fixes #
```
fix: possible dead loop in GetVolumeStats
```

fix: possible dead loop in GetVolumeStats

---

pkg/azuredisk/azure_common_darwin.go
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/azure_common_windows.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_v2.go

/kind bug
fix: cache GetVolumeStats on Windows node
`(Get-Item -Path $Env:mount).Target` powershell command is an expensive call on Windows node, this PR adds a 10min expire cache into GetVolumeStats on Windows node, thus to reduce the calling number
```
I0411 02:02:50.830339   23500 utils.go:105] GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0411 02:02:50.830339   23500 utils.go:106] GRPC request: {"volume_id":"/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/MC_andy-aks127_andy-aks127_eastus2euap/providers/Microsoft.Compute/disks/pvc-f2aab55f-72a2-459b-bd78-eb865864afcf","volume_path":"c:\\var\\lib\\kubelet\\pods\\05906335-fed7-4564-abc5-2e3a1ae55f4e\\volumes\\kubernetes.io~csi\\pvc-f2aab55f-72a2-459b-bd …
```

fix: cache GetVolumeStats on Windows node

---

pkg/azuredisk/azure_common_darwin.go
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/azure_common_windows.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_v2.go

/kind bug
fix: cache GetVolumeStats on Windows node
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2273
`(Get-Item -Path $Env:mount).Target` powershell command is an expensive call on Windows node, this PR adds a 10min expire cache into GetVolumeStats on Windows node, thus to reduce the calling number
```
I0411 02:02:50.830339   23500 utils.go:105] GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0411 02:02:50.830339   23500 utils.go:106] GRPC request: {"volume_id":"/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/MC_andy-aks127_andy-aks127_eastus2euap/providers/Microsoft.Compute/disks/pvc-f2aab55f-72a2-459b-bd78-eb865864afcf","volume_path":"c:\\var\\lib\\kubelet\\pods\\05906335-fe …
```

[release-1.28] fix: cache GetVolumeStats on Windows node

---

pkg/azuredisk/azure_common_darwin.go
pkg/azuredisk/azure_common_linux.go
pkg/azuredisk/azure_common_windows.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_v2.go

/kind bug
fix: cache GetVolumeStats on Windows node
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2273
`(Get-Item -Path $Env:mount).Target` powershell command is an expensive call on Windows node, this PR adds a 10min expire cache into GetVolumeStats on Windows node, thus to reduce the calling number
```
I0411 02:02:50.830339   23500 utils.go:105] GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0411 02:02:50.830339   23500 utils.go:106] GRPC request: {"volume_id":"/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/MC_andy-aks127_andy-aks127_eastus2euap/providers/Microsoft.Compute/disks/pvc-f2aab55f-72a2-459b-bd78-eb865864afcf","volume_path":"c:\\var\\lib\\kubelet\\pods\\05906335-fe …
```

[release-1.29] fix: cache GetVolumeStats on Windows node

---

pkg/azuredisk/nodeserver.go

/kind bug
fix: print error logs in NodeGetVolumeStats
Fixes #
```
none
```

fix: print error logs in NodeGetVolumeStats

---

go.mod
pkg/azuredisk/nodeserver.go
pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/volume/volume.go

/kind bug
fix: refine GetFreeSpace call on Windows
this PR could get rid of expensive powershell command `(Get-Item -Path $Env:mount).Target`
```
I0412 11:24:54.552255   21436 utils.go:105] GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0412 11:24:54.552255   21436 utils.go:106] GRPC request: {"volume_id":"/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/MC_andy-aks127_andy-aks127_eastus2euap/providers/Microsoft.Compute/disks/pvc-9a2a1408-7661-46d6-ae6f-53f8139d501b","volume_path":"c:\\var\\lib\\kubelet\\pods\\ff7d184e-9672-447e-8036-7c3425f85233\\volumes\\kubernetes.io~csi\\pvc-9a2a1408-7661-46d6-ae6f-53f8139d501b\\mount"}
I0412 11:24:54.552255   21436 utils.go:112] GRPC response: …
```

fix: refine GetFreeSpace call on Windows

---

go.mod
pkg/azuredisk/nodeserver.go
pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/volume/volume.go

/kind bug
fix: refine GetFreeSpace call on Windows
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2287
this PR could get rid of expensive powershell command `(Get-Item -Path $Env:mount).Target`
```
I0412 11:24:54.552255   21436 utils.go:105] GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0412 11:24:54.552255   21436 utils.go:106] GRPC request: {"volume_id":"/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/MC_andy-aks127_andy-aks127_eastus2euap/providers/Microsoft.Compute/disks/pvc-9a2a1408-7661-46d6-ae6f-53f8139d501b","volume_path":"c:\\var\\lib\\kubelet\\pods\\ff7d184e-9672-447e-8036-7c3425f85233\\volumes\\kubernetes.io~csi\\pvc-9a2a1408-7661-46d6-ae6f-53f8139d501b\\mount"} …
```

[release-1.28] fix: refine GetFreeSpace call on Windows

---

go.mod
pkg/azuredisk/nodeserver.go
pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/volume/volume.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_managedDiskController.go

/kind bug
fix: refine GetFreeSpace call on Windows
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2287
this PR could get rid of expensive powershell command `(Get-Item -Path $Env:mount).Target`
```
I0412 11:24:54.552255   21436 utils.go:105] GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0412 11:24:54.552255   21436 utils.go:106] GRPC request: {"volume_id":"/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/MC_andy-aks127_andy-aks127_eastus2euap/providers/Microsoft.Compute/disks/pvc-9a2a1408-7661-46d6-ae6f-53f8139d501b","volume_path":"c:\\var\\lib\\kubelet\\pods\\ff7d184e-9672-447e-8036-7c3425f85233\\volumes\\kubernetes.io~csi\\pvc-9a2a1408-7661-46d6-ae6f-53f8139d501b\\mount"} …
```

[release-1.29] fix: refine GetFreeSpace call on Windows

---

go.mod
pkg/azuredisk/nodeserver.go
pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/volume/volume.go

/kind bug
fix: refine GetFreeSpace call on Windows
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2287
this PR could get rid of expensive powershell command `(Get-Item -Path $Env:mount).Target`
```
I0412 11:24:54.552255   21436 utils.go:105] GRPC call: /csi.v1.Node/NodeGetVolumeStats
I0412 11:24:54.552255   21436 utils.go:106] GRPC request: {"volume_id":"/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/MC_andy-aks127_andy-aks127_eastus2euap/providers/Microsoft.Compute/disks/pvc-9a2a1408-7661-46d6-ae6f-53f8139d501b","volume_path":"c:\\var\\lib\\kubelet\\pods\\ff7d184e-9672-447e-8036-7c3425f85233\\volumes\\kubernetes.io~csi\\pvc-9a2a1408-7661-46d6-ae6f-53f8139d501b\\mount"} …
```

[release-1.30] fix: refine GetFreeSpace call on Windows

---

pkg/azuredisk/azure_common_windows.go

/kind bug
fix: panic on Windows node when getFreeSpace failed on volume path
Fixes #2361
```
fix: panic on Windows node when getFreeSpace failed on volume path
```

fix: panic on Windows node when getFreeSpace failed on volume path

---

pkg/azuredisk/azuredisk.go

/kind bug
Adds code that is required for the parameter ReservedDataDiskSlotNum to be used 
**Special notes for your reviewer**: 
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/pkg/azuredisk/nodeserver.go#L395 was not modified even with VolumeAttachLimit < 0 
It seems the option wasn't given to the Driver.ReservedDataDiskSlotNum which was = to 0

fix: add ReservedDataDiskSlotNum copy from DriverOptions to Driver struct

---

pkg/azuredisk/azure_common_linux.go

/kind feature
feat: support NVME disk
Fixes #
<details>
```
I0726 12:16:23.959590       1 utils.go:106] GRPC request: {"publish_context":{"LUN":"2"},"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/disk.csi.azure.com/feff39288781b8a9437126cfecfe10952213f446af81ade220093cdd382ae7aa/globalmount","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":7}},"volume_context":{"requestedsizegib":"10","skuName":"StandardSSD_LRS","storage.kubernetes.io/csiProvisionerIdentity":"1721990465719-962-disk.csi.azure.com"},"volume_id":"/subscriptions/xxx/resourceGroups/shoot--hc-dev--d029266amd-haas/provid …
```

feat: support NVME disk

---

pkg/azuredisk/azure_managedDiskController.go
pkg/azuredisk/controllerserver.go

/kind bug
fix: create snapshot failure in edge zone
<details>
```
I0801 17:27:57.425602       1 utils.go:77] GRPC call: /csi.v1.Controller/CreateSnapshot
I0801 17:27:57.425628       1 utils.go:78] GRPC request: {"name":"snapshot-ec660e34-1f38-41de-9b1a-093aee63d751","source_volume_id":"/subscriptions/xxx/resourceGroups/mc_e2erg-ebld99563156-pzypqanubzn_e2eaks-qpj_westus/providers/Microsoft.Compute/disks/pvc-54b33ee8-ab52-444e-874e-82845edf6564"}
I0801 17:27:57.425862       1 controllerserver.go:986] begin to create snapshot(snapshot-ec660e34-1f38-41de-9b1a-093aee63d751, incremental: true) under rg(mc_e2erg-ebld99563156-pzypqanubzn_e2eaks-qpj_westus) region(westus)
I0801 17:27:57.765070       1 azure_armclient.go:301] …
```

fix: create snapshot failure in edge zone

---

pkg/azuredisk/controllerserver.go

/kind bug
fix: create snapshot failure in edge zone
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2450
<details>
```
I0801 17:27:57.425602       1 utils.go:77] GRPC call: /csi.v1.Controller/CreateSnapshot
I0801 17:27:57.425628       1 utils.go:78] GRPC request: {"name":"snapshot-ec660e34-1f38-41de-9b1a-093aee63d751","source_volume_id":"/subscriptions/xxx/resourceGroups/mc_e2erg-ebld99563156-pzypqanubzn_e2eaks-qpj_westus/providers/Microsoft.Compute/disks/pvc-54b33ee8-ab52-444e-874e-82845edf6564"}
I0801 17:27:57.425862       1 controllerserver.go:986] begin to create snapshot(snapshot-ec660e34-1f38-41de-9b1a-093aee63d751, incremental: true) under …
```

[release-1.29] fix: create snapshot failure in edge zone

---

.github/workflows/static.yaml
.golangci.yml
pkg/azuredisk/azure_common_linux_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/azuredisk_v1.go
pkg/azuredisk/azuredisk_v1_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/controllerserver_v2.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go
pkg/azurediskplugin/main.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
pkg/azureutils/azure_snapshot_utils.go
pkg/azureutils/azure_snapshot_utils_test.go
pkg/csi-common/utils_test.go
pkg/os/disk/types.go
pkg/os/volume/volume.go
pkg/tool/gen-disk-skus-map.go
pkg/util/util.go
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
test/e2e/testsuites/testsuites.go

/kind cleanup
[release-1.28] cleanup: upgrade golint version and fix golint errors
cherry-pick for https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2487
Fixes #
```
none
```

[release-1.28] cleanup: upgrade golint version and fix golint errors

---

.github/workflows/static.yaml
pkg/azuredisk/azure_common_linux_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/azuredisk_v1.go
pkg/azuredisk/azuredisk_v1_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azurediskplugin/main.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go
pkg/azureutils/azure_snapshot_utils.go
pkg/os/disk/types.go
pkg/util/util.go
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
test/e2e/testsuites/testsuites.go

/kind cleanup
[release-1.28] fix golint and disable staticcheck
Fixes #
```
none
```

[release-1.28] fix golint and disable staticcheck

---

.github/workflows/static.yaml
pkg/azuredisk/azure_common_linux_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go
pkg/azuredisk/azuredisk_v1.go
pkg/azuredisk/azuredisk_v1_test.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/controllerserver_test.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/nodeserver.go
pkg/azurediskplugin/main.go
pkg/csi-common/server.go
pkg/os/disk/types.go
pkg/util/util.go
test/e2e/pre_provisioning_test.go
test/e2e/suite_test.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_detach_tester.go
test/e2e/testsuites/dynamically_provisioned_azuredisk_tag_tester.go
test/e2e/testsuites/dynamically_provisioned_resize_volume_tester.go
test/e2e/testsuites/testsuites.go

/kind cleanup
[release-1.29] fix golint and disable staticcheck
Fixes #
```
none
```

[release-1.29] fix golint and disable staticcheck

---

test/e2e/dynamic_provisioning_test.go

/kind test
test: add snapshot restore test on xfs file system
Fixes #
```
none
```

test: add snapshot restore test on xfs file system

---

pkg/azuredisk/azure_controller_common.go

Customers can use VAC to migrate `PremiumLRS` disks to `PremiumV2LRS` disks while they are detached from the VM. While the driver already sets caching mode to `None` when it creates a `PremiumV2LRS` disk, it still defaults to either the caching mode set in the `VolumeContext` or to `ReadOnly` caching when it attaches the disk. Because caching in the `VolumeContext` defaults and is set to `ReadOnly` for `PremiumLRS` disks, to support attach operation after the migration, the driver must set the caching mode to `None` explicitly when it attaches a `PremiumV2LRS` disk.
Fixes #
```
none
```

fix: support attach operations after premiumV2 disk migration

---

pkg/azuredisk/azuredisk.go

/kind bug
fix: vm-type is not overriding as expected
Fixes #2533 
azuredisk log:
```
I1104 06:08:41.447295       1 azuredisk.go:223] override VMType(vmss) in cloud config as standard
I1104 06:08:41.447305       1 azuredisk.go:230] disable UseInstanceMetadata for controller
I1104 06:08:41.447316       1 azuredisk.go:242] cloud: AzurePublicCloud, location: eastus2, rg: MC_aks-yxytest_group_aks-yxytest_eastus2, VMType: standard, PrimaryScaleSetName: aks-userpool-34645390-vmss, PrimaryAvailabilitySetName: , DisableAvailabilitySetNodes: false
I1104 06:08:41.450388       1 mount_linux.go:285] 'umount …
```

fix: vm-type is not overriding as expected

---

pkg/azurediskplugin/Dockerfile

Reverts kubernetes-sigs/azuredisk-csi-driver#2490
alpine base image 3.20.2 works on `Ubuntu 22.04.4 LTS   6.5.0-1024-azure`, but it's broken on `Ubuntu 22.04.5 LTS   5.15.0-1073-azure` with xfs mount with following error:
```
'could not format /dev/disk/azure/scsi1/lun0(lun: 0), and mount it at /var/lib/kubelet/plugins/kubernetes.io/csi/disk.csi.azure.com/90564df3fd2ed9991ce81f6ca7aab17a7f871e17839da16460c96c3f5dceb0da/globalmount, failed with mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t xfs -o nouuid,defaults /dev/disk/azure/scsi1/lun0 /var/lib/kubelet/plugins/kubernetes.io/csi/disk.csi.azure.com/90564df3fd2ed9991ce81f6ca7aab17a7f871e17839da16460c96c3f5dceb0da/globalmount
Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/disk.csi.azure.com/90564df3fd …
```

Revert "chore: upgrade to base image alpine 3.20.2"

---

docs/driver-parameters.md

If you assign the permissions listed in [driver-parameters.md](docs/driver-parameters.md) to the azuredisk-csi-driver and attempt to use the `diskEncryptionSetID` driver parameter, the driver will fail to provision a disk with a linked authorization failure. 
```
failed to provision volume with StorageClass "des-disk-csi": rpc error: code = Internal desc = Retriable: false, RetryAfter: 0s, HTTPStatusCode: 403, RawError: \{"error":{"code":"LinkedAuthorizationFailed","message":"The client '<client>' with object id '<object-id>' has permission to perform action 'Microsoft.Compute/disks/write' on scope '/subscriptions/<subscription-id>/resourceGroups/<resource-group>/providers/Microsoft.Compute/disks/pvc-5 …
```

docs: Add missing disk encryption set read permission

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/fake_azuredisk.go
pkg/azuredisk/fake_azuredisk_v2.go
pkg/mounter/fake_safe_mounter.go
pkg/mounter/safe_mounter_unix.go
pkg/mounter/safe_mounter_unix_test.go
pkg/mounter/safe_mounter_windows.go

/king bug
bug: add serial format limit to fix OOM issue when formatting a few disks in parallel in csi-azuredisk-node
add flags `max-concurrent-format` and `concurrent-format-timeout` as default 2 and 2 minutes
Fixes #
```
fix: add serial format limit to fix OOM issue when formatting a few disks in parallel in csi-azuredisk-node
```

fix: add serial format limit to fix OOM issue when formatting a few disks in parallel in csi-azuredisk-node

---

pkg/azuredisk/controllerserver.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind feature
feat: pick region when zonal node pool is in different region, this only works when in a zonal node pool 
Fixes #
<details>
```
I1120 08:59:32.941891       1 utils.go:105] GRPC call: /csi.v1.Controller/CreateVolume
I1120 08:59:32.941921       1 utils.go:106] GRPC request: {"accessibility_requirements":{"preferred":[{"segments":{"topology.disk.csi.azure.com/zone":"eastus2-1","topology.kubernetes.io/zone":"eastus2-1"}}],"requisite":[{"segments":{"topology.disk.csi.azure.com/zone":"eastus2-1","topology.kubernetes.io/zone":"eastus2-1"}}]},"capacity_range":{"required_bytes":10737418240},"name":"pvc-a40152bb-3ca5-4951-9368-eb7 …
```

feat: pick region when zonal node pool is in different region

---

pkg/azuredisk/azuredisk_option.go

/kind bug
chore: increase format timeout as 300s by default
I have observed that it costs 83s to format a 30TB disk:
```
I1126 07:00:17.583179       1 utils.go:105] GRPC call: /csi.v1.Node/NodeStageVolume
I1126 07:00:17.583205       1 utils.go:106] GRPC request: {"publish_context":{"LUN":"0"},"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/disk.csi.azure.com/a621ec8e71c62e341ae812c978f90f00af8507b7dcb7380a9430e86b5fe65ac8/globalmount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":7}},"volume_context":{"csi.storage.k8s.io/pv/name":"pvc-c0cc6ce6-039c-43a2-a0e1-99f9261364b0","csi.storage.k8s.io/pvc/name":"persistent-storage-statefulset-azuredisk-bigdisk-1","csi.storage.k8s.io/pvc/name …
```

chore: increase format timeout as 300s by default

---

pkg/azuredisk/azure_common_windows.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/volume/volume.go

/kind bug
fix: unmount volume issue on Windows node, original behavior is just deleting the mounted directory which may lead to mount failure in frequent unmount and mount the same volume on the same node
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2691
```
I1204 14:39:28.920234    1336 utils.go:105] GRPC call: /csi.v1.Node/NodeUnpublishVolume
I1204 14:39:28.920234    1336 utils.go:106] GRPC request: {"target_path":"c:\\var\\lib\\kubelet\\pods\\d17b945a-2f91-4bfc-b5c9-28e886c86525\\volumes\\kubernetes.io~csi\\pvc-6afee86b-e9b9-4e63-a8a0-d49b887fd682\\mount","volume_id":"/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/MC_andy-aks129_andy-aks129_eastus2/providers/Microsoft.C …
```

[release-1.30] fix: unmount volume issue on Windows node

---

pkg/azuredisk/azure_common_windows.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/volume/volume.go

/kind bug
fix: unmount volume issue on Windows node, original behavior is just deleting the mounted directory which may lead to mount failure in frequent unmount and mount the same volume on the same node
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2691
```
I1204 14:39:28.920234    1336 utils.go:105] GRPC call: /csi.v1.Node/NodeUnpublishVolume
I1204 14:39:28.920234    1336 utils.go:106] GRPC request: {"target_path":"c:\\var\\lib\\kubelet\\pods\\d17b945a-2f91-4bfc-b5c9-28e886c86525\\volumes\\kubernetes.io~csi\\pvc-6afee86b-e9b9-4e63-a8a0-d49b887fd682\\mount","volume_id":"/subscriptions/b9d2281e-dcd5-4dfd-9a97-0d50377cdf76/resourceGroups/MC_andy-aks129_andy-aks129_eastus2/providers/Microsoft.C …
```

[release-1.29] fix: unmount volume issue on Windows node

---

go.mod

/kind bug
Revert to go 1.22 windows filesystem behavior building with go 1.23 until use of Stat/Lstat/EvalSymlinks adjusts to go1.23 behavior
- golang 1.23.1 building with `godebug winreadlinkvolume=0` 
```
C:\>dir C:\var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\72bb2b07b6028371cea50fb631344dc9113f0846681814572edb765f698195da
Volume in drive C is Windows
Volume Serial Number is 663A-A45B
Directory of C:\var\lib\kubelet\plugins\kubernetes.io\csi\disk.csi.azure.com\72bb2b07b6028371cea50fb631344dc9113f0846681814572edb765f698195da
09/11/2024  03:33 AM    <DIR>          .
12/05/2024  08:21 AM    <DIR>          ..
09/11/2024  03:33 AM    <JUNCTION>     globalmount [\??\Volume{99cc61ac-6fec-11ef-bbb1-cd4785e79c6b}\]
09/11/2024  03:34 AM               230 vol_data.json
1 File(s) …
```

fix: revert to go1.22 windows filesystem stdlib behavior

---

pkg/azureutils/azure_disk_utils.go

/kind bug
fix: allow more powershell command running at same time on Windows node
Fixes #2690
```
fix: allow more powershell command running at same time on Windows node
```

fix: allow more powershell command running at same time on Windows node

---

pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/filesystem/filesystem.go
pkg/os/volume/volume.go

/kind cleanup
cleanup: windows functions
Fixes #
```
none
```

cleanup: windows functions

---

pkg/azuredisk/azure_common_windows.go
pkg/azuredisk/nodeserver.go
pkg/os/volume/volume.go

/kind bug
fix: resize is required after snapshot restore/volume clone on Windows
Fixes #
```
none
```

fix: resize is required after snapshot restore/volume clone on Windows

---

pkg/azuredisk/azure_common_linux.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind feature
feat: add noformat option to fix fsck stuck issue
when disk PV is quite big(e.g. 30TB) and it contains lots of files, fsck could be stuck there for long time, this PR supports adding a `noformat` mount option in disk pv, then the already formatted disk will not be fsck check again, this could save a lot of time for fsck
<details>
```
I1222 03:15:01.101253       1 utils.go:105] GRPC call: /csi.v1.Node/NodeStageVolume
I1222 03:15:01.101281       1 utils.go:106] GRPC request: {"publish_context":{"LUN":"0"},"staging_target_path":"/var/lib/kubelet/plugins/kubernetes.io/csi/disk.csi.azure.com/6315f0e19af4e6a13e09168e7165aa7f08235b3e975873eccfa6db02a4c3ec97/globalmount","volume_capability":{"AccessType":{"Mount":{" …
```

feat: add noformat option to fix fsck stuck issue

---

pkg/azuredisk/azure_common_linux.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind feature
feat: add noformat option to fix fsck stuck issue on Linux node
when disk PV is quite big(e.g. 30TB) and it contains lots of files, fsck could be stuck there for long time, this PR supports adding a `noformat` mount option in disk pv, then the already formatted disk will not be fsck check again, this could save a lot of time for fsck
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2751
Fixes #
```
none
```

[release-1.29] feat: add noformat option to fix fsck stuck issue on Linux node

---

pkg/azuredisk/azure_common_linux.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind feature
feat: add noformat option to fix fsck stuck issue on Linux node
when disk PV is quite big(e.g. 30TB) and it contains lots of files, fsck could be stuck there for long time, this PR supports adding a `noformat` mount option in disk pv, then the already formatted disk will not be fsck check again, this could save a lot of time for fsck
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2751
Fixes #
```
none
```

[release-1.30] feat: add noformat option to fix fsck stuck issue on Linux node

---

pkg/tool/gen-disk-skus-map.go
pkg/tool/gen-disk-skus-map_test.go

This pull request includes changes to the `pkg/tool/gen-disk-skus-map.go` file to improve code maintainability and the addition of a new test file `pkg/tool/gen-disk-skus-map_test.go`.
Code maintainability improvements:
* Introduced a new `exit` function to handle program termination, replacing direct calls to `os.Exit` with calls to the `exit` function. (`pkg/tool/gen-disk-skus-map.go`) [[1]](diffhunk://#diff-1029231156796ebf6e7dcab9853facf923ad1796ab8aad9eca3567ebddd1fb50R52-R56) [[2]](diffhunk://#diff-1029231156796ebf6e7dcab9853facf923ad1796ab8aad9eca3567ebddd1fb50L140-R145) [[3]](diffhunk://#diff-1029231156796ebf6e7dcab9853facf923ad1796ab8aad9eca3567ebddd1fb50L149-R154)
Testing improvements:
* Added a new test file `pkg/tool/gen-disk-skus-map_test.go` to include a unit test for the …

test: add UT for gen-disk-skus-map_test

---

pkg/tool/gen-disk-skus-map.go
pkg/tool/gen-disk-skus-map_test.go
pkg/tool/skus-sample.json

This pull request introduces a new test scenario for generating disk SKU maps and includes a sample JSON file for testing purposes. The changes primarily focus on adding conditional logic to handle the test scenario and updating the test setup accordingly.
Key changes include:
* [`pkg/tool/gen-disk-skus-map.go`](diffhunk://#diff-1029231156796ebf6e7dcab9853facf923ad1796ab8aad9eca3567ebddd1fb50R98-R110): Added conditional logic to check for the `TEST_SCENARIO` environment variable and use the `skus-sample.json` file if set. This allows for a predefined set of SKUs to be used during testing.
* [`pkg/tool/gen-disk-skus-map_test.go`](diffhunk://#diff-9494507c5160c887e22c02223e9a45d7697145b3b9e48669713086fe4064235bR25-R28): Updated the test setup to set the `TEST_SCENARIO` environment variable …

test: refine UT for gen-disk-skus-map_test

---

pkg/filewatcher/filewatcher.go
pkg/filewatcher/filewatcher_test.go

This pull request includes changes to improve the handling of program termination and adds a test for the `WatchFileForChanges` function. The most important changes include the introduction of a separate `exit` function and the addition of a comprehensive test for file watching.
Improvements to program termination handling:
* [`pkg/filewatcher/filewatcher.go`](diffhunk://#diff-5d8d60fa78da8b711b2e021fa0643a9e8d880a4ed6eca069019dd76d9a37677eR28-R32): Introduced a separate `exit` function to handle program termination, replacing direct calls to `os.Exit` with this function. [[1]](diffhunk://#diff-5d8d60fa78da8b711b2e021fa0643a9e8d880a4ed6eca069019dd76d9a37677eR28-R32) [[2]](diffhunk://#diff-5d8d60fa78da8b711b2e021fa0643a9e8d880a4ed6eca069019dd76d9a37677eL67-R72)
Addition of tests:
* …

test: add UT for filewatcher

---

pkg/filewatcher/filewatcher.go
pkg/filewatcher/filewatcher_test.go

This pull request introduces updates to the `pkg/filewatcher` package to improve testing and error handling. The most important changes include adding a reset function for a sync variable and a new test case for handling non-existent files.
Improvements to testing:
* [`pkg/filewatcher/filewatcher.go`](diffhunk://#diff-5d8d60fa78da8b711b2e021fa0643a9e8d880a4ed6eca069019dd76d9a37677eR35-R39): Added a `resetWatchCertificateFileOnce` function to reset the `watchCertificateFileOnce` variable for testing purposes.
* [`pkg/filewatcher/filewatcher_test.go`](diffhunk://#diff-1f58eb1a770908ddeb74a9fdfcb0345888f1a6cdf9ac1e2531ea643728fad8f5R21): Imported the `strings` package to support string operations in tests.
* [`pkg/filewatcher/filewatcher_test.go`](diffhunk://#diff-1f58eb1a770908ddeb74a9fdfcb0 …

test: add UT negative case for filewatcher

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_test.go

/kind bug
fix: wrong node matching when detaching dangling disk (edge case)
in following logs, the two VMSS nodes are actually the same node, with this fix, CSI driver will regard that this disk is already attached to the correct node instead of detaching the disk and re-attach it to the same node.
Fixes #
```
fix: wrong node matching when detaching dangling disk
```

fix: wrong node matching when detaching dangling disk

---

.github/workflows/linux.yml
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_windows.go

/kind test
test: improve ut coverage
Fixes #
```
none
```

test: improve ut coverage

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
test/e2e/suite_test.go

/kind bug
fix: set get disk timeout as 15s and make it configurable
Fixes #
```
fix: set get disk timeout as 15s and make it configurable
```

fix: set get disk timeout as 15s and make it configurable

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
test/e2e/suite_test.go

/kind bug
fix: set get disk timeout as 15s and make it configurable
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2857
Fixes #
```
fix: set get disk timeout as 15s and make it configurable
```

[release-1.30] fix: set get disk timeout as 15s and make it configurable

---

pkg/azuredisk/controllerserver.go

/kind bug
fix: obsolete vmss cache issue after disk is resized successfully
```
I0210 09:51:07.224054       1 azure_managedDiskController.go:412] azureDisk - resize disk(pvc-32b5d157-73d6-46be-bbb3-f261360623ae) with new size(20) completed
I0210 09:51:07.224084       1 controllerserver.go:944] expand azure disk(/subscriptions/46678f10-4bbb-447e-98e8-d2829589f2d8/resourceGroups/capz-1zdete/providers/Microsoft.Compute/disks/pvc-32b5d157-73d6-46be-bbb3-f261360623ae) successfully, currentSize(21474836480)
I0210 09:51:07.224180       1 controllerserver.go:949] delete cache for node (capz-1zdete-mp-0000001, /subscriptions/46678f10-4bbb-447e-98e8-d2829589f2d8/resourceGroups/capz-1zdete/providers/Microsoft.Compute/virtualMachineS …
```

fix: obsolete vmss cache issue after disk is resized successfully

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azure_managedDiskController.go

/kind bug
fix: disable batch attach when hitting MaximumDataDisksExceeded error
example error:
```
azure_armclient.go:301] Received error in sendAsync.send: resourceID: http://localhost:7788/subscriptions/xx/resourceGroups/xxx/providers/Microsoft.Compute/virtualMachineScaleSets/aks-xxx/virtualMachines/5?api-version=2022-03-01, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: OperationNotAllowed, The maximum number of data disks allowed to be attached to a VM of this size is 8
```
Fixes #2851
```
none
```

fix: disable batch attach when hitting MaximumDataDisksExceeded error

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azure_managedDiskController.go

/kind bug
fix: disable batch attach when hitting MaximumDataDisksExceeded error
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2883
example error:
```
azure_armclient.go:301] Received error in sendAsync.send: resourceID: http://localhost:7788/subscriptions/xx/resourceGroups/xxx/providers/Microsoft.Compute/virtualMachineScaleSets/aks-xxx/virtualMachines/5?api-version=2022-03-01, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: OperationNotAllowed, The maximum number of data disks allowed to be attached to a VM of this size is 8
```
Fixes #2851
```
none
```

[release-1.30] fix: disable batch attach when hitting MaximumDataDisksExceeded error

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azure_managedDiskController.go

/kind bug
fix: disable batch attach when hitting MaximumDataDisksExceeded error
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2883
example error:
```
azure_armclient.go:301] Received error in sendAsync.send: resourceID: http://localhost:7788/subscriptions/xx/resourceGroups/xxx/providers/Microsoft.Compute/virtualMachineScaleSets/aks-xxx/virtualMachines/5?api-version=2022-03-01, error: Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: OperationNotAllowed, The maximum number of data disks allowed to be attached to a VM of this size is 8
```
Fixes #2851
```
none
```

[release-1.31] fix: disable batch attach when hitting MaximumDataDisksExceeded error

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_loadbalancer.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_publicip_repo.go
vendor/sigs.k8s.io/cloud-provider-azure/pkg/provider/azure_routes.go

/kind bug
fix: incorrect cloud provider setting in sovereign cloud
related to https://github.com/kubernetes-sigs/cloud-provider-azure/pull/8504
the cloud provider with track2 sdk does not work in Azure China cloud, error is like following:
```
E0304 04:59:58.032152       1 utils.go:110] GRPC error: rpc error: code = Internal desc = ManagedIdentityCredential authentication failed. the requested identity isn't assigned to this resource
GET http://169.254.169.254/metadata/identity/oauth2/token
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
--------------------------------------------------------------------------------
{
"error": "invalid_resource",
"error_description": "AADSTS500011: The resource principal named …
```

fix: incorrect cloud provider setting in sovereign cloud

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azure_managedDiskController.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/controllerserver.go

/kind bug
fix: detach disk should have more priority than attach disk on the same node, this could reduce the MaximumDataDisksExceeded error occurrence. This PR also reverts https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2883
Fixes #2851
```
fix: detach disk should have more priority than attach disk on the same node
```

fix: detach disk should have more priority than attach disk on the same node

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azure_managedDiskController.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/controllerserver.go

/kind bug
fix: detach disk should have more priority than attach disk on the same node, this could reduce the MaximumDataDisksExceeded error occurrence. 
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2992
Fixes #
```
fix: detach disk should have more priority than attach disk on the same node
```

[release-1.30] fix: detach disk should have more priority than attach disk on the same node

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azure_managedDiskController.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/controllerserver.go

/kind bug
fix: detach disk should have more priority than attach disk on the same node, this could reduce the MaximumDataDisksExceeded error occurrence. 
cherrypick of https://github.com/kubernetes-sigs/azuredisk-csi-driver/pull/2992
Fixes #
```
fix: detach disk should have more priority than attach disk on the same node
```

[release-1.31] fix: detach disk should have more priority than attach disk on the same node

---

deploy/example/vpa/README.md
deploy/example/vpa/install-components/admission-controller-deployment.yaml
deploy/example/vpa/install-components/delete-webhook.sh
deploy/example/vpa/install-components/gencerts.sh
deploy/example/vpa/install-components/recommender-deployment.yaml
deploy/example/vpa/install-components/rmcerts.sh
deploy/example/vpa/install-components/updater-deployment.yaml
deploy/example/vpa/install-components/vpa-rbac.yaml
deploy/example/vpa/install-components/vpa-v1-crd-gen.yaml
deploy/example/vpa/install-components/warn-obsolete-vpa-objects.sh
deploy/example/vpa/install-vpa.sh
deploy/example/vpa/uninstall-vpa.sh
deploy/example/vpa/vertical-pod-autoscaler.yaml
hack/verify-yamllint.sh

/kind feature
feat: add VerticalPodAutoscaler to csi controller pod
Fixes #
```
none
```

feat: add VerticalPodAutoscaler to csi controller pod

---

pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/disk/disk.go

/kind bug
fix: incorrect disk num discovery on Windows 2019 node
Fixes #3029
<details>
```
ConvertTo-Json @(Get-CimInstance win32_diskdrive | Where-Object { $_.Model -eq "Virtual_Disk NVME Premium" -or $_.SCSIPort -eq 3 })
ConvertTo-Json @(Get-CimInstance win32_diskdrive | Where-Object { $_.Model -eq "Virtual_Disk NVME Premium" -or $_.SCSIPort -eq 3 } | Select-Object Index, SCSILogicalUnit, SCSITargetId, SCSIPort, SCSIBus, Model)
PS C:\hpc> ConvertTo-Json @(Get-CimInstance win32_diskdrive | Where-Object { $_.Model -eq "Virtual_Disk NVME Premium" -or $_.SCSIPort -Ne 0 } | Select-Object Index, SCSILogicalUnit, SCSITargetId, SCSIPort, …
```

fix: incorrect disk num discovery on Windows 2019 node

---

pkg/mounter/safe_mounter_host_process_windows.go
pkg/os/cim/disk.go
pkg/os/disk/disk.go
pkg/os/disk/disk_cim.go
pkg/os/volume/volume_cim.go

/kind feature
This PR leverages of WMI interfaces to replace the PowerShell functions for Windows related storage operations,
which improve the overall performance 
<details>
```
I0427 03:03:18.372866     772 utils.go:105] GRPC call: /csi.v1.Node/NodeStageVolume
I0427 03:03:18.372866     772 utils.go:106] GRPC request: {"publish_context":{"LUN":"0"},"staging_target_path":"\\var\\lib\\kubelet\\plugins\\kubernetes.io\\csi\\disk.csi.azure.com\\a63e2d3886284cfbdb45cce97cb66a469f363a5574afdefac52747fc5ca18b42\\globalmount","volume_capability":{"AccessType":{"Mount":{}},"access_mode":{"mode":7}},"volume_context":{"csi.storage.k8s.io/pv/name":"pvc-eec2e808-ec85-4cd0-bf30-e80cbaa117be","c …
```

feat: Use WMI to implement Disk API to reduce PowerShell overhead#2

---

pkg/azuredisk/azure_controller_common.go
pkg/azuredisk/azure_controller_common_test.go
pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/controllerserver.go
pkg/azuredisk/nodeserver.go
pkg/azuredisk/nodeserver_test.go
pkg/azuredisk/nodeserver_v2.go

fix: adjust the batch size as per the number of disks allowed

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind feature
feat: add option to override ARM retry-after header
Fixes #
<details>
```
I0512 02:39:48.626649       1 main.go:112] set up prometheus server on [::]:29604
I0512 02:39:48.626719       1 main.go:87] Sys info: NumCPU: 2 MAXPROC: 2
W0512 02:39:48.626730       1 azuredisk.go:204] nodeid is empty
I0512 02:39:48.626738       1 azuredisk.go:225] driver userAgent: disk.csi.azure.com/v1.32.5 OSS-kubectl
W0512 02:39:48.626746       1 client_config.go:667] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0512 02:39:48.627404       1 azure_disk_utils.go:155] reading cloud config …
```

[release-1.32] feat: add option to override ARM retry-after header

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind feature
feat: add option to override ARM retry-after header
Fixes #
<details>
```
I0512 02:39:48.626649       1 main.go:112] set up prometheus server on [::]:29604
I0512 02:39:48.626719       1 main.go:87] Sys info: NumCPU: 2 MAXPROC: 2
W0512 02:39:48.626730       1 azuredisk.go:204] nodeid is empty
I0512 02:39:48.626738       1 azuredisk.go:225] driver userAgent: disk.csi.azure.com/v1.32.5 OSS-kubectl
W0512 02:39:48.626746       1 client_config.go:667] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0512 02:39:48.627404       1 azure_disk_utils.go:155] reading cloud config …
```

[release-1.31] feat: add option to override ARM retry-after header

---

pkg/azuredisk/azuredisk.go
pkg/azuredisk/azuredisk_option.go
pkg/azuredisk/azuredisk_v2.go
pkg/azuredisk/controllerserver.go
pkg/azureutils/azure_disk_utils.go
pkg/azureutils/azure_disk_utils_test.go

/kind feature
Due to CRP extension bug, ARM polling GET responses are being given a high retry-after value after a certain number of retries. To mitigate the impact of the impact of this bug, this PR adds an option to override the retry-after header in http response when the value is lower than the configured minimum. This would allow the driver to poll for GET with a longer delay in between, lessening the frequency of large retry-after.
Fixes #
```
none
```

feat: add option to override ARM retry-after header if the value is lower than the configured minimum

---

docs/driver-parameters.md

I admit I don't fully understand Azure permissions. I think that when the CSI driver patches a VM to attach a disk, Azure evaluates *all* fields of the VM and not only the changed ones. Azure then evaluates all "link"/"action" permissions of anything that is linked to the VM - load balancers, security groups, network interfaces etc, even though the CSI driver never modifies these VM properties.
I'm adding the permissions found in an internal audit. However, I don't know _what else_ can be linked to a VM. The list may be quite incomplete. And it's not very future proof, as Azure may link other objects to the VMs in the future and we will need to update the driver permissions. It would be great if the …

doc: add linked permissions

---

pkg/azuredisk/controllerserver.go

/kind feature
This PR introduces a custom disk naming logic to the Azure Disk CSI driver:
- When both the PVC namespace and name tags are present and non-empty, the Azure disk will be named as `<namespace>-<pvcname>`.
- If either tag is missing, the default disk naming logic is used.
- The disk name is always sanitized to meet Azure requirements.
This improves traceability and operational clarity by making disk names more meaningful and directly linked to their originating PVCs.
Fixes #3174
- The logic is implemented in the `CreateVolume` method in `controllerserver.go`.
- Example: If a PVC has namespace `prod` …

support custom Azure disk naming using PVC name and namespace [#3174]

---

pkg/azuredisk/azuredisk_option.go

/kind bug
fix: disable enable-minimum-retry-after by default
```
during the polling phase while waiting for CRP to finalize attaching disks, Azure tells us to retry  after X seconds (4/2/2/2), which is less than the expected 5 according to the logic. In doing so, we remove the header... And according to the Azure SDK, For long running operations and respective polling: [General Guidelines: API Design | Azure SDKs](https://azure.github.io/azure-sdk/general_design.html#long-running-operations).
DO support the following polling configuration options:
pollInterval
Polling configuration may be used only in the absence of relevant retry-after headers from service, and otherwise should be ignored.
And from the poller source …
```

fix: disable enable-minimum-retry-after by default
